import type {
  TrustBadge, Package, ItineraryDay, HotelTier,
  MonthRating, Season, FAQ, Testimonial, RelatedDestination,
  Experience, WhatsAppConfig, ProcessStep, DestinationTheme, LeadFormConfig
} from '@/lib/shared/types'

export const shimlaData = {
  meta: {
    title: 'Shimla Tour Packages — Family & Honeymoon Trips | Outbound Travelers',
    description: 'Plan your Shimla trip with Outbound Travelers. Family, honeymoon & group packages with hotels, toy train, transfers. Get a lightning-fast custom quote today.',
    canonical: 'https://www.outboundtravelers.com/shimla',
    ogImage: 'https://picsum.photos/seed/shimla-og/1200/630',
    h1: 'Shimla Tour Packages — The Queen of Hills, Planned for You',
  },
  theme: {
    accentColor: '#2F5233',
    accentSoft: '#E8EFE6',
    motif: 'pine-cone',
  } as DestinationTheme,
  hero: {
    variant: 'HeroSplit',
    headline: 'Shimla, Where Every Season Tells a Story',
    subheadline: 'Snow in winter, apple blossoms in spring, cool summers, golden autumn — family holidays and honeymoons planned end-to-end by hill station specialists.',
    primaryCta: 'Get my Shimla quote',
    secondaryCta: 'Or talk to a travel expert on WhatsApp',
    desktopImage: 'https://picsum.photos/seed/shimla-hero-d/1920/1080',
    mobileImage: 'https://picsum.photos/seed/shimla-hero-m/800/1200',
    imageAlt: 'Shimla Mall Road colonial architecture snow winter Himachal Pradesh',
    quickStats: [
      { label: 'Altitude', value: '2,205m' },
      { label: 'Best Season', value: 'Oct–Jun' },
      { label: 'Ideal Duration', value: '4–6 nights' },
      { label: 'Starting From', value: '₹[TBD] pp' },
    ],
  },
  trustBadges: [
    { icon: 'trips', label: '2,500+ trips delivered' },
    { icon: 'custom', label: '100% customizable' },
    { icon: 'verified', label: 'Verified hotels' },
    { icon: 'support', label: '24/7 on-trip support' },
    { icon: 'quote', label: 'Lightning quotes' },
    { icon: 'member', label: 'TAFI/IATA member' },
  ] as TrustBadge[],
  quickSummary: {
    duration: '4–6 nights ideal',
    bestSeason: 'Oct–Jun (Snow · Spring · Summer)',
    startingFrom: 'From ₹[TBD] per person',
    tripTypes: 'Family · Honeymoon · Group · Senior',
  },
  whyVisit: [
    {
      icon: 'specialist',
      title: 'Family-tested itineraries',
      description: 'Every Shimla itinerary we build is paced for families — comfortable drives, child-friendly hotels, senior-accessible sightseeing, no rushed mornings.',
    },
    {
      icon: 'verified',
      title: 'Toy train + full logistics sorted',
      description: 'Kalka–Shimla toy train booking, hotel pickups, and all hill transfers in comfortable vehicles — arranged before you leave home.',
    },
    {
      icon: 'southindia',
      title: 'South India to Shimla, easy',
      description: 'Flights from Chennai, Bangalore, Kochi to Delhi or Chandigarh, then a scenic drive or toy train to Shimla — we plan every connection.',
    },
  ],
  experiences: [
    { id: 'toy-train', title: 'Kalka–Shimla Toy Train', description: 'A UNESCO World Heritage railway winding through 102 tunnels and 864 bridges across the Shivalik hills. The most scenic train ride in North India — book early, fills fast.', image: 'https://picsum.photos/seed/toy-train/800/600', alt: 'Kalka Shimla toy train UNESCO heritage railway Himachal', seasonal: false },
    { id: 'mall-road', title: 'Mall Road & The Ridge', description: 'Shimla\'s colonial heart — Victorian-era buildings, Christ Church, Gaiety Theatre, and mountain views on a clear day all the way to Jakhu peak.', image: 'https://picsum.photos/seed/mall-road/800/600', alt: 'Shimla Mall Road Ridge colonial buildings Himachal Pradesh', seasonal: false },
    { id: 'kufri', title: 'Kufri Snow Point & Adventure Park', description: 'Shimla\'s most popular day excursion — snow play in winter, yak rides, sledging, Himalayan Nature Park, and sweeping valley views from India\'s highest point road.', image: 'https://picsum.photos/seed/kufri/800/600', alt: 'Kufri snow adventure park yak ride Shimla Himachal', seasonal: false },
    { id: 'jakhu', title: 'Jakhu Temple & Forest Trek', description: 'The highest point in Shimla at 2,455m. Ancient Hanuman temple, dense rhododendron forest, resident langurs, and panoramic Himalayan views at the summit.', image: 'https://picsum.photos/seed/jakhu/800/600', alt: 'Jakhu temple forest trek Shimla highest point', seasonal: false },
    { id: 'naldehra', title: 'Naldehra Golf & Tattapani Hot Springs', description: 'India\'s oldest golf course set in a cedar forest. Combine with Tattapani for natural hot spring baths by the Sutlej river — a perfect relaxation day.', image: 'https://picsum.photos/seed/naldehra/800/600', alt: 'Naldehra golf course cedar forest Shimla Tattapani hot springs', seasonal: false },
    { id: 'snow-season', title: 'Shimla in Snow — Dec to Feb', description: 'Mall Road blanketed in snow, Kufri fully frozen, the toy train crawling through white hills. Shimla\'s most magical season — and most popular, so book 60+ days early.', image: 'https://picsum.photos/seed/shimla-snow/800/600', alt: 'Shimla snow winter Mall Road white December January', seasonal: true, seasonMonths: [12, 1, 2] },
  ] as Experience[],
  packages: [
    {
      id: 'shimla-classic',
      name: 'Shimla Classic',
      duration: '4 Nights / 5 Days',
      idealFor: 'First-time visitors, Couples',
      highlights: ['Shimla 3N', 'Kufri day', 'Mall Road + Toy train'],
      price: 'From ₹[TBD] per person',
      image: 'https://picsum.photos/seed/shimla-pkg1/800/600',
      alt: 'Shimla classic tour package Mall Road Kufri',
      whatsappMessage: 'Hi Outbound Travelers, I\'d like to know more about the Shimla Classic 4N/5D package. Please share details and customization options.',
      seasonal: false,
    },
    {
      id: 'shimla-family',
      name: 'Shimla Family Delight',
      duration: '5 Nights / 6 Days',
      idealFor: 'Families with kids, Multi-gen travel',
      highlights: ['Shimla 3N', 'Kufri 1N', 'Toy train ride', 'Ice Skating Rink'],
      price: 'From ₹[TBD] per person',
      image: 'https://picsum.photos/seed/shimla-pkg2/800/600',
      alt: 'Shimla family delight package kids ice skating toy train',
      whatsappMessage: 'Hi Outbound Travelers, I\'d like to know more about the Shimla Family Delight 5N/6D package. Please share details and customization options.',
      seasonal: false,
    },
    {
      id: 'shimla-honeymoon',
      name: 'Shimla Honeymoon Special',
      duration: '5 Nights / 6 Days',
      idealFor: 'Newly-married couples, Anniversary trips',
      highlights: ['Heritage hotel stay', 'Private valley view room', 'Romantic dinner', 'Toy train first class'],
      price: 'From ₹[TBD] per couple',
      image: 'https://picsum.photos/seed/shimla-pkg3/800/600',
      alt: 'Shimla honeymoon special heritage hotel valley view',
      whatsappMessage: 'Hi Outbound Travelers, I\'d like to know more about the Shimla Honeymoon Special 5N/6D package. Please share details and customization options.',
      seasonal: false,
    },
    {
      id: 'shimla-manali',
      name: 'Shimla + Manali Combo',
      duration: '7 Nights / 8 Days',
      idealFor: 'Adventure seekers, Friend groups',
      highlights: ['Shimla 3N', 'Manali 3N', 'Rohtang Pass', 'Solang Valley'],
      price: 'From ₹[TBD] per person',
      image: 'https://picsum.photos/seed/shimla-pkg4/800/600',
      alt: 'Shimla Manali combo tour package Rohtang Pass',
      whatsappMessage: 'Hi Outbound Travelers, I\'d like to know more about the Shimla + Manali Combo 7N/8D. Please share details and customization options.',
      seasonal: false,
    },
    {
      id: 'shimla-snow',
      name: 'Shimla Snow Special',
      duration: '4 Nights / 5 Days',
      idealFor: 'Snow lovers, Families, Couples',
      highlights: ['Snow play Kufri', 'Mall Road in snow', 'Toy train winter ride', 'Bonfire evenings'],
      price: 'From ₹[TBD] per person',
      image: 'https://picsum.photos/seed/shimla-pkg5/800/600',
      alt: 'Shimla snow special winter package December January',
      whatsappMessage: 'Hi Outbound Travelers, I\'d like to know more about the Shimla Snow Special 4N/5D. Please share details and customization options.',
      seasonal: true,
      seasonMonths: [12, 1, 2],
    },
  ] as Package[],
  itinerary: [
    { day: 1, title: 'Arrive Shimla — Mall Road Evening', description: 'Arrive by toy train from Kalka or by road from Chandigarh/Delhi. Check-in. Evening stroll on Mall Road, Christ Church, The Ridge. Dinner at a local restaurant.', highlights: ['Arrival by toy train or road', 'Mall Road walk', 'The Ridge evening'], stay: 'Shimla' },
    { day: 2, title: 'Shimla Sightseeing — Jakhu & Old Town', description: 'Morning ropeway or trek to Jakhu Temple. Afternoon: Viceregal Lodge (now IIAS), Annandale ground, Old Town bazaar. Evening free on Mall Road.', highlights: ['Jakhu temple', 'Viceregal Lodge', 'Old Town bazaar'], stay: 'Shimla' },
    { day: 3, title: 'Kufri & Chail Day Excursion', description: 'Full day to Kufri — snow play / Himalayan Nature Park / yak rides. Continue to Chail for the highest cricket ground in the world and Chail Palace. Return to Shimla.', highlights: ['Kufri snow/adventure', 'Chail Palace', 'Highest cricket ground'], stay: 'Shimla' },
    { day: 4, title: 'Naldehra, Tattapani & Leisure', description: 'Morning drive to Naldehra golf course cedar forest. Afternoon at Tattapani hot springs on Sutlej riverbank. Return to Shimla. Evening at leisure.', highlights: ['Naldehra golf forest', 'Tattapani hot springs', 'Sutlej riverbank'], stay: 'Shimla' },
    { day: 5, title: 'Fagu, Mashobra & Apple Orchards', description: 'Scenic drive to Fagu viewpoint and Mashobra orchards. Apple and cherry orchards in season (May–July). Wildflower Hall area. Return for last evening in Shimla.', highlights: ['Fagu viewpoint', 'Mashobra orchards', 'Apple picking in season'], stay: 'Shimla' },
    { day: 6, title: 'Departure', description: 'Breakfast and checkout. Transfer to Kalka (toy train) or Chandigarh/Delhi (road).', highlights: ['Last Mall Road walk', 'Hotel checkout', 'Transfer to Kalka/Chandigarh'], stay: 'Departure' },
  ] as ItineraryDay[],
  hotelTiers: [
    { tier: '3★ Comfort', description: 'Clean mid-range hotels with valley views, room heaters, and warm hospitality. Good for families on a budget.', price: 'From ₹[TBD] per night' },
    { tier: '4★ Premium', description: 'Premium hotels with panoramic mountain views, multi-cuisine restaurants, spa, and family rooms.', price: 'From ₹[TBD] per night' },
    { tier: '5★ Luxury', description: 'Top-tier Shimla properties — Wildflower Hall, Oberoi Cecil — with heritage architecture and world-class service.', price: 'From ₹[TBD] per night' },
    { tier: 'Heritage Property', description: 'Colonial-era bungalows and raja-era properties converted to boutique hotels — unique Shimla character, personal service.', price: 'From ₹[TBD] per night' },
  ] as HotelTier[],
  months: [
    { month: 'Jan', rating: 'best', note: 'Peak snow season — Mall Road and Kufri white.' },
    { month: 'Feb', rating: 'best', note: 'Snow still heavy, most romantic month.' },
    { month: 'Mar', rating: 'good', note: 'Snow melting, spring beginning.' },
    { month: 'Apr', rating: 'good', note: 'Pleasant, apple blossoms, rhododendrons.' },
    { month: 'May', rating: 'best', note: 'Peak season — cool escape from plains heat.' },
    { month: 'Jun', rating: 'best', note: 'School holiday peak, book early.' },
    { month: 'Jul', rating: 'okay', note: 'Monsoon season, misty but green.' },
    { month: 'Aug', rating: 'okay', note: 'Heavy rain, some landslide risk on roads.' },
    { month: 'Sep', rating: 'good', note: 'Post-monsoon clear skies, apple harvest.' },
    { month: 'Oct', rating: 'best', note: 'Apple harvest, golden forests, crisp air.' },
    { month: 'Nov', rating: 'good', note: 'Quiet, cold, first snow possible.' },
    { month: 'Dec', rating: 'best', note: 'Christmas in Shimla — festive and snowy.' },
  ] as MonthRating[],
  seasons: [
    { id: 'winter', label: 'Snow Winter', months: 'Dec–Feb', description: 'Shimla\'s most magical season. Mall Road in snow, Kufri fully white, toy train in winter. Book 60+ days early.', image: 'https://picsum.photos/seed/shimla-winter/800/600' },
    { id: 'spring', label: 'Apple Blossom Spring', months: 'Mar–Apr', description: 'Orchards bloom pink and white. Rhododendrons everywhere. Pleasant 10–20°C days.', image: 'https://picsum.photos/seed/shimla-spring/800/600' },
    { id: 'summer', label: 'Cool Summer Escape', months: 'May–Jun', description: 'When the plains hit 45°C, Shimla is 20°C. Most popular family season — book early.', image: 'https://picsum.photos/seed/shimla-summer/800/600' },
    { id: 'autumn', label: 'Apple Harvest Autumn', months: 'Sep–Oct', description: 'Red apples on every branch, golden forests, crisp mountain air. Underrated season.', image: 'https://picsum.photos/seed/shimla-autumn/800/600' },
  ] as Season[],
  process: [
    { step: 1, title: 'Share your dates', description: 'WhatsApp or form — tell us your travel month, group size, departure city, and whether you want the toy train.' },
    { step: 2, title: 'Get a custom itinerary', description: 'A Shimla specialist sends your day-wise plan with toy train and hotel options within 2 hours.' },
    { step: 3, title: 'Refine until it\'s right', description: 'Swap hotels, add Manali extension, include more snow activities. We iterate till it\'s perfect.' },
    { step: 4, title: 'Travel with full support', description: 'One team from your home airport to your Shimla hotel and back. Consultant reachable throughout.' },
  ] as ProcessStep[],
  inclusions: [
    'Accommodation per chosen tier',
    'Daily breakfast and meals per package',
    'Airport/station pickup and drop (Chandigarh or Kalka)',
    'All transfers in comfortable private vehicle',
    'Toy train booking assistance (Kalka–Shimla segment)',
    'English-speaking driver-guide',
    'All applicable tolls and parking',
    'GST on services',
  ],
  exclusions: [
    'Flights or trains to Chandigarh/Delhi (can be booked on request)',
    'Toy train ticket cost (booked at actuals)',
    'Kufri snow activity tickets (yak ride, sledge, snow scooter)',
    'Personal expenses, tips, room heater charges',
    'Travel insurance (recommended)',
    'Anything not explicitly in inclusions',
  ],
  gallery: [
    { image: 'https://picsum.photos/seed/shimla-g1/800/600', alt: 'Shimla Mall Road colonial buildings snow winter' },
    { image: 'https://picsum.photos/seed/shimla-g2/800/600', alt: 'Kalka Shimla toy train UNESCO railway hills' },
    { image: 'https://picsum.photos/seed/shimla-g3/800/600', alt: 'Kufri snow adventure park yak ride Shimla' },
    { image: 'https://picsum.photos/seed/shimla-g4/800/600', alt: 'Jakhu temple Hanuman forest trek Shimla' },
    { image: 'https://picsum.photos/seed/shimla-g5/800/600', alt: 'Christ Church Shimla colonial architecture Ridge' },
    { image: 'https://picsum.photos/seed/shimla-g6/800/600', alt: 'Shimla valley view snow Himalayan mountains' },
    { image: 'https://picsum.photos/seed/shimla-g7/800/600', alt: 'Apple orchard Mashobra Shimla Himachal Pradesh' },
    { image: 'https://picsum.photos/seed/shimla-g8/800/600', alt: 'Tattapani hot springs Sutlej river Shimla' },
    { image: 'https://picsum.photos/seed/shimla-g9/800/600', alt: 'Naldehra golf course cedar forest Shimla' },
    { image: 'https://picsum.photos/seed/shimla-g10/800/600', alt: 'Shimla family kids snow play Kufri winter' },
    { image: 'https://picsum.photos/seed/shimla-g11/800/600', alt: 'Heritage hotel Shimla colonial bungalow valley view' },
    { image: 'https://picsum.photos/seed/shimla-g12/800/600', alt: 'Chail Palace highest cricket ground Himachal' },
  ],
  testimonials: [
    { name: 'Rajan Family', city: 'Chennai', tripType: 'Family', quote: 'Shimla with three generations — grandparents, parents, kids. The toy train was the highlight for everyone. Outbound Travelers got the pace exactly right — no rushing, no fatigue.', rating: 5, date: 'May 2026', photo: 'https://picsum.photos/seed/shimla-t1/100/100' },
    { name: 'Preethi & Vijay', city: 'Coimbatore', tripType: 'Honeymoon', quote: 'Snow, heritage hotel, candlelit dinner — Shimla was magical. The team booked us a first-class toy train compartment as a surprise. Perfect honeymoon.', rating: 5, date: 'January 2026', photo: 'https://picsum.photos/seed/shimla-t2/100/100' },
  ] as Testimonial[],
  faqs: [
    { q: 'What is the best time to visit Shimla?', a: 'Shimla is a year-round destination. December to February for snow. March to April for apple blossoms and spring. May to June for a cool summer escape. September to October for the apple harvest and golden forests. July–August is monsoon — lush but rainy.' },
    { q: 'How do I get to Shimla from South India?', a: 'Fly to Delhi or Chandigarh from Chennai, Bangalore, or Kochi. From Chandigarh it\'s a 3-hour drive or take the toy train from Kalka (5–6 hours, booking required). We arrange all connections.' },
    { q: 'Is the Kalka–Shimla toy train worth it?', a: 'Absolutely — it\'s a UNESCO World Heritage railway and one of India\'s most scenic train rides. 96km through 102 tunnels and 864 bridges. Book well in advance as it fills quickly, especially in peak season.' },
    { q: 'How many days are enough for Shimla?', a: '4–5 nights covers Mall Road, Kufri, Jakhu, Naldehra, and a toy train ride. 6–7 nights lets you add the Shimla + Manali extension.' },
    { q: 'What is the average cost of a Shimla tour from South India?', a: 'A 5N/6D 3-star package starts from ₹[TBD] per person including road transfers from Chandigarh but excluding flights. Snow season packages cost slightly more. Use the estimator above.' },
    { q: 'Can I see snow in Shimla?', a: 'Yes — December to February brings reliable snowfall on Mall Road and Kufri. Some years snow comes as early as November or as late as March. Kufri usually has snow when Mall Road doesn\'t. We monitor conditions and advise before your trip.' },
    { q: 'Is Shimla good for families with seniors?', a: 'Yes — Shimla is very accessible. Mall Road and the Ridge are flat walking areas. Ropeway to Jakhu removes the trek. Most sightseeing is short-drive based. We use comfortable vehicles and senior-friendly hotels.' },
    { q: 'What is Kufri and is it worth a visit?', a: 'Kufri is a hill station 13km from Shimla at 2,600m — higher and snowier than Shimla town. Yak rides, sledging, snow scooters, and Himalayan Nature Park. In summer it\'s a viewpoint and adventure park. Always worth the half-day.' },
    { q: 'What should I pack for Shimla?', a: 'Heavy woollens and thermals for winter, light woollens for spring/autumn, comfortable walking shoes for Mall Road year-round. Rain jacket for July–August. Sunscreen for summer — UV is stronger at altitude.' },
    { q: 'Is Shimla safe for families and kids?', a: 'Very safe. Well-developed infrastructure, good road access, reliable hospitals. Mall Road is pedestrian only. Kids love the toy train, snow play, and Jakhu monkey sightings.' },
    { q: 'Can I combine Shimla with Manali?', a: 'Yes — the Shimla–Manali combo is our most popular North India circuit. 7–8 nights covers both destinations comfortably. Road via Mandi is 5–6 hours. We include Rohtang Pass and Solang Valley in the Manali portion.' },
    { q: 'What is the temperature in Shimla in winter?', a: 'December to February: 0°C to 10°C during the day, -5°C to 0°C at night. Snow is frequent at this time. Pack thermal inners, heavy woollens, gloves, and waterproof boots.' },
  ] as FAQ[],
  relatedDestinations: [
    { name: 'Manali', image: 'https://picsum.photos/seed/manali-rel/400/300', href: '/manali' },
    { name: 'Kashmir', image: 'https://picsum.photos/seed/kashmir-rel/400/300', href: '/kashmir' },
    { name: 'Ladakh', image: 'https://picsum.photos/seed/ladakh-rel/400/300', href: '/ladakh' },
    { name: 'Sikkim', image: 'https://picsum.photos/seed/sikkim-rel/400/300', href: '/sikkim' },
  ] as RelatedDestination[],
  whatsapp: {
    number: '919876543210',
    heroMessage: 'Hi Outbound Travelers, I\'m interested in a Shimla tour package. Please share itinerary options and a quote.',
    stickyMessage: 'Hi Outbound Travelers, I\'m planning a Shimla trip. Can someone help me plan and quote?',
    floaterMessage: 'Hi Outbound Travelers, I\'m interested in a Shimla tour package. Please share itinerary options and a quote.',
    finalCtaMessage: 'Hi Outbound Travelers, I\'m ready to plan my Shimla trip. Please send me your best itinerary and quote.',
    postFormMessage: 'Hi Outbound Travelers, I just submitted my Shimla enquiry. Travel month: {month}, {travelers} travelers from {city}, trip type: {tripType}. Looking forward to the itinerary and quote.',
  } as WhatsAppConfig,
  leadForm: {
    title: 'Get your Shimla quote',
    subtitle: 'Tell us your travel dates and group — we\'ll come back within 2 hours.',
    submitButtonText: 'Get my Shimla quote',
    successMessage: 'Got it! Your Shimla specialist will WhatsApp you within 2 hours. Meanwhile, save our number: +91-98765-43210.',
    destinationId: 'shimla',
    destinationName: 'Shimla',
  } as LeadFormConfig,
  familyHighlights: [
    { icon: 'train', title: 'Toy Train Adventure', description: 'Kids and adults equally mesmerized by the UNESCO heritage Kalka–Shimla railway winding through tunnels and hills.' },
    { icon: 'snow', title: 'Snow Play at Kufri', description: 'Yak rides, sledging, snowball fights — Kufri delivers the snow experience safely and memorably for all ages.' },
    { icon: 'ice', title: 'Ice Skating Rink', description: 'Asia\'s only natural open-air ice skating rink (winter only) — a unique Shimla experience for the whole family.' },
    { icon: 'pace', title: 'Senior-Friendly Pace', description: 'Ropeway to Jakhu, flat Mall Road walks, comfortable vehicles — every activity is accessible for older family members.' },
  ],
  seoContent: {
    h2: 'Planning Your Shimla Trip with Outbound Travelers',
    sections: [
      {
        h3: 'Which Shimla itinerary is right for you?',
        body: 'The classic Shimla tour package covers Mall Road, Kufri, Jakhu, and Naldehra in four to five nights — the complete Shimla experience at a comfortable pace. Families add a day at Chail for the highest cricket ground. The Shimla–Manali combo extends to seven nights and adds Rohtang Pass and Solang Valley. Couples choose heritage hotel packages with the toy train in first class.',
      },
      {
        h3: 'Shimla from South India — flights, connections, what to plan around',
        body: 'Fly to Delhi or Chandigarh from Chennai, Bangalore, Kochi, or Hyderabad. From Chandigarh it is a three-hour comfortable road transfer to Shimla, or take the Kalka–Shimla toy train for the scenic route — five to six hours through the hills. We arrange all connections including station or airport pickup in Chandigarh and booking the toy train tickets well in advance.',
      },
      {
        h3: 'Customizing your Shimla package',
        body: 'Families add the ice skating rink in winter and apple orchard visits in autumn. Honeymooners upgrade to heritage properties with valley-view rooms and candlelit dinner arrangements. Adventure groups extend to Manali and add Rohtang or Spiti Valley. Seniors get ropeway access instead of treks and comfortable vehicles throughout. Every package starts from your group\'s needs.',
      },
      {
        h3: 'Why book Shimla with Outbound Travelers',
        body: 'We specialize in South Indian families visiting North Indian hill stations — a very specific kind of trip that most North India operators handle generically. We understand the food preferences, the pace, the multi-generational family structure, and the importance of the toy train experience. Every hotel and transfer on our Shimla list is personally vetted.',
      },
    ],
  },
}
