import type {
  TrustBadge, Package, ItineraryDay, HotelTier,
  MonthRating, Season, FAQ, Testimonial, RelatedDestination,
  Experience, WhatsAppConfig, ProcessStep, DestinationTheme, LeadFormConfig
} from '@/lib/shared/types'

export const ladakhData = {
  meta: {
    title: 'Ladakh Tour Packages — Customizable Adventure & Scenic Trips | Outbound Travelers',
    description: 'Plan your Ladakh trip with Outbound Travelers. Adventure, honeymoon & family packages with permits, hotels, transfers. Lightning-fast custom quotes.',
    canonical: 'https://www.outboundtravelers.com/ladakh',
    ogImage: 'https://picsum.photos/seed/ladakh-og/1200/630',
    h1: 'Ladakh Tour Packages — Journey to the Roof of the World',
  },
  theme: {
    accentColor: '#1F3A8A',
    accentSoft: '#E0E7FF',
    motif: 'prayer-flag',
  } as DestinationTheme,
  hero: {
    headline: 'Ladakh, Where the Sky Meets the Road',
    subheadline: 'Adventure, culture, and high-altitude landscapes — fully customized Ladakh trips for bikers, trekkers, families, and first-timers from South India.',
    primaryCta: 'Get my Ladakh quote',
    secondaryCta: 'Or talk to a travel expert on WhatsApp',
    desktopImage: 'https://picsum.photos/seed/ladakh-hero-d/1920/1080',
    mobileImage: 'https://picsum.photos/seed/ladakh-hero-m/800/1200',
    imageAlt: 'Pangong Lake blue waters with Himalayan mountains Ladakh',
  },
  trustBadges: [
    { icon: 'trips', label: '2,500+ trips delivered' },
    { icon: 'custom', label: '100% customizable' },
    { icon: 'verified', label: 'Permit handling' },
    { icon: 'support', label: '24/7 on-trip support' },
    { icon: 'quote', label: 'Lightning quotes' },
    { icon: 'member', label: 'TAFI/IATA member' },
  ] as TrustBadge[],
  quickSummary: {
    duration: '6–8 nights ideal',
    bestSeason: 'June–September (Road Open)',
    startingFrom: 'From ₹[TBD] per person',
    tripTypes: 'Adventure · Bike · Trek · Family · Honeymoon',
  },
  whyVisit: [
    {
      icon: 'specialist',
      title: 'Altitude-ready itineraries',
      description: 'Every Ladakh itinerary includes proper acclimatization days built in — we never rush the altitude. Your safety is the first plan item.',
    },
    {
      icon: 'verified',
      title: 'Permits, logistics, sorted',
      description: 'Inner Line Permits, Pangong access, bike rental, oxygen support — all arranged before you land in Leh. Zero paperwork for you.',
    },
    {
      icon: 'southindia',
      title: 'South India to Leh, planned right',
      description: 'Flights from Chennai, Bangalore, Kochi with correct acclimatization scheduling. We know how South Indian bodies respond to altitude.',
    },
  ],
  experiences: [
    { id: 'pangong', title: 'Pangong Lake — Blue to Turquoise', description: 'The lake that changes colour across its 134km length. Camp on the north bank at 4,350m. Sunrise here is one of the most surreal moments in Indian travel.', image: 'https://picsum.photos/seed/pangong/800/600', alt: 'Pangong Lake blue waters Himalayan mountains Ladakh', seasonal: false },
    { id: 'nubra', title: 'Nubra Valley & Khardung La', description: 'Cross the world\'s highest motorable road at 5,359m. Drop into the Nubra Valley for double-humped Bactrian camel rides on the sand dunes of Hunder.', image: 'https://picsum.photos/seed/nubra/800/600', alt: 'Nubra Valley Bactrian camel sand dunes Hunder Ladakh', seasonal: false },
    { id: 'leh-palace', title: 'Leh Palace & Shanti Stupa', description: 'Nine-storey palace overlooking old Leh town. Walk the old market. Shanti Stupa at sunset — 360-degree views of the Indus Valley and Stok Kangri.', image: 'https://picsum.photos/seed/leh-palace/800/600', alt: 'Leh Palace historic monument Ladakh mountains', seasonal: false },
    { id: 'magnetic-hill', title: 'Magnetic Hill & Sangam Point', description: 'The optical illusion road that appears to pull vehicles uphill. Then Sangam — the confluence of Indus and Zanskar rivers in contrasting brown and green.', image: 'https://picsum.photos/seed/magnetic-hill/800/600', alt: 'Sangam Indus Zanskar river confluence Leh Ladakh', seasonal: false },
    { id: 'monasteries', title: 'Hemis, Thiksey & Diskit Monasteries', description: 'Hemis — Ladakh\'s largest monastery, annual festival in June/July. Thiksey — modelled on Potala Palace. Diskit — the giant Maitreya Buddha in Nubra Valley.', image: 'https://picsum.photos/seed/hemis/800/600', alt: 'Hemis monastery Ladakh Buddhist festival', seasonal: false },
    { id: 'chadar-trek', title: 'Chadar Trek — Frozen River Walk', description: 'January to February only — walk the frozen Zanskar River gorge, one of the most extreme and beautiful treks in the world.', image: 'https://picsum.photos/seed/chadar/800/600', alt: 'Chadar trek frozen Zanskar river winter Ladakh', seasonal: true, seasonMonths: [1, 2] },
  ] as Experience[],
  packages: [
    {
      id: 'ladakh-classic',
      name: 'Ladakh Classic',
      duration: '6 Nights / 7 Days',
      idealFor: 'First-time visitors, Families',
      highlights: ['Leh acclimatization 2N', 'Nubra Valley 2N', 'Pangong Lake 1N'],
      price: 'From ₹[TBD] per person',
      image: 'https://picsum.photos/seed/ladakh-pkg1/800/600',
      alt: 'Ladakh classic tour package Leh Nubra Pangong',
      whatsappMessage: 'Hi Outbound Travelers, I\'d like to know more about the Ladakh Classic 6N/7D package. Please share details and customization options.',
      seasonal: false,
    },
    {
      id: 'ladakh-bike',
      name: 'Ladakh Bike Expedition',
      duration: '8 Nights / 9 Days',
      idealFor: 'Bikers, Adventure seekers',
      highlights: ['Manali–Leh highway', 'Khardung La pass', 'Pangong camp'],
      price: 'From ₹[TBD] per person',
      image: 'https://picsum.photos/seed/ladakh-pkg2/800/600',
      alt: 'Ladakh bike expedition Manali Leh highway mountain pass',
      whatsappMessage: 'Hi Outbound Travelers, I\'d like to know more about the Ladakh Bike Expedition 8N/9D. Please share details and customization options.',
      seasonal: true,
      seasonMonths: [6, 7, 8, 9],
    },
    {
      id: 'ladakh-trek',
      name: 'Markha Valley Trek',
      duration: '7 Nights / 8 Days',
      idealFor: 'Trekkers, Adventure seekers',
      highlights: ['Markha Valley trail', 'Kongmaru La 5,150m', 'Village homestays'],
      price: 'From ₹[TBD] per person',
      image: 'https://picsum.photos/seed/ladakh-pkg3/800/600',
      alt: 'Markha Valley trek Ladakh Himalayan trail',
      whatsappMessage: 'Hi Outbound Travelers, I\'d like to know more about the Markha Valley Trek 7N/8D. Please share details and customization options.',
      seasonal: true,
      seasonMonths: [6, 7, 8, 9],
    },
    {
      id: 'ladakh-luxury',
      name: 'Ladakh Luxury Camp',
      duration: '7 Nights / 8 Days',
      idealFor: 'Luxury travelers, Couples',
      highlights: ['Glamping at Pangong', 'Private jeep circuit', 'Monastery private tour'],
      price: 'From ₹[TBD] per person',
      image: 'https://picsum.photos/seed/ladakh-pkg4/800/600',
      alt: 'Ladakh luxury glamping camp Pangong Lake',
      whatsappMessage: 'Hi Outbound Travelers, I\'d like to know more about the Ladakh Luxury Camp 7N/8D. Please share details and customization options.',
      seasonal: false,
    },
    {
      id: 'ladakh-winter',
      name: 'Chadar Trek & Snow Ladakh',
      duration: '7 Nights / 8 Days',
      idealFor: 'Extreme trekkers, Winter seekers',
      highlights: ['Chadar frozen river trek', 'Leh in snow', 'Thiksey monastery winter'],
      price: 'From ₹[TBD] per person',
      image: 'https://picsum.photos/seed/ladakh-pkg5/800/600',
      alt: 'Chadar trek winter Ladakh frozen river',
      whatsappMessage: 'Hi Outbound Travelers, I\'d like to know more about the Chadar Trek & Snow Ladakh 7N/8D. Please share details and customization options.',
      seasonal: true,
      seasonMonths: [1, 2],
    },
  ] as Package[],
  itinerary: [
    { day: 1, title: 'Arrive Leh — Acclimatization Day 1', description: 'Flight to Leh (3,500m). Check-in and complete rest. No sightseeing today — altitude acclimatization is non-negotiable. Light walk in the evening only.', highlights: ['Flight arrival Leh', 'Hotel check-in', 'Rest and hydrate'], stay: 'Leh' },
    { day: 2, title: 'Leh Local — Acclimatization Day 2', description: 'Short visits to Shanti Stupa, Leh Palace, and the old market. Light walking only. Evening briefing on the journey ahead.', highlights: ['Shanti Stupa', 'Leh Palace walk', 'Old market'], stay: 'Leh' },
    { day: 3, title: 'Leh to Nubra Valley via Khardung La', description: 'Cross Khardung La (5,359m). Descend into Nubra. Afternoon camel ride on Hunder sand dunes. Check-in to camp or guesthouse.', highlights: ['Khardung La top', 'Nubra Valley drive', 'Camel ride Hunder'], stay: 'Nubra' },
    { day: 4, title: 'Nubra Valley — Diskit Monastery & Dunes', description: 'Diskit Monastery and the giant Maitreya Buddha. Afternoon free at the sand dunes. Sunset over the Shyok River valley.', highlights: ['Diskit monastery', 'Maitreya Buddha', 'Shyok River sunset'], stay: 'Nubra' },
    { day: 5, title: 'Nubra to Pangong Lake', description: 'Long scenic drive via the remote Shyok valley road to Pangong. Arrive by afternoon. First sight of the electric blue lake at 4,350m.', highlights: ['Shyok valley road', 'Pangong first view', 'Lakeside camp'], stay: 'Pangong' },
    { day: 6, title: 'Pangong Lake — Sunrise & Return to Leh', description: 'Pre-dawn lakeside sunrise — the lake shifts from deep blue to turquoise as light changes. Drive back to Leh via Chang La (5,360m).', highlights: ['Pangong sunrise', 'Chang La pass', 'Return to Leh'], stay: 'Leh' },
    { day: 7, title: 'Leh Monasteries — Hemis & Thiksey', description: 'Full day monastery circuit — Hemis (Ladakh\'s largest), Thiksey (resembles Potala), Rancho School visit optional. Sangam river confluence.', highlights: ['Hemis monastery', 'Thiksey monastery', 'Sangam confluence'], stay: 'Leh' },
    { day: 8, title: 'Departure from Leh', description: 'Early morning flight back. Airport transfer. End of Ladakh journey.', highlights: ['Packing and checkout', 'Airport transfer', 'Departure'], stay: 'Departure' },
  ] as ItineraryDay[],
  hotelTiers: [
    { tier: 'Guesthouse', description: 'Local Ladakhi guesthouses with home-cooked meals, warm blankets, and genuine hospitality. The most authentic Ladakh experience.', price: 'From ₹[TBD] per night' },
    { tier: '3★ Comfort', description: 'Comfortable hotels in Leh with attached bathrooms, room heaters, and reliable breakfast.', price: 'From ₹[TBD] per night' },
    { tier: '4★ Premium', description: 'Premium properties with good amenities, mountain views, and warm common areas.', price: 'From ₹[TBD] per night' },
    { tier: 'Luxury Camp', description: 'Glamping tents at Pangong and Nubra — heated interiors, attached washrooms, stargazing decks, and gourmet meals under the Milky Way.', price: 'From ₹[TBD] per night' },
  ] as HotelTier[],
  months: [
    { month: 'Jan', rating: 'avoid', note: 'Roads closed, extreme cold, Chadar trek only.' },
    { month: 'Feb', rating: 'avoid', note: 'Chadar trek season, otherwise inaccessible.' },
    { month: 'Mar', rating: 'avoid', note: 'Roads still closed, not recommended.' },
    { month: 'Apr', rating: 'okay', note: 'Roads opening, early season, cold.' },
    { month: 'May', rating: 'good', note: 'Good weather, roads mostly open.' },
    { month: 'Jun', rating: 'best', note: 'Peak season begins, all roads open.' },
    { month: 'Jul', rating: 'best', note: 'Best weather, full Ladakh circuit possible.' },
    { month: 'Aug', rating: 'best', note: 'Peak season, book early.' },
    { month: 'Sep', rating: 'best', note: 'Clear skies, slightly cooler, fewer crowds.' },
    { month: 'Oct', rating: 'good', note: 'Roads closing soon, last call for Pangong.' },
    { month: 'Nov', rating: 'avoid', note: 'Roads closing, not recommended.' },
    { month: 'Dec', rating: 'avoid', note: 'Closed season except Chadar prep.' },
  ] as MonthRating[],
  seasons: [
    { id: 'summer', label: 'Peak Summer', months: 'Jun–Sep', description: 'All roads open, full circuit possible. Best weather for Pangong, Nubra, and trekking.', image: 'https://picsum.photos/seed/ladakh-summer/800/600' },
    { id: 'spring', label: 'Early Season', months: 'Apr–May', description: 'Roads opening, fewer crowds, cooler temperatures. Good for budget travel.', image: 'https://picsum.photos/seed/ladakh-spring/800/600' },
    { id: 'autumn', label: 'Late Season', months: 'Oct', description: 'Last call before roads close. Clear skies, golden landscapes, great photography.', image: 'https://picsum.photos/seed/ladakh-autumn/800/600' },
    { id: 'winter', label: 'Chadar Season', months: 'Jan–Feb', description: 'Only for Chadar frozen river trek. Extreme cold, -20°C. Expert-guided only.', image: 'https://picsum.photos/seed/ladakh-winter/800/600' },
  ] as Season[],
  process: [
    { step: 1, title: 'Share your dates', description: 'WhatsApp or form — tell us your travel window, group size, and whether you want bikes, treks, or a jeep circuit.' },
    { step: 2, title: 'Get a custom itinerary', description: 'A Ladakh specialist builds your day-wise plan with correct acclimatization and sends a transparent quote within 2 hours.' },
    { step: 3, title: 'We handle all permits', description: 'Inner Line Permits, Pangong access permits, Nubra permits — all arranged by us before you travel.' },
    { step: 4, title: 'Travel with full support', description: 'Satellite-backed emergency contacts, oxygen support arrangement, and a consultant reachable throughout your trip.' },
  ] as ProcessStep[],
  inclusions: [
    'Accommodation per chosen tier',
    'All meals as per package (breakfast + dinner standard)',
    'Leh airport pickup and drop',
    'All transfers in private SUV or jeep (altitude-capable vehicles)',
    'Inner Line Permits for Nubra, Pangong, and restricted areas',
    'English-speaking driver-guide with altitude experience',
    'Oxygen cylinder on vehicle throughout trip',
    'All applicable tolls and parking',
    'GST on services',
  ],
  exclusions: [
    'Flights to Leh (can be booked on request)',
    'Bike rental for bike expedition packages (available on request)',
    'Camel ride, ATV, rafting tickets (priced live)',
    'Personal expenses, tips, room heater charges at some guesthouses',
    'Travel insurance (strongly recommended at altitude)',
    'Anything not explicitly in inclusions',
  ],
  gallery: [
    { image: 'https://picsum.photos/seed/ladakh-g1/800/600', alt: 'Pangong Lake blue water Himalayan mountains Ladakh' },
    { image: 'https://picsum.photos/seed/ladakh-g2/800/600', alt: 'Khardung La highest motorable road pass Ladakh' },
    { image: 'https://picsum.photos/seed/ladakh-g3/800/600', alt: 'Nubra Valley Bactrian camel Hunder sand dunes' },
    { image: 'https://picsum.photos/seed/ladakh-g4/800/600', alt: 'Thiksey monastery Potala resemblance Ladakh' },
    { image: 'https://picsum.photos/seed/ladakh-g5/800/600', alt: 'Leh Palace historic nine storey palace Ladakh' },
    { image: 'https://picsum.photos/seed/ladakh-g6/800/600', alt: 'Pangong Lake sunrise turquoise blue Ladakh' },
    { image: 'https://picsum.photos/seed/ladakh-g7/800/600', alt: 'Chadar trek frozen Zanskar river winter Ladakh' },
    { image: 'https://picsum.photos/seed/ladakh-g8/800/600', alt: 'Hemis monastery Buddhist festival Ladakh' },
    { image: 'https://picsum.photos/seed/ladakh-g9/800/600', alt: 'Shanti Stupa Leh valley view sunset Ladakh' },
    { image: 'https://picsum.photos/seed/ladakh-g10/800/600', alt: 'Markha Valley trek trail Himalayan mountains' },
    { image: 'https://picsum.photos/seed/ladakh-g11/800/600', alt: 'Luxury glamping tent Pangong Lake Ladakh' },
    { image: 'https://picsum.photos/seed/ladakh-g12/800/600', alt: 'Manali Leh highway mountain road Ladakh bike' },
  ],
  testimonials: [
    { name: 'Aravind & Friends', city: 'Bangalore', tripType: 'Adventure', quote: 'Six of us on Royal Enfields from Manali to Leh. Outbound Travelers handled everything — permits, fuel stops, emergency contacts, accommodation. The bike trip of our lives.', rating: 5, date: 'July 2026', photo: 'https://picsum.photos/seed/ladakh-t1/100/100' },
    { name: 'Meena Family', city: 'Chennai', tripType: 'Family', quote: 'We were nervous about altitude with our 65-year-old mother. The team built in two full acclimatization days and had oxygen ready. She loved Pangong sunrise more than anyone.', rating: 5, date: 'August 2026', photo: 'https://picsum.photos/seed/ladakh-t2/100/100' },
  ] as Testimonial[],
  faqs: [
    { q: 'What is the best time to visit Ladakh?', a: 'June to September is the ideal window — all roads open, Pangong and Nubra accessible, weather stable. July and August are peak. May and October are shoulder months. January–February for Chadar trek only.' },
    { q: 'How many days are enough for a Ladakh trip?', a: '7–8 nights is the sweet spot. 6 nights covers Leh, Nubra, and Pangong with proper acclimatization. 8+ nights adds the Markha Valley or a Zanskar extension.' },
    { q: 'Is altitude sickness a concern for South Indian travelers?', a: 'Yes — the jump from sea level to 3,500m in Leh on a direct flight is significant. We always build 2 full acclimatization days into every itinerary. We carry oxygen on every vehicle and brief you on symptoms before travel.' },
    { q: 'Do we need Inner Line Permits for Ladakh?', a: 'Yes — Nubra Valley, Pangong Lake, Tso Moriri, and several other areas require Inner Line Permits. We handle all permit applications before your trip. Zero paperwork for you.' },
    { q: 'What is the road condition on the Manali–Leh highway?', a: 'The Manali–Leh highway opens around late May or early June depending on snowmelt. It is a two-day drive through high mountain passes including Rohtang and Baralacha La. We recommend flying into Leh for most travelers.' },
    { q: 'Can families with seniors do Ladakh?', a: 'Yes with proper planning. Two acclimatization days are non-negotiable. We use comfortable SUVs, recommend 3-4 star hotels over campsites for seniors, keep daily drives under 5 hours, and carry oxygen throughout.' },
    { q: 'What should I pack for Ladakh?', a: 'Warm layers even in summer (nights drop to 5–10°C in July), thermal inners, sun protection (UV is intense at altitude), waterproof jacket, trekking shoes, personal medication, and altitude sickness tablets. Full list shared post-booking.' },
    { q: 'Is Pangong Lake worth the trip?', a: 'Absolutely — the lake changes colour from deep blue to turquoise as you move along its length. The north bank camp sunrise is unlike anything in Indian travel. One night is the minimum; two is better.' },
    { q: 'Can I do a bike trip to Ladakh from South India?', a: 'Most riders fly to Manali or Delhi and start the ride from there. We arrange bike rental in Manali or Leh, permits, support vehicle, accommodation, and emergency contacts. The Manali–Leh route is 9 days including acclimatization.' },
    { q: 'What is the Chadar trek?', a: 'The Chadar trek is a January–February expedition along the frozen Zanskar River gorge. It is one of the most extreme and beautiful winter treks in the world. Temperature: -20°C to -30°C. Expert-guided only — we handle full logistics.' },
    { q: 'Can I get South Indian food in Ladakh?', a: 'Local food is mostly Ladakhi and North Indian. Most hotels serve Indian meals. South Indian food is limited — we can arrange specific meals at select Leh restaurants on request. We recommend embracing local cuisine — thukpa and momos are excellent.' },
    { q: 'Is Ladakh safe for solo female travelers?', a: 'Yes — Ladakh is one of the safest destinations in India for solo travelers including women. The local Buddhist culture is respectful and welcoming. We arrange trusted drivers and accommodation for solo travelers.' },
  ] as FAQ[],
  relatedDestinations: [
    { name: 'Kashmir', image: 'https://picsum.photos/seed/kashmir-rel/400/300', href: '/kashmir' },
    { name: 'Manali', image: 'https://picsum.photos/seed/manali-rel/400/300', href: '/manali' },
    { name: 'Sikkim', image: 'https://picsum.photos/seed/sikkim-rel/400/300', href: '/sikkim' },
    { name: 'Meghalaya', image: 'https://picsum.photos/seed/meghalaya-rel/400/300', href: '/meghalaya' },
  ] as RelatedDestination[],
  whatsapp: {
    number: '919876543210',
    heroMessage: 'Hi Outbound Travelers, I\'m interested in a Ladakh tour package. Please share itinerary options and a quote.',
    stickyMessage: 'Hi Outbound Travelers, I\'m planning a Ladakh trip. Can someone help me plan and quote?',
    floaterMessage: 'Hi Outbound Travelers, I\'m interested in a Ladakh tour package. Please share itinerary options and a quote.',
    finalCtaMessage: 'Hi Outbound Travelers, I\'m ready to plan my Ladakh trip. Please send me your best itinerary and quote.',
    postFormMessage: 'Hi Outbound Travelers, I just submitted my Ladakh enquiry. Travel month: {month}, {travelers} travelers from {city}, trip type: {tripType}. Looking forward to the itinerary and quote.',
  } as WhatsAppConfig,
  leadForm: {
    title: 'Get your Ladakh quote',
    subtitle: 'Tell us your travel window and what kind of Ladakh experience you want — we\'ll come back within 2 hours.',
    submitButtonText: 'Get my Ladakh quote',
    successMessage: 'Got it! Your Ladakh specialist will WhatsApp you within 2 hours. Meanwhile, save our number: +91-98765-43210.',
    destinationId: 'ladakh',
    destinationName: 'Ladakh',
  } as LeadFormConfig,
  altitudeWarning: {
    title: '⚠️ Important: Altitude & Acclimatization',
    points: [
      'Leh is at 3,500m — arrive by flight and rest completely on Day 1',
      'Pangong Lake is at 4,350m and Khardung La at 5,359m',
      'We build 2 mandatory acclimatization days into every itinerary',
      'Oxygen cylinder carried on every vehicle throughout your trip',
      'Consult your doctor if you have heart, lung, or blood pressure conditions',
      'Children under 5 and seniors above 70 require medical clearance',
    ],
  },
  seoContent: {
    h2: 'Planning Your Ladakh Trip with Outbound Travelers',
    sections: [
      {
        h3: 'Which Ladakh circuit is right for you?',
        body: 'The classic Ladakh tour package covers Leh, Nubra Valley, and Pangong Lake in six to seven nights — the three essential Ladakh experiences. Add Tso Moriri for a deeper circuit in eight nights. Bikers can ride the Manali–Leh highway in nine days including acclimatization. Trekkers choose the Markha Valley for a five-day moderate trail or the Stok Kangri summit for a serious high-altitude climb.',
      },
      {
        h3: 'Ladakh from South India — flights, acclimatization, what to plan around',
        body: 'Direct flights to Leh run from Delhi. From Chennai, Bangalore, and Kochi, connect via Delhi — total travel time five to six hours. We always schedule arrival in Leh in the morning to maximise rest time on Day 1. The altitude jump from sea level to 3,500m in under three hours is significant — our itineraries are built around this reality, not around packing in more sights.',
      },
      {
        h3: 'Customizing your Ladakh package',
        body: 'Adventure travelers build around the bike expedition, Chadar trek, or Markha Valley. Families focus on the jeep circuit — Nubra, Pangong, and monastery visits at a comfortable pace. Couples upgrade to luxury glamping at Pangong for a stargazing experience that rivals any resort. Every Ladakh tour package starts from your version of the trip, not from a fixed template.',
      },
      {
        h3: 'Why book Ladakh with Outbound Travelers',
        body: 'Our Ladakh specialists have planned hundreds of high-altitude trips. We carry oxygen on every vehicle — not as an upsell, but as standard. We handle all Inner Line Permits before you travel. And because we specialise in South Indian travelers, we understand the specific acclimatization challenges and food needs of travelers coming from sea-level cities.',
      },
    ],
  },
}
