import type {
  TrustBadge, Package, ItineraryDay, HotelTier,
  MonthRating, Season, FAQ, Testimonial, RelatedDestination,
  Experience, WhatsAppConfig, ProcessStep, DestinationTheme, LeadFormConfig
} from '@/lib/shared/types'

export const manaliData = {
  meta: {
    title: 'Manali Tour Packages — Adventure & Romantic Trips | Outbound Travelers',
    description: 'Plan your Manali trip with Outbound Travelers. Adventure, honeymoon & family packages with Rohtang Pass, Solang Valley, hotels and transfers. Lightning-fast quotes.',
    canonical: 'https://www.outboundtravelers.com/manali',
    ogImage: 'https://picsum.photos/seed/manali-og/1200/630',
    h1: 'Manali Tour Packages — Snow Peaks, River Valleys, and Open Roads',
  },
  theme: {
    accentColor: '#355C7D',
    accentSoft: '#DEE5EC',
    motif: 'snowflake-pine',
  } as DestinationTheme,
  hero: {
    variant: 'HeroCinematic',
    headline: 'Manali, Where Every Road Leads to Adventure',
    subheadline: 'Snow peaks, river valleys, Rohtang Pass, Solang Valley — adventure and romance in the Kullu Valley, planned end-to-end for South Indian travelers.',
    primaryCta: 'Get my Manali quote',
    secondaryCta: 'Or talk to a travel expert on WhatsApp',
    desktopImage: 'https://picsum.photos/seed/manali-hero-d/1920/1080',
    mobileImage: 'https://picsum.photos/seed/manali-hero-m/800/1200',
    imageAlt: 'Solang Valley snow slopes Manali Himachal Pradesh with cable car',
  },
  trustBadges: [
    { icon: 'trips', label: '2,500+ trips delivered' },
    { icon: 'custom', label: '100% customizable' },
    { icon: 'verified', label: 'Permit handling' },
    { icon: 'support', label: '24/7 on-trip support' },
    { icon: 'quote', label: 'Lightning quotes' },
    { icon: 'member', label: 'TAFI/IATA member' },
  ] as TrustBadge[],
  quickSummary: {
    duration: '5–7 nights ideal',
    bestSeason: 'Oct–Jun (Snow · Spring · Summer)',
    startingFrom: 'From ₹14,999 per person',
    tripTypes: 'Adventure · Honeymoon · Family · Bike',
  },
  whyVisit: [
    {
      icon: 'specialist',
      title: 'Adventure and romance, both',
      description: 'Manali works for thrill-seekers and honeymooners alike. We build itineraries that balance both — snow activities by day, cozy riverside stays by night.',
    },
    {
      icon: 'verified',
      title: 'Rohtang permits and logistics sorted',
      description: 'Rohtang Pass requires NGT permits — limited daily. We book permits in advance so your snow day is never cancelled by a full permit quota.',
    },
    {
      icon: 'southindia',
      title: 'South India to Manali, connected',
      description: 'Fly to Delhi or Chandigarh, then scenic road or Volvo bus to Manali. We arrange all connections including overnight Volvo from Delhi if preferred.',
    },
  ],
  experiences: [
    {
      id: 'rohtang',
      title: 'Rohtang Pass — Snow at 3,978m',
      description: 'Cross the Rohtang Pass for dramatic snow even in summer. The view from the top — glaciers, high-altitude desert, and the road to Lahaul — is unlike anything in the lower hills. NGT permit required — we book in advance.',
      image: 'https://picsum.photos/seed/rohtang/800/600',
      alt: 'Rohtang Pass snow mountains Manali Himachal Pradesh',
      seasonal: true,
      seasonMonths: [5, 6, 7, 8, 9, 10],
    },
    {
      id: 'solang',
      title: 'Solang Valley — Snow & Adventure Hub',
      description: 'Skiing, zorbing, paragliding, cable car, snow scooters — Solang Valley packs every adventure into one valley. Available year-round with different activities per season.',
      image: 'https://picsum.photos/seed/solang/800/600',
      alt: 'Solang Valley skiing cable car adventure Manali',
      seasonal: false,
    },
    {
      id: 'old-manali',
      title: 'Old Manali & Hadimba Temple',
      description: 'The ancient Hadimba Devi Temple set in a cedar forest — one of the most distinctive temples in North India. Old Manali village with its cafés, craft shops, and mountain character.',
      image: 'https://picsum.photos/seed/hadimba/800/600',
      alt: 'Hadimba temple cedar forest Old Manali Himachal Pradesh',
      seasonal: false,
    },
    {
      id: 'beas-river',
      title: 'Beas River — Rafting & Walks',
      description: 'White water rafting on the Beas between Pirdi and Jhiri. Or simply walk the riverside path through Vashisht village and the hot springs. The river is the heart of Manali.',
      image: 'https://picsum.photos/seed/beas-river/800/600',
      alt: 'Beas river white water rafting Manali Himachal Pradesh',
      seasonal: true,
      seasonMonths: [5, 6, 7, 8, 9],
    },
    {
      id: 'naggar-kullu',
      title: 'Naggar Castle & Kullu Valley',
      description: 'Medieval Naggar Castle overlooking the Kullu Valley. Stop at the Roerich Art Gallery. Drive through apple orchards and the Kullu Dussehra ground on the way up.',
      image: 'https://picsum.photos/seed/naggar/800/600',
      alt: 'Naggar Castle Kullu Valley medieval fort Himachal Pradesh',
      seasonal: false,
    },
    {
      id: 'spiti-extension',
      title: 'Spiti Valley Extension — 2 Extra Days',
      description: 'From Manali take the highway to Kaza via Kunzum Pass. Moonscape mountains, Key Monastery, Pin Valley. Manali to Spiti is among the most dramatic drives on earth.',
      image: 'https://picsum.photos/seed/spiti/800/600',
      alt: 'Spiti Valley Kaza Key monastery Himachal Pradesh extension',
      seasonal: true,
      seasonMonths: [6, 7, 8, 9],
    },
  ] as Experience[],
  packages: [
    {
      id: 'manali-classic',
      name: 'Manali Classic',
      duration: '5 Nights / 6 Days',
      idealFor: 'First-time visitors, Couples',
      highlights: ['Solang Valley', 'Rohtang Pass (seasonal)', 'Old Manali & Hadimba'],
      price: 'From ₹14,999 per person',
      image: 'https://picsum.photos/seed/manali-pkg1/800/600',
      alt: 'Manali classic tour package Solang Rohtang Hadimba',
      whatsappMessage: 'Hi Outbound Travelers, I\'d like to know more about the Manali Classic 5N/6D package. Please share details and customization options.',
      seasonal: false,
    },
    {
      id: 'manali-honeymoon',
      name: 'Manali Honeymoon Special',
      duration: '6 Nights / 7 Days',
      idealFor: 'Newly-married couples, Anniversary trips',
      highlights: ['Riverside cottage stay', 'Candlelit dinner', 'Private snow excursion', 'Spa day'],
      price: 'From ₹34,999 per couple',
      image: 'https://picsum.photos/seed/manali-pkg2/800/600',
      alt: 'Manali honeymoon special riverside cottage snow',
      whatsappMessage: 'Hi Outbound Travelers, I\'d like to know more about the Manali Honeymoon Special 6N/7D. Please share details and customization options.',
      seasonal: false,
    },
    {
      id: 'manali-adventure',
      name: 'Manali Adventure Pack',
      duration: '6 Nights / 7 Days',
      idealFor: 'Adventure seekers, Friend groups',
      highlights: ['River rafting Beas', 'Paragliding Solang', 'Rohtang snow trek', 'Camping Sissu'],
      price: 'From ₹18,999 per person',
      image: 'https://picsum.photos/seed/manali-pkg3/800/600',
      alt: 'Manali adventure pack rafting paragliding snow trek',
      whatsappMessage: 'Hi Outbound Travelers, I\'d like to know more about the Manali Adventure Pack 6N/7D. Please share details and customization options.',
      seasonal: true,
      seasonMonths: [5, 6, 7, 8, 9],
    },
    {
      id: 'manali-family',
      name: 'Manali Family Holiday',
      duration: '6 Nights / 7 Days',
      idealFor: 'Families with kids, Multi-gen travel',
      highlights: ['Solang cable car', 'Hadimba temple', 'Apple orchards Kullu', 'Snow play'],
      price: 'From ₹16,999 per person',
      image: 'https://picsum.photos/seed/manali-pkg4/800/600',
      alt: 'Manali family holiday kids snow apple orchards',
      whatsappMessage: 'Hi Outbound Travelers, I\'d like to know more about the Manali Family Holiday 6N/7D. Please share details and customization options.',
      seasonal: false,
    },
    {
      id: 'manali-shimla',
      name: 'Manali + Shimla Combo',
      duration: '8 Nights / 9 Days',
      idealFor: 'First-timers, Families, Couples',
      highlights: ['Manali 4N', 'Shimla 3N', 'Rohtang + Kufri', 'Toy train'],
      price: 'From ₹24,999 per person',
      image: 'https://picsum.photos/seed/manali-pkg5/800/600',
      alt: 'Manali Shimla combo tour package Rohtang toy train',
      whatsappMessage: 'Hi Outbound Travelers, I\'d like to know more about the Manali + Shimla Combo 8N/9D. Please share details and customization options.',
      seasonal: false,
    },
  ] as Package[],
  itinerary: [
    {
      day: 1,
      title: 'Arrive Manali — Settle by the Beas',
      description: 'Arrive by overnight Volvo from Delhi or by road from Chandigarh. Check-in to your riverside or valley-view property. Evening stroll through Old Manali and the Mall Road.',
      highlights: ['Arrival and check-in', 'Old Manali evening walk', 'Mall Road Manali'],
      stay: 'Manali',
    },
    {
      day: 2,
      title: 'Solang Valley — Full Adventure Day',
      description: 'Full day at Solang Valley — cable car to the top, snow activities or paragliding depending on season. Zorbing, skiing in winter, river crossing in summer. Back by evening.',
      highlights: ['Solang cable car', 'Season activity (ski/paraglide/zorb)', 'Valley views'],
      stay: 'Manali',
    },
    {
      day: 3,
      title: 'Rohtang Pass — Snow Day (May–Oct only)',
      description: 'Early start for Rohtang Pass (permit pre-booked). Snow play, glacier views, Lahaul valley vista from the top. Return via Rahala Falls. Full day excursion.',
      highlights: ['Rohtang Pass summit', 'Glacier snow play', 'Rahala Falls'],
      stay: 'Manali',
    },
    {
      day: 4,
      title: 'Hadimba Temple, Vashisht & Old Manali',
      description: 'Morning at Hadimba Devi Temple in its cedar forest. Afternoon at Vashisht hot spring temple and Old Manali cafés. Evening at leisure — riverside walk.',
      highlights: ['Hadimba temple cedar forest', 'Vashisht hot springs', 'Old Manali café'],
      stay: 'Manali',
    },
    {
      day: 5,
      title: 'Naggar Castle & Kullu Valley Drive',
      description: 'Drive down the Kullu Valley — Naggar Castle, Roerich Art Gallery, apple orchards. Return via Kullu town and the Beas gorge. Evening bonfire at hotel.',
      highlights: ['Naggar Castle', 'Roerich Gallery', 'Apple orchard drive'],
      stay: 'Manali',
    },
    {
      day: 6,
      title: 'Beas River Rafting & Leisure',
      description: 'Morning white water rafting on the Beas (May–September). Afternoon free for spa, shopping at Tibetan market, or a quiet riverside walk. Farewell dinner.',
      highlights: ['Beas river rafting', 'Tibetan market', 'Farewell dinner'],
      stay: 'Manali',
    },
    {
      day: 7,
      title: 'Departure',
      description: 'Breakfast and checkout. Transfer to Chandigarh airport or Delhi by road. Overnight Volvo option available.',
      highlights: ['Last valley views', 'Hotel checkout', 'Transfer to Chandigarh/Delhi'],
      stay: 'Departure',
    },
  ] as ItineraryDay[],
  hotelTiers: [
    { tier: '3★ Comfort', description: 'Mid-range hotels in Manali town or Old Manali with mountain views, room heaters, and warm hospitality.', price: 'From ₹2,200 per night' },
    { tier: '4★ Premium', description: 'Premium resorts with river or valley views, full amenities, multi-cuisine restaurants, and spa access.', price: 'From ₹3,200 per night' },
    { tier: '5★ Luxury', description: 'Top Manali properties with panoramic snow peak views, heated pools, butler service, and fine dining.', price: 'From ₹4,800 per night' },
    { tier: 'Riverside Cottage', description: 'Standalone cottages on the Beas riverbank — private decks, river sounds, campfire evenings. The definitive Manali romantic stay.', price: 'From ₹3,800 per night' },
  ] as HotelTier[],
  months: [
    { month: 'Jan', rating: 'good', note: 'Heavy snow in Manali town, Rohtang closed. Solang skiing open.' },
    { month: 'Feb', rating: 'good', note: 'Snow season peak, romantic, Solang active.' },
    { month: 'Mar', rating: 'good', note: 'Snow melting, spring beginning, fewer crowds.' },
    { month: 'Apr', rating: 'best', note: 'Pleasant weather, apple blossoms, Rohtang still closed.' },
    { month: 'May', rating: 'best', note: 'Rohtang opens, peak season begins, book early.' },
    { month: 'Jun', rating: 'best', note: 'Best weather, all activities open, some rain.' },
    { month: 'Jul', rating: 'good', note: 'Monsoon rains, lush green, some road risk.' },
    { month: 'Aug', rating: 'good', note: 'Monsoon continues, river rafting peak season.' },
    { month: 'Sep', rating: 'best', note: 'Post-monsoon clarity, all roads open, Rohtang last weeks.' },
    { month: 'Oct', rating: 'best', note: 'Golden autumn, crisp air, last Rohtang visits.' },
    { month: 'Nov', rating: 'good', note: 'Rohtang closes, snow returning to higher areas.' },
    { month: 'Dec', rating: 'good', note: 'Christmas in Manali — snow town, festive atmosphere.' },
  ] as MonthRating[],
  seasons: [
    { id: 'summer', label: 'Peak Summer', months: 'May–Jun', description: 'Rohtang open, all activities running. Best overall weather window. Book 45+ days early.', image: 'https://picsum.photos/seed/manali-summer/800/600' },
    { id: 'monsoon', label: 'Monsoon Green', months: 'Jul–Aug', description: 'Lush valleys, river rafting in full flow. Some road risk. Fewer crowds, lower prices.', image: 'https://picsum.photos/seed/manali-monsoon/800/600' },
    { id: 'autumn', label: 'Golden Autumn', months: 'Sep–Oct', description: 'Post-rain clarity, golden apple orchards, last Rohtang before closure. Most scenic season.', image: 'https://picsum.photos/seed/manali-autumn/800/600' },
    { id: 'winter', label: 'Snow Winter', months: 'Dec–Mar', description: 'Manali under snow, Solang skiing active, Rohtang closed. Romantic and photogenic.', image: 'https://picsum.photos/seed/manali-winter/800/600' },
  ] as Season[],
  process: [
    { step: 1, title: 'Share your dates', description: 'Tell us your travel month — it determines whether Rohtang is open and which activities are available. WhatsApp or form.' },
    { step: 2, title: 'Get a custom itinerary', description: 'A Manali specialist builds your day-wise plan with correct seasonal activities and Rohtang permit status.' },
    { step: 3, title: 'Permits booked in advance', description: 'Rohtang NGT permits are limited daily — we book them as soon as your travel dates are confirmed.' },
    { step: 4, title: 'Travel with full support', description: 'One consultant from your home airport to Manali and back. Reachable throughout your trip.' },
  ] as ProcessStep[],
  inclusions: [
    'Accommodation per chosen tier',
    'Daily breakfast and meals per package',
    'Airport/bus stand pickup and drop (Chandigarh or Manali)',
    'All transfers in private AC vehicle',
    'Rohtang Pass NGT permit (when applicable by season)',
    'English-speaking driver-guide familiar with mountain roads',
    'All applicable tolls and parking',
    'GST on services',
  ],
  exclusions: [
    'Flights or trains to Chandigarh/Delhi (can be booked on request)',
    'Rohtang snow activity tickets (skiing, snow scooter, snow suit)',
    'Solang cable car, zorbing, paragliding tickets (priced live)',
    'River rafting charges (priced at actuals)',
    'Personal expenses, tips, room heater charges',
    'Travel insurance (recommended)',
    'Anything not explicitly in inclusions',
  ],
  gallery: [
    { image: 'https://picsum.photos/seed/manali-g1/800/600', alt: 'Rohtang Pass snow mountains Manali summer' },
    { image: 'https://picsum.photos/seed/manali-g2/800/600', alt: 'Solang Valley cable car skiing adventure Manali' },
    { image: 'https://picsum.photos/seed/manali-g3/800/600', alt: 'Hadimba temple cedar forest Manali Himachal' },
    { image: 'https://picsum.photos/seed/manali-g4/800/600', alt: 'Beas river white water rafting Manali' },
    { image: 'https://picsum.photos/seed/manali-g5/800/600', alt: 'Manali riverside cottage snow winter Beas' },
    { image: 'https://picsum.photos/seed/manali-g6/800/600', alt: 'Old Manali village cafes mountain character' },
    { image: 'https://picsum.photos/seed/manali-g7/800/600', alt: 'Naggar Castle Kullu Valley medieval Himachal' },
    { image: 'https://picsum.photos/seed/manali-g8/800/600', alt: 'Manali snow winter town Mall Road December' },
    { image: 'https://picsum.photos/seed/manali-g9/800/600', alt: 'Vashisht hot springs temple Manali village' },
    { image: 'https://picsum.photos/seed/manali-g10/800/600', alt: 'Apple orchard Kullu valley Manali autumn' },
    { image: 'https://picsum.photos/seed/manali-g11/800/600', alt: 'Paragliding Solang Valley Manali adventure' },
    { image: 'https://picsum.photos/seed/manali-g12/800/600', alt: 'Manali honeymoon couple riverside valley view' },
  ],
  testimonials: [
    { name: 'Karthik & Divya', city: 'Chennai', tripType: 'Honeymoon', quote: 'The riverside cottage was beyond expectations. Woke up to snow peaks and the Beas sound every morning. Rohtang permit was ready before we arrived — zero stress trip.', rating: 5, date: 'June 2026', photo: 'https://picsum.photos/seed/manali-t1/100/100' },
    { name: 'Siva & Friends', city: 'Bangalore', tripType: 'Adventure', quote: 'Rafting, paragliding, Rohtang snow — packed it all in 6 days. Outbound Travelers\' planning made sure nothing clashed. The Rohtang permit saved us from a wasted day.', rating: 5, date: 'September 2026', photo: 'https://picsum.photos/seed/manali-t2/100/100' },
  ] as Testimonial[],
  faqs: [
    { q: 'What is the best time to visit Manali?', a: 'May to June for snow plus all activities. July–August for river rafting and green valleys. September–October for post-monsoon clarity and last Rohtang. December to February for snow romance and Solang skiing. Manali is good year-round — the experience changes by season.' },
    { q: 'Is Rohtang Pass open year-round?', a: 'No — Rohtang Pass is open roughly May to November, depending on snowmelt and NTPC permission. It is closed December through April. We confirm the current status before your trip and plan accordingly. NGT permits are limited to 1,200 vehicles per day.' },
    { q: 'Do we need a permit for Rohtang Pass?', a: 'Yes — NGT-mandated permits are required for all vehicles going to Rohtang. Permits are limited daily and must be booked online in advance. We handle this as part of your package at no extra charge.' },
    { q: 'How do I get to Manali from South India?', a: 'Fly to Delhi or Chandigarh. From Chandigarh it is a 7–8 hour drive or from Delhi a 14-hour overnight Volvo. Most South Indian travelers fly to Delhi and take the overnight bus — arrives fresh in Manali morning. We arrange all connections.' },
    { q: 'How many days are enough for Manali?', a: '5–6 nights covers Solang Valley, Rohtang Pass (seasonal), Hadimba, Old Manali, and Kullu Valley. 7+ nights lets you add Spiti Valley extension or the Shimla combo.' },
    { q: 'What is the difference between Manali and Shimla?', a: 'Shimla is colonial, accessible, family-oriented with the toy train as a highlight. Manali is more adventurous — higher altitude, snow peaks, Rohtang Pass, river rafting, Solang Valley. They pair well together as a combo trip.' },
    { q: 'Can I do river rafting in Manali?', a: 'Yes — white water rafting on the Beas between Pirdi and Jhiri is available May through September. Grade 2–3 rapids, 14km route, 2 hours. We include this in adventure packages and it can be added to any itinerary.' },
    { q: 'Is Manali safe for families with kids?', a: 'Very family-friendly. Solang Valley has safe, supervised snow activities. Hadimba and Old Manali are easy walks. Kullu Valley drives are comfortable. We pace family itineraries appropriately and avoid the more extreme activities for younger kids.' },
    { q: 'What activities are available in Manali in winter (Dec–Mar)?', a: 'Rohtang is closed but Solang Valley has skiing, snow tubing, and snowmobile rides. Manali town itself can have snow. Hadimba temple in snow is stunning. Winter is romantic and peaceful with far fewer crowds.' },
    { q: 'Can I go to Spiti Valley from Manali?', a: 'Yes — Manali to Kaza via Kunzum Pass is one of the most dramatic road trips in India. Open June to September only. Takes 8–10 hours one way. We can add 2–3 nights in Spiti as an extension to your Manali package.' },
    { q: 'What should I pack for Manali?', a: 'Warm layers year-round (nights are cool even in summer), rain jacket for July–August, snow gear for winter (or rent in Solang), sunscreen for Rohtang (UV is intense), comfortable trekking shoes. Full list shared post-booking.' },
    { q: 'Is Manali suitable for a honeymoon?', a: 'Absolutely — riverside cottages on the Beas, snow peaks visible from your room, candlelit dinners, and the private feeling of the Kullu Valley make Manali one of North India\'s best honeymoon destinations. We design dedicated honeymoon packages with upgraded stays and romantic add-ons.' },
  ] as FAQ[],
  relatedDestinations: [
    { name: 'Shimla', image: 'https://picsum.photos/seed/shimla-rel/400/300', href: '/shimla' },
    { name: 'Kashmir', image: 'https://picsum.photos/seed/kashmir-rel/400/300', href: '/kashmir' },
    { name: 'Ladakh', image: 'https://picsum.photos/seed/ladakh-rel/400/300', href: '/ladakh' },
    { name: 'Sikkim', image: 'https://picsum.photos/seed/sikkim-rel/400/300', href: '/sikkim' },
  ] as RelatedDestination[],
  whatsapp: {
    number: '919876543210',
    heroMessage: 'Hi Outbound Travelers, I\'m interested in a Manali tour package. Please share itinerary options and a quote.',
    stickyMessage: 'Hi Outbound Travelers, I\'m planning a Manali trip. Can someone help me plan and quote?',
    floaterMessage: 'Hi Outbound Travelers, I\'m interested in a Manali tour package. Please share itinerary options and a quote.',
    finalCtaMessage: 'Hi Outbound Travelers, I\'m ready to plan my Manali trip. Please send me your best itinerary and quote.',
    postFormMessage: 'Hi Outbound Travelers, I just submitted my Manali enquiry. Travel month: {month}, {travelers} travelers from {city}, trip type: {tripType}. Looking forward to the itinerary and quote.',
  } as WhatsAppConfig,
  leadForm: {
    title: 'Get your Manali quote',
    subtitle: 'Tell us your travel month — it changes everything about what Manali can offer you.',
    submitButtonText: 'Get my Manali quote',
    successMessage: 'Got it! Your Manali specialist will WhatsApp you within 2 hours. Meanwhile, save our number: +91-98765-43210.',
    destinationId: 'manali',
    destinationName: 'Manali',
  } as LeadFormConfig,
  permitInfo: {
    title: '🏔️ Rohtang Pass — Permit Information',
    subtitle: 'Rohtang requires an NGT permit. We handle this for you.',
    points: [
      'Rohtang Pass is open approximately May to November each year',
      'NGT limits vehicles to 1,200 per day — permits sell out fast in peak season',
      'Permits must be booked online 1–7 days before the visit date',
      'We book Rohtang permits as soon as your travel dates are confirmed',
      'If Rohtang is closed (Dec–Apr), Solang Valley is always open',
      'We monitor permit availability and adjust your itinerary if quota fills',
    ],
  },
  adventureRomantic: {
    adventure: {
      title: 'Manali for the Adventurer',
      image: 'https://picsum.photos/seed/manali-adventure-feat/800/600',
      highlights: [
        'Rohtang Pass snow trek and glacier views',
        'River rafting Grade 2–3 on the Beas',
        'Paragliding over Solang Valley',
        'Spiti Valley extension — the ultimate road trip',
      ],
      cta: 'See adventure packages',
    },
    romantic: {
      title: 'Manali for the Couple',
      image: 'https://picsum.photos/seed/manali-romantic-feat/800/600',
      highlights: [
        'Riverside cottage with Beas river sounds',
        'Private snow excursion to Rohtang',
        'Candlelit dinner with valley view',
        'Couples spa in a mountain resort',
      ],
      cta: 'See honeymoon packages',
    },
  },
  seoContent: {
    h2: 'Planning Your Manali Trip with Outbound Travelers',
    sections: [
      {
        h3: 'Which Manali itinerary is right for you?',
        body: 'The classic Manali tour package covers Solang Valley, Rohtang Pass, Hadimba Temple, and the Kullu Valley drive in five to six nights. Adventure travelers add river rafting, paragliding, and a Spiti extension. Couples opt for riverside cottages and private snow excursions. The Manali plus Shimla combo in eight nights is our most popular North India circuit for first-time visitors — two very different hill experiences back to back.',
      },
      {
        h3: 'Manali from South India — flights, connections, what to plan around',
        body: 'Fly to Delhi from Chennai, Bangalore, Kochi, or Hyderabad. The overnight Volvo bus from Delhi reaches Manali in 14 hours — most South Indian travelers prefer this over breaking the journey in Chandigarh. We book Volvo tickets as part of your package. Alternatively fly to Chandigarh for a 7-hour road transfer. The Manali flight option via Bhuntar airport is weather-dependent and not recommended for planned itineraries.',
      },
      {
        h3: 'Customizing your Manali package',
        body: 'Honeymooners upgrade to riverside cottages and add candlelit dinners, couples spa sessions, and a private Rohtang snow excursion without group crowds. Adventure groups build around the full Solang day, rafting on the Beas, and the Spiti road trip extension. Families focus on Solang snow activities, Hadimba temple, and the Kullu orchard drive. Every Manali tour package we build starts from your group and your season.',
      },
      {
        h3: 'Why book Manali with Outbound Travelers',
        body: 'Rohtang permits are the single biggest source of stress on a Manali trip — sold out permits mean a wasted snow day. We book permits the moment your travel dates are confirmed. Our drivers know every mountain road condition and our consultants monitor road closures throughout your trip. And because we specialize in South Indian travelers, we plan the Delhi or Chandigarh connection so it works with your flight timings.',
      },
    ],
  },
}
