import type {
  TrustBadge,
  Package,
  ItineraryDay,
  FAQ,
  Testimonial,
  RelatedDestination,
  ProcessStep,
} from '@/lib/shared/types'

export const keralaData = {
  meta: {
    title: 'Kerala Tour Packages — Backwaters, Munnar, Honeymoon Trips | Outbound Travelers',
    description: 'Customisable Kerala tour packages from ₹12,500. Alleppey houseboats, Munnar hills, Thekkady, Kovalam beaches. Honeymoon-friendly, family-tested.',
    canonical: 'https://www.outboundtravelers.com/destinations/kerala-tour-packages',
    ogImage: 'https://picsum.photos/seed/kerala-og/1200/630',
    h1: "Kerala Tour Packages — God's Own Country, On Your Pace",
  },

  theme: {
    accentColor: '#047857',
    accentSoft: '#FAF6F0',
    motif: 'palm-kettuvallam',
  },

  hero: {
    variant: 'HeroCinematic',
    eyebrow: 'Domestic · Backwaters & Hills · Sep–Mar peak',
    headline: 'Where the Water Walks You Through the Trip',
    subheadline: 'Houseboats on the Vembanad backwaters. Tea estates in Munnar. Spice trails in Thekkady. Kovalam at sunset. Kerala doesn\'t rush — and neither should you.',
    primaryCta: { label: 'Plan My Kerala Trip on WhatsApp', action: 'whatsapp' as const },
    secondaryCta: { label: 'See Packages', action: 'scroll' as const, target: '#kerala-packages' },
    trustChips: ['Honeymoon-tested', 'Houseboats curated', 'Wellness add-ons', '24/7 ground team'],
    desktopImage: 'https://picsum.photos/seed/kerala-hero-d/1920/1080',
    mobileImage: 'https://picsum.photos/seed/kerala-hero-m/800/1200',
    imageAlt: 'Kerala houseboat kettuvallam Alleppey backwaters Vembanad lake palm trees',
  },

  quickSummary: [
    { label: 'Best Time', value: 'Sep–Mar' },
    { label: 'Days', value: '4N/5D to 7N/8D' },
    { label: 'Starts From', value: '₹12,500 per person' },
    { label: 'Honeymoon-ready', value: 'Yes' },
  ],

  whyVisit: {
    title: 'Why Kerala',
    body: 'Kerala is the only place where the road sometimes becomes water and nobody finds it strange. You wake up on a houseboat, drift past coconut groves, and have lunch served on banana leaves. Then you drive up to Munnar where the tea estates roll on forever, and into Thekkady where the spice plantation guide tells you the difference between fresh cardamom and the kind you buy in a box. We build trips where you don\'t have to choose — you do all of it, just slower.',
  },

  honeymoonSpecial: {
    enabled: true,
    title: "Kerala for honeymoon — what's different",
    body: 'Private houseboat (not a shared cabin) for the Alleppey night, candlelit dinner on the deck, hillside-view room in Munnar, optional couple Ayurveda massage, late checkouts, photographer add-on for sunset Kovalam. The pacing is slower than the standard family itinerary — 2 nights per location, not 1.',
    image: 'https://picsum.photos/seed/kerala-honeymoon/800/600',
    imageAlt: 'Kerala honeymoon private houseboat Alleppey candlelit dinner deck',
  },

  regions: [
    { id: 'munnar', name: 'Munnar', description: 'Tea estates, cool climate, photogenic', idealFor: 'Family, Honeymoon', topThree: ['Tea Museum', 'Eravikulam', 'Mattupetty Dam'], image: 'https://picsum.photos/seed/kerala-munnar/800/600', imageAlt: 'Munnar tea estates hills green Kerala cool climate' },
    { id: 'alleppey', name: 'Alleppey', description: 'Backwaters, houseboat night', idealFor: 'All segments', topThree: ['Houseboat overnight', 'Village walks', 'Sunset cruise'], image: 'https://picsum.photos/seed/kerala-alleppey/800/600', imageAlt: 'Alleppey houseboat backwaters Kerala Vembanad lake' },
    { id: 'thekkady', name: 'Thekkady', description: 'Spice plantations, Periyar wildlife', idealFor: 'Family, Heritage', topThree: ['Spice walk', 'Periyar boat ride', 'Kathakali'], image: 'https://picsum.photos/seed/kerala-thekkady/800/600', imageAlt: 'Thekkady spice plantation Periyar wildlife Kerala' },
    { id: 'kovalam-varkala', name: 'Kovalam / Varkala', description: 'Beaches, sunset', idealFor: 'Honeymoon', topThree: ['Sunset', 'Lighthouse Beach', 'Varkala Cliffs'], image: 'https://picsum.photos/seed/kerala-kovalam/800/600', imageAlt: 'Kovalam beach sunset Varkala cliffs Kerala' },
    { id: 'kumarakom', name: 'Kumarakom', description: 'Quieter backwaters, lakeside resort feel', idealFor: 'Luxury, Wellness', topThree: ['Bird sanctuary', 'Lakeside stays', 'Backwaters'], image: 'https://picsum.photos/seed/kerala-kumarakom/800/600', imageAlt: 'Kumarakom backwaters bird sanctuary Kerala lake' },
    { id: 'wayanad', name: 'Wayanad', description: 'Coffee, waterfalls, less touristy', idealFor: 'Off-beat, Family', topThree: ['Edakkal Caves', 'Banasura Sagar Dam', 'Coffee plantations'], image: 'https://picsum.photos/seed/kerala-wayanad/800/600', imageAlt: 'Wayanad coffee plantation waterfall Kerala offbeat' },
  ],

  topExperiences: [
    { id: 'houseboat', title: 'Alleppey houseboat overnight', subtitle: 'Vembanad backwaters', image: 'https://picsum.photos/seed/kerala-exp1/800/600', alt: 'Alleppey houseboat overnight Vembanad Kerala backwaters' },
    { id: 'munnar-tea', title: 'Munnar tea estates', subtitle: 'Tata Tea Museum', image: 'https://picsum.photos/seed/kerala-exp2/800/600', alt: 'Munnar tea estates Tata Tea Museum Kerala hills' },
    { id: 'thekkady', title: 'Thekkady spice walk + Periyar boat', subtitle: 'Wildlife glimpse included', image: 'https://picsum.photos/seed/kerala-exp3/800/600', alt: 'Thekkady spice walk Periyar boat ride wildlife' },
    { id: 'kovalam-beach', title: 'Kovalam sunset / Varkala cliffs', subtitle: 'Kerala beach evening', image: 'https://picsum.photos/seed/kerala-exp4/800/600', alt: 'Kovalam beach sunset Varkala cliffs Kerala evening' },
    { id: 'kathakali', title: 'Kathakali performance', subtitle: 'Kochi cultural experience', image: 'https://picsum.photos/seed/kerala-exp5/800/600', alt: 'Kathakali performance Kochi Kerala traditional dance' },
    { id: 'village-walk', title: 'Backwater village walk', subtitle: 'Real Kerala life', image: 'https://picsum.photos/seed/kerala-exp6/800/600', alt: 'Kerala backwater village walk local life coconut groves' },
    { id: 'kumarakom-birds', title: 'Kumarakom bird sanctuary', subtitle: 'Dawn boat ride', image: 'https://picsum.photos/seed/kerala-exp7/800/600', alt: 'Kumarakom bird sanctuary dawn boat ride Kerala' },
    { id: 'ayurveda', title: 'Ayurveda session', subtitle: 'Licensed centres only', image: 'https://picsum.photos/seed/kerala-exp8/800/600', alt: 'Kerala Ayurveda massage wellness licensed centre' },
  ],

  houseboatModule: {
    enabled: true,
    title: 'Choose your houseboat',
    subtitle: 'One night on the Vembanad backwaters is the Kerala experience. We curate the boat, not just the booking.',
    tiers: [
      { tier: 'Standard 1BHK', includes: 'AC bedroom, private deck, all meals, one night', price: 'From ₹8,500 per night', image: 'https://picsum.photos/seed/kerala-hb1/800/600', imageAlt: 'Standard 1BHK houseboat Alleppey Kerala deck' },
      { tier: 'Premium 2BHK', includes: 'Two bedrooms, larger deck, premium meals, sunset cruise', price: 'From ₹13,000 per night', image: 'https://picsum.photos/seed/kerala-hb2/800/600', imageAlt: 'Premium 2BHK houseboat Alleppey Kerala sunset cruise' },
      { tier: 'Luxury', includes: 'Private boat with crew, butler service, gourmet meals', price: 'From ₹24,000 per night', image: 'https://picsum.photos/seed/kerala-hb3/800/600', imageAlt: 'Luxury private houseboat Kerala crew butler service' },
    ],
  },

  wellnessAddons: [
    { name: 'Couple massage (90 min)', priceFrom: '₹3,500 per couple', description: 'Traditional Kerala Abhyanga by certified therapists at licensed centres.' },
    { name: '3-day rejuvenation retreat', priceFrom: '₹12,000 per person', description: 'Shirodhara, Pizhichil, and herbal steam. Included in Wellness Retreat package.' },
    { name: '7-day Panchakarma', priceFrom: '₹28,000 per person', note: 'Requires doctor consult', description: 'Full detox and rejuvenation. Requires pre-booking and medical consultation.' },
  ],

  packages: [
    {
      id: 'kerala-honeymoon-classic',
      name: 'Kerala Honeymoon Classic',
      duration: '5N/6D',
      featured: true,
      idealFor: 'Couples, Honeymoon, Anniversary',
      tier: 'Premium',
      highlights: ['Munnar 2N — hillside view room', 'Thekkady 1N — spice walk + Periyar', 'Alleppey 1N — private houseboat, candlelit deck dinner', 'Kovalam 1N — sunset beach'],
      price: 'From ₹24,500 per couple',
      image: 'https://picsum.photos/seed/kerala-pkg1/800/600',
      alt: 'Kerala honeymoon classic package Munnar Alleppey Kovalam 5 nights',
      whatsappMessage: "Hi Outbound Travelers, I'd like to know more about the Kerala Honeymoon Classic 5N/6D package. Please share details and a quote.",
      seasonal: false,
    },
    {
      id: 'kerala-family',
      name: 'Kerala Family Tour',
      duration: '6N/7D',
      featured: false,
      idealFor: 'Families, Multi-gen, Seniors',
      tier: 'Comfort / Premium',
      highlights: ['Kochi 1N', 'Munnar 2N', 'Thekkady 1N', 'Alleppey 1N houseboat', 'Kovalam 1N'],
      price: 'From ₹15,500 per person',
      image: 'https://picsum.photos/seed/kerala-pkg2/800/600',
      alt: 'Kerala family tour package 6 nights Kochi Munnar Alleppey Kovalam',
      whatsappMessage: "Hi Outbound Travelers, I'd like to know more about the Kerala Family Tour 6N/7D. Please share details and a quote.",
      seasonal: false,
    },
    {
      id: 'kerala-backwater-beach',
      name: 'Kerala Backwater & Beach Short',
      duration: '4N/5D',
      featured: false,
      idealFor: 'Couples, Short break, First-timers',
      tier: 'Comfort',
      highlights: ['Alleppey 1N houseboat', 'Kumarakom 1N lakeside', 'Kovalam 2N beach'],
      price: 'From ₹12,500 per person',
      image: 'https://picsum.photos/seed/kerala-pkg3/800/600',
      alt: 'Kerala backwater beach short trip 4 nights Alleppey Kumarakom Kovalam',
      whatsappMessage: "Hi Outbound Travelers, I'd like to know more about the Kerala Backwater & Beach Short Trip 4N/5D. Please share details and a quote.",
      seasonal: false,
    },
    {
      id: 'kerala-wellness',
      name: 'Kerala Wellness Retreat',
      duration: '7N/8D',
      featured: false,
      idealFor: 'Wellness seekers, Couples, International travelers',
      tier: 'Premium',
      highlights: ['Ayurveda focus throughout', 'Balanced sightseeing', 'Licensed wellness centres', 'Munnar + Alleppey + Kovalam'],
      price: 'From ₹29,000 per person',
      image: 'https://picsum.photos/seed/kerala-pkg4/800/600',
      alt: 'Kerala wellness Ayurveda retreat 7 nights package',
      whatsappMessage: "Hi Outbound Travelers, I'd like to know more about the Kerala Wellness Retreat 7N/8D. Please share details and a quote.",
      seasonal: false,
    },
    {
      id: 'kerala-luxury',
      name: 'Kerala Luxury Escape',
      duration: '6N/7D',
      featured: false,
      idealFor: 'Luxury travelers, Couples, Anniversaries',
      tier: 'Luxury',
      highlights: ['5★ stays throughout', 'Private guide', 'Luxury houseboat', 'Leela / Taj Kovalam'],
      price: 'From ₹48,000 per couple',
      image: 'https://picsum.photos/seed/kerala-pkg5/800/600',
      alt: 'Kerala luxury escape 5 star package 6 nights private guide',
      whatsappMessage: "Hi Outbound Travelers, I'd like to know more about the Kerala Luxury Escape 6N/7D. Please share details and a quote.",
      seasonal: false,
    },
    {
      id: 'wayanad-quick',
      name: 'Wayanad Quick Escape',
      duration: '3N/4D',
      featured: false,
      idealFor: 'Off-beat travelers, Families, Nature lovers',
      tier: 'Comfort / Premium',
      highlights: ['Edakkal Caves', 'Banasura Sagar Dam', 'Coffee plantation walk', 'Less-touristed Kerala'],
      price: 'From ₹9,500 per person',
      image: 'https://picsum.photos/seed/kerala-pkg6/800/600',
      alt: 'Wayanad quick escape 3 nights Kerala offbeat coffee plantation',
      whatsappMessage: "Hi Outbound Travelers, I'd like to know more about the Wayanad Quick Escape 3N/4D. Please share details and a quote.",
      seasonal: false,
    },
  ] as Package[],

  itinerary: [
    {
      day: 1,
      title: 'Arrive Kochi → Drive to Munnar',
      description: 'Land at Kochi International Airport. 4-hour scenic drive through rubber and tea plantations to Munnar. Check-in to hillside property. Evening at leisure — first views of the Western Ghats.',
      highlights: ['Kochi airport arrival', '4-hour Munnar drive', 'Hotel check-in', 'Evening at leisure'],
      stay: 'Munnar',
    },
    {
      day: 2,
      title: 'Munnar — Tea Estates & Eravikulam',
      description: 'Full day Munnar sightseeing. Eravikulam National Park (Nilgiri Tahr), Tata Tea Museum, Mattupetty Dam and Echo Point. Tea estate walk with plantation guide.',
      highlights: ['Eravikulam National Park', 'Tata Tea Museum', 'Mattupetty Dam', 'Echo Point'],
      stay: 'Munnar',
      note: 'Eravikulam closed Jan 15–Mar 15 for calving season — alternative arranged.',
      noteBadge: 'Seasonal note',
    },
    {
      day: 3,
      title: 'Munnar → Thekkady — Spice Walk + Kathakali',
      description: '3-hour drive to Thekkady. Afternoon spice plantation walk — cardamom, pepper, cinnamon. Periyar Lake boat ride for wildlife spotting. Evening Kathakali performance.',
      highlights: ['3-hr Thekkady drive', 'Spice plantation walk', 'Periyar boat ride', 'Kathakali evening show'],
      stay: 'Thekkady',
    },
    {
      day: 4,
      title: 'Thekkady → Alleppey — Board Houseboat',
      description: '4-hour drive to Alleppey. Board your private houseboat at noon. Cruise the Vembanad backwaters through coconut groves and village life. Sunset cruise. Candlelit dinner served on deck. Overnight on the water.',
      highlights: ['4-hr Alleppey drive', 'Board houseboat at noon', 'Backwater cruise', 'Candlelit deck dinner'],
      stay: 'Houseboat — Vembanad Backwaters',
      note: 'Day 4 is the highlight of the trip — pace is deliberately slow.',
      noteBadge: 'Houseboat night',
    },
    {
      day: 5,
      title: 'Disembark → Kovalam Beach',
      description: 'Morning on the backwaters before disembarking. 3-hour drive to Kovalam. Check-in to beachside property. Evening sunset walk on Lighthouse Beach.',
      highlights: ['Morning backwater cruise', 'Disembark and check-out', '3-hr Kovalam drive', 'Lighthouse Beach sunset'],
      stay: 'Kovalam',
    },
    {
      day: 6,
      title: 'Depart from Trivandrum',
      description: 'Optional couple Ayurveda massage at a licensed centre (90 min). Transfer to Trivandrum International Airport for departure.',
      highlights: ['Optional Ayurveda session', 'Hotel checkout', 'Trivandrum airport transfer'],
      stay: 'Departure',
      note: 'Ayurveda session must be pre-booked — confirm at booking stage.',
      noteBadge: 'Optional add-on',
    },
  ],

  hotelTiers: [
    {
      tier: 'Comfort (3★)',
      description: 'Well-located properties across Kerala — close to key sights, clean, reliable.',
      byLocation: { munnar: 'Standard Stays', thekkady: 'Standard Hotels', alleppey: 'Standard Houseboat', kovalam: 'Beachside Comfort' },
      price: 'From ₹4,500 per night',
    },
    {
      tier: 'Premium (4★)',
      description: 'Boutique resorts and premium properties with views, multi-cuisine dining, and spa access.',
      byLocation: { munnar: 'Tea Country / SpiceTree', thekkady: 'Cardamom County', alleppey: 'Premium Houseboat', kovalam: 'Uday Samudra' },
      price: 'From ₹8,000 per night',
    },
    {
      tier: 'Luxury (5★)',
      description: 'Signature Kerala luxury — Tea Sanctuary in Munnar, Taj Gateway Thekkady, Leela or Taj at Kovalam.',
      byLocation: { munnar: 'Tea Sanctuary', thekkady: 'Taj Gateway', alleppey: 'Luxury Houseboat', kovalam: 'Leela / Taj Green Cove' },
      price: 'From ₹16,500 per night',
    },
  ],

  months: [
    { month: 'Jan', status: 'peak' as const, note: 'Cool and clear. Peak season. Book early.' },
    { month: 'Feb', status: 'peak' as const, note: 'Best weather. Eravikulam opens mid-Feb.' },
    { month: 'Mar', status: 'peak' as const, note: 'Warm and pleasant. Ideal for beaches.' },
    { month: 'Apr', status: 'shoulder' as const, note: 'Getting hot. Shoulder pricing.' },
    { month: 'May', status: 'shoulder' as const, note: 'Hot and humid. Pre-monsoon.' },
    { month: 'Jun', status: 'wellness' as const, note: 'Monsoon arrives. Ayurveda season begins.' },
    { month: 'Jul', status: 'wellness' as const, note: 'Full monsoon. Best for wellness. Avoid beaches.' },
    { month: 'Aug', status: 'wellness' as const, note: 'Monsoon. Houseboats run. Lush and green.' },
    { month: 'Sep', status: 'peak' as const, note: 'Post-monsoon clarity. Peak season starts.' },
    { month: 'Oct', status: 'peak' as const, note: 'Pleasant. All sights open.' },
    { month: 'Nov', status: 'peak' as const, note: 'Ideal weather. High season.' },
    { month: 'Dec', status: 'peak' as const, note: 'Peak — Christmas and New Year travel. Book 45+ days early.' },
  ],

  seasons: [
    { id: 'peak', label: 'Sep–Mar Peak', months: 'September to March', description: 'Best weather for all activities. Houseboat, beaches, wildlife all open. Book Dec–Feb early.', image: 'https://picsum.photos/seed/kerala-season-peak/800/600' },
    { id: 'shoulder', label: 'Apr–May Shoulder', months: 'April to May', description: 'Hot and humid but fewer crowds. Lower prices. Good for Munnar (cooler hills).', image: 'https://picsum.photos/seed/kerala-season-shoulder/800/600' },
    { id: 'wellness', label: 'Jun–Aug Monsoon / Ayurveda', months: 'June to August', description: "Kerala's Ayurveda season — the therapeutic benefits are highest in monsoon. Beaches closed, houseboats run, Munnar is misty green. Best for wellness retreats.", image: 'https://picsum.photos/seed/kerala-season-monsoon/800/600' },
  ] as Season[],

  process: [
    { step: 1, title: 'Tell us your group', description: 'Share travel dates, group size, and whether this is honeymoon, family, or wellness-focused. We\'ll ask about houseboat preference.' },
    { step: 2, title: 'We design your circuit', description: 'A Kerala specialist builds your region-by-region plan — right number of nights per location, houseboat pre-selected, Ayurveda booked if needed.' },
    { step: 3, title: 'You confirm and pay deposit', description: 'Review, customise, confirm. Houseboat and wellness slots are limited — we hold them at booking.' },
    { step: 4, title: 'Ground team on call', description: 'Kerala ground team reachable throughout — from Kochi arrival to Trivandrum departure, including on the backwaters.' },
  ] as ProcessStep[],

  inclusions: [
    'Accommodation per chosen tier across all locations',
    'Daily breakfast at all hotels',
    'Houseboat with all meals when included in package',
    'All transfers in private AC vehicle',
    'Airport pickup (Kochi) and drop (Trivandrum or Kochi)',
    'Spice plantation walk and Periyar boat ride when listed in package',
    'All applicable tolls and parking',
    'GST on services',
  ],

  exclusions: [
    'Flights to Kochi or Trivandrum (can be booked on request)',
    'Lunch and dinner at hotels (except on houseboat)',
    'Wellness and Ayurveda packages (priced separately)',
    'Kathakali and cultural show tickets (priced at actuals)',
    'Eravikulam National Park entry fees',
    'Personal expenses and tips',
    'Travel insurance (strongly recommended)',
    'Anything not explicitly listed in inclusions',
  ],

  gallery: [
    { image: 'https://picsum.photos/seed/kerala-g1/800/600', alt: 'Kerala houseboat kettuvallam Alleppey Vembanad backwaters sunset' },
    { image: 'https://picsum.photos/seed/kerala-g2/800/600', alt: 'Munnar tea estates green hills Western Ghats Kerala' },
    { image: 'https://picsum.photos/seed/kerala-g3/800/600', alt: 'Thekkady spice plantation cardamom pepper Kerala' },
    { image: 'https://picsum.photos/seed/kerala-g4/800/600', alt: 'Kovalam beach lighthouse sunset Kerala' },
    { image: 'https://picsum.photos/seed/kerala-g5/800/600', alt: 'Kathakali performance traditional dance Kochi Kerala' },
    { image: 'https://picsum.photos/seed/kerala-g6/800/600', alt: 'Kerala backwater village coconut grove canal boat' },
    { image: 'https://picsum.photos/seed/kerala-g7/800/600', alt: 'Kumarakom bird sanctuary dawn boat ride Kerala' },
    { image: 'https://picsum.photos/seed/kerala-g8/800/600', alt: 'Kerala Ayurveda massage wellness treatment licensed centre' },
    { image: 'https://picsum.photos/seed/kerala-g9/800/600', alt: 'Varkala cliffs beach Kerala sunset couple' },
    { image: 'https://picsum.photos/seed/kerala-g10/800/600', alt: 'Wayanad coffee plantation waterfall offbeat Kerala' },
    { image: 'https://picsum.photos/seed/kerala-g11/800/600', alt: 'Munnar Eravikulam National Park Nilgiri Tahr fog' },
    { image: 'https://picsum.photos/seed/kerala-g12/800/600', alt: 'Houseboat candlelit dinner deck Alleppey Kerala honeymoon' },
  ],

  testimonials: [
    { name: 'Aravind & Sneha', city: 'Bangalore', tripType: 'Honeymoon', quote: 'The private houseboat at Alleppey was the highlight — candlelit dinner under the stars, water lapping. Magical.', rating: 5, photo: 'https://picsum.photos/seed/kerala-t1/100/100', date: 'March 2026' },
    { name: 'Krishnan family', city: 'Chennai', tripType: 'Family', quote: 'Three generations. Munnar weather was perfect for my parents. Houseboat was clean and the food was excellent.', rating: 5, photo: 'https://picsum.photos/seed/kerala-t2/100/100', date: 'April 2026' },
    { name: 'Diya & Mark', city: 'Hyderabad', tripType: 'Wellness', quote: 'International couple, first time in Kerala. The wellness add-on was unexpected and exactly what we needed.', rating: 5, photo: 'https://picsum.photos/seed/kerala-t3/100/100', date: 'May 2026' },
  ] as Testimonial[],

  faqs: [
    { q: 'What is the best time to visit Kerala?', a: 'September to March for pleasant weather across all regions. June to August (monsoon) is Kerala\'s Ayurveda season — lush and beautiful but beaches are rough. Houseboats run through the monsoon.' },
    { q: 'Is one night on the houseboat enough?', a: 'Yes — one night is the sweet spot. You board at noon, cruise through the afternoon and evening, wake up on the water, and disembark the next morning. Two nights starts to feel repetitive unless you\'re on a luxury private boat.' },
    { q: 'Should I do Munnar + Alleppey or just one?', a: 'The combination is standard for a reason — Munnar hills and Alleppey backwaters are two completely different Kerala experiences. Munnar 2N + Alleppey 1N is the most popular pairing. Most 5-night packages include both.' },
    { q: 'Is Kerala suitable for families with infants?', a: 'Yes — all our hotel stays are family-friendly. The houseboat is safe with railings and the crew is experienced with families. We pace family itineraries accordingly and can slow down Munnar for younger children.' },
    { q: 'Is vegetarian food available throughout?', a: 'Kerala has exceptional vegetarian cuisine. All hotels cater to pure vegetarian. Houseboats prepare pure veg meals on request. The banana-leaf meal in Kochi is a must even for non-vegetarians.' },
    { q: 'Is the Ayurveda authentic or touristy?', a: 'Both exist in Kerala. We only partner with licensed Ayurveda centres with certified therapists — not hotel spa rebrands. The 3-day and 7-day retreats require actual consultation with an Ayurveda doctor.' },
    { q: 'How do I reach Kerala from South India?', a: 'Fly into Kochi International Airport or Trivandrum International Airport. Direct flights from Bangalore, Chennai, Hyderabad, and all major metros. We can book flights as part of your package on request.' },
    { q: 'What makes the honeymoon package different from the regular package?', a: 'Private houseboat instead of shared cabin, candlelit deck dinner, hillside-view room in Munnar, 2 nights per location instead of 1, late checkouts, optional couple Ayurveda massage, and photographer add-on at Kovalam sunset. The pacing is slower throughout.' },
    { q: 'Is Kerala worth visiting during the monsoon?', a: 'Yes for wellness — the monsoon is actually Ayurveda\'s peak season because the therapeutic benefits are strongest then. Not ideal for beaches. Houseboats run through the monsoon. Munnar turns extraordinarily green. If you\'re doing a wellness retreat, July–August is ideal.' },
    { q: 'Should I add Wayanad to my Kerala trip?', a: 'If you have 8 or more days, yes — Wayanad is a less-touristed, coffee-plantation Kerala with waterfalls and Edakkal Caves. If you have 5–6 days, stick to the classic Munnar–Thekkady–Alleppey–Kovalam circuit first.' },
    { q: 'Are Kerala tour packages customisable?', a: 'Yes — all our itineraries are built around your group, travel style, and pace. We can swap locations, add Kumarakom, change hotel tiers by location, add wellness, or extend into Wayanad.' },
    { q: 'Is Kerala comfortable for senior citizens?', a: 'Very much so — Kerala travel is gentle paced. We book lift-equipped hotels for seniors, choose flatter terrain options in Munnar, and ensure the houseboat has accessible boarding. We\'ve run many three-generation Kerala trips.' },
  ] as FAQ[],

  relatedDestinations: [
    { name: 'Lakshadweep', image: 'https://picsum.photos/seed/lakshadweep-rel/400/300', href: '/destinations/lakshadweep-tour-packages' },
    { name: 'Andaman & Nicobar', image: 'https://picsum.photos/seed/andaman-rel/400/300', href: '/destinations/andaman-tour-packages' },
    { name: 'Ooty', image: 'https://picsum.photos/seed/ooty-rel/400/300', href: '/destinations/ooty-tour-packages' },
  ] as RelatedDestination[],

  whatsapp: {
    number: '919876543210',
    heroMessage: "Hi Outbound Travelers, I'm interested in a Kerala tour package. Please share itinerary options and a quote.",
    stickyMessage: "Hi Outbound Travelers, I'm planning a Kerala trip. Can someone help me plan and quote?",
    floaterMessage: "Hi Outbound Travelers, I'm interested in a Kerala tour package. Please share itinerary options and a quote.",
    finalCtaMessage: "Hi Outbound Travelers, I'm ready to plan my Kerala trip. Please send me your best itinerary and quote.",
    postFormMessage: 'Hi Outbound Travelers, I just submitted my Kerala enquiry. Travel month: {month}, {travelers} travelers from {city}, trip type: {tripType}. Looking forward to the itinerary and quote.',
  },

  leadForm: {
    title: 'Get your Kerala quote',
    subtitle: 'Tell us your travel month and whether this is a honeymoon, family, or wellness trip — the houseboat and region mix changes.',
    submitButtonText: 'Get my Kerala quote',
    successMessage: 'Got it! Your Kerala specialist will WhatsApp you within 2 hours. Houseboat availability checked on your dates.',
    destinationId: 'kerala',
    destinationName: 'Kerala',
  },

  seoContent: {
    h2: 'Planning Your Kerala Trip with Outbound Travelers',
    sections: [
      {
        h3: 'Choosing your Kerala circuit — regions and nights',
        body: 'The classic Kerala circuit runs Munnar for two nights, Thekkady for one, Alleppey houseboat for one, and Kovalam for one — five nights in total. This is the most popular pattern for a reason: it gives you the cool hills, the spice country, the backwaters, and the beach without any single location feeling rushed. Families often add Kochi for a night at the start. Honeymooners slow down to two nights per location for a seven-night trip. Wellness travelers swap Kovalam for Kumarakom and build the Ayurveda sessions around the circuit.',
      },
      {
        h3: 'Kerala from South India — flights and the drive factor',
        body: 'Most South Indian travelers fly into Kochi and depart from Trivandrum — the natural direction of the classic circuit. Direct flights connect Bangalore, Chennai, Hyderabad, and Coimbatore to Kochi in under two hours. From Kochi, the Munnar drive takes four hours through the Western Ghats — and it is genuinely part of the Kerala experience. We plan arrival times to make sure Day 1 driving is not wasted time.',
      },
      {
        h3: 'The houseboat question — what to know before you book',
        body: 'The Alleppey houseboat is the single most asked-about element of a Kerala trip. One night is the right duration for most travelers. The houseboat boards at noon, cruises through the afternoon into evening, stays moored overnight, and disembarks the following morning. A private houseboat means the boat is exclusively yours — no shared cabins, no strangers at dinner. For honeymooners we only book private boats. Standard packages use shared-cabin boats for solo travelers or couples on tighter budgets. We inspect every houseboat we list.',
      },
      {
        h3: 'Why book Kerala with Outbound Travelers',
        body: 'We are a South India-based agency that has run Kerala trips for over a decade for travelers from Chennai, Bangalore, Coimbatore, and Nagercoil. Our Kerala specialists know which Munnar properties have unobstructed valley views and which don\'t, which Alleppey houseboats are genuinely maintained and which trade on old reviews, and which Thekkady spice walk is run by an actual plantation family. We build the circuit, pre-book the houseboat, hold the Ayurveda slot, and give you one contact from departure to return.',
      },
    ],
  },
}
