import type {
  TrustBadge, Package, ItineraryDay, HotelTier,
  MonthRating, Season, FAQ, Testimonial, RelatedDestination,
  Experience, WhatsAppConfig, ProcessStep, DestinationTheme, LeadFormConfig
} from '@/lib/shared/types'

export const andamanData = {
  meta: {
    title: 'Premium Andaman Tour Packages — Honeymoon, Family & Scuba | Outbound Travelers',
    description: 'Book customizable premium Andaman & Nicobar tour packages. Experience Radhanagar Beach sunsets, private island hopping, bioluminescent scuba diving, and Taj Exotica luxury. Crafted for modern luxury.',
    canonical: 'https://www.outboundtravelers.com/andaman',
    ogImage: '/images/andaman/og-image.jpg',
    h1: 'Andaman & Nicobar Islands — Floating Tropical Luxury',
  },
  theme: {
    accentColor: '#0891B2', // Lagoon Cyan
    accentSoft: '#ECFEFF', // Aqua Mist
    motif: 'jellyfish-wave',
  } as DestinationTheme,
  hero: {
    headline: 'Turquoise Serenity. Secluded Luxury.',
    subheadline: 'Enter a floating tropical paradise where ancient mahogany forests sweep down to powder-white sands. Outbound Travelers crafts highly bespoke, unhurried, editorial island journeys for discerning travelers.',
    primaryCta: 'Curate My Island Escape',
    secondaryCta: 'Speak to an Andaman Specialist',
    desktopImage: '/images/andaman/hero-desktop.jpg',
    mobileImage: '/images/andaman/hero-mobile.jpg',
    imageAlt: 'Pristine Radhanagar beach with turquoise waves and lush green forest canopy under sunset light, Havelock Island, Andaman',
  },
  trustBadges: [
    { icon: 'island', label: 'Vetted private speedboats' },
    { icon: 'custom', label: '100% personalized pacing' },
    { icon: 'scuba', label: 'PADI-certified diving experts' },
    { icon: 'support', label: '24/7 dedicated on-trip concierge' },
    { icon: 'hotel', label: 'Palace & luxury villa retreats' },
    { icon: 'member', label: 'TAFI/IATA member agency' },
  ] as TrustBadge[],
  quickSummary: {
    duration: '5–6 nights ideal',
    bestSeason: 'September–May (Vibrant skies & calm waters)',
    startingFrom: 'From ₹48,500 per couple',
    tripTypes: 'Lagoon Honeymoon · Multi-Gen Family · Bioluminescent Diving · Quiet Retreats',
  },
  whyVisit: [
    {
      icon: 'seclusion',
      title: 'Untouched Island Seclusion',
      description: 'Find real tranquility. Skip crowded mainland shores and lounge on beaches regularly voted among the finest and cleanest in Asia.',
    },
    {
      icon: 'scuba',
      title: 'Bioluminescent Scuba diving',
      description: 'Explore the world\'s most vibrant coral reefs. Dive under the stars to witness glowing bioluminescent plankton shifting around your fingers.',
    },
    {
      icon: 'heritage',
      title: 'Deep Maritime Heritage',
      description: 'Witness history illuminated. Roam the quiet gallows of Cellular Jail and stroll under centuries-old roots at Ross Island.',
    },
    {
      icon: 'seafood',
      title: 'Fresh Island Gastronomy',
      description: 'Indulge in coconut seafood curries, freshly baked lagoon lobsters, and bespoke sunset dinners right on the sand.',
    },
  ],
  experiences: [
    {
      id: 'radhanagar-sunrise',
      title: 'Sunrise at Radhanagar Beach',
      description: 'Walk hand‑in‑hand on powdery white sand as the golden tropical sun rises above calm, glassy turquoise waters.',
      image: '/images/andaman/exp-radhanagar.jpg',
      alt: 'Radhanagar beach sunrise Havelock island',
      seasonal: false,
    },
    {
      id: 'private-snorkel',
      title: 'Private Snorkel with a Guide',
      description: 'Discover pristine coral gardens in complete privacy, guided by a certified marine biologist showing you hidden sea life.',
      image: '/images/andaman/exp-snorkel.jpg',
      alt: 'Private snorkeling tour coral reef',
      seasonal: false,
    },
    {
      id: 'cellular-jail',
      title: 'Cellular Jail Night Tour',
      description: 'Roam through historical stone cells illuminated under amber lanterns, listening to moving stories of India\'s freedom struggle.',
      image: '/images/andaman/exp-jail.jpg',
      alt: 'Cellular jail light show Port Blair',
      seasonal: false,
    },
    {
      id: 'yacht-cruise',
      title: 'Island‑hopping Yacht Cruise',
      description: 'Sail the Andaman Sea on a luxurious private yacht. Stop at empty sandbars for swims and sip cold coconut water on deck.',
      image: '/images/andaman/exp-yacht.jpg',
      alt: 'Private yacht charter Havelock island',
      seasonal: false,
    },
    {
      id: 'sunset-shoot',
      title: 'Sunset Photoshoot',
      description: 'A professional photographer captures high-end, editorial portrait memories of you against fiery magenta-orange sunset skies.',
      image: '/images/andaman/exp-photoshoot.jpg',
      alt: 'Honeymoon couple sunset photoshoot beach',
      seasonal: false,
    },
    {
      id: 'night-scuba',
      title: 'Night Scuba Dive',
      description: 'Plunge into black waters at night to experience marine bioluminescence. Move your hands to trigger clouds of glowing starlight.',
      image: '/images/andaman/exp-scuba.jpg',
      alt: 'Night scuba diving bioluminescent plankton',
      seasonal: false,
    },
  ] as Experience[],
  packages: [
    {
      id: 'honeymoon-classic',
      name: 'Andaman Honeymoon Classic',
      duration: '5 Nights / 6 Days',
      idealFor: 'Newlyweds seeking romantic tropical isolation and premium beach villa stays.',
      highlights: ['Port Blair 1N · Havelock 3N · Neil 1N', 'Beachfront Candlelit Sea Dinner', 'Sunset Beach Editorial Photoshoot', 'Premium Makruzz Ferry crossings', 'Bespoke floral bed decorations'],
      price: 'From ₹58,500 per couple',
      image: '/images/andaman/pkg-honeymoon.jpg',
      alt: 'Andaman luxury honeymoon package',
      whatsappMessage: 'Hi Outbound Travelers, I am interested in the Andaman Honeymoon Classic 5N/6D package. Please share details and custom options.',
      seasonal: false,
    },
    {
      id: 'family-tour',
      name: 'Andaman Premium Family Tour',
      duration: '6 Nights / 7 Days',
      idealFor: 'Families looking for safe beach activities, heritage tours, and unhurried schedules.',
      highlights: ['Port Blair 2N · Havelock 2N · Neil 1N · PB 1N', 'Cellular Jail light & sound VIP seats', 'Glass-bottom boat tour with kids', 'Private Toyota Innova for all islands', 'Vetted child-friendly sea resorts'],
      price: 'From ₹64,500 per person',
      image: '/images/andaman/pkg-family.jpg',
      alt: 'Andaman family tour package',
      whatsappMessage: 'Hi Outbound Travelers, I am interested in the Andaman Premium Family Tour 6N/7D package. Please share the details.',
      seasonal: false,
    },
    {
      id: 'scuba-special',
      name: 'Andaman Scuba Explorer',
      duration: '6 Nights / 7 Days',
      idealFor: 'Adventure seekers, marine enthusiasts, and solo travelers wanting certified diving.',
      highlights: ['Havelock Island 4N · Port Blair 2N', 'PADI Open Water certification program', '4 custom deep reef diving excursions', 'All high-end diving equipment included', 'Underwater GoPro photo packages'],
      price: 'From ₹72,000 per person',
      image: '/images/andaman/pkg-scuba.jpg',
      alt: 'Andaman scuba diving special package',
      whatsappMessage: 'Hi Outbound Travelers, please send info about the Andaman Scuba Explorer 6N/7D package.',
      seasonal: false,
    },
    {
      id: 'quick-honeymoon',
      name: 'Andaman Quick Honeymoon',
      duration: '4 Nights / 5 Days',
      idealFor: 'Couples wanting a brief, high-end tropical island break.',
      highlights: ['Port Blair 1N · Havelock 3N', 'Private sunset yacht rental', 'Radhanagar beach dinner', 'Toyota Crysta premium transfers'],
      price: 'From ₹48,500 per couple',
      image: '/images/andaman/pkg-quick.jpg',
      alt: 'Andaman short honeymoon getaway',
      whatsappMessage: 'Hi Outbound Travelers, I am interested in the Andaman Quick Honeymoon 4N/5D package.',
      seasonal: false,
    },
    {
      id: 'luxury-escape',
      name: 'Andaman Ultimate Luxury Escape',
      duration: '7 Nights / 8 Days',
      idealFor: 'Luxury seekers wishing for ultimate five-star indulgence and quiet privacy.',
      highlights: ['Taj Exotica Resort & Spa Havelock 4N', 'Private helicopter island transfer options', 'Exclusive custom speedboats', 'Bespoke candlelight dining under the stars', 'Personal 24/7 royal concierge guide'],
      price: 'From ₹1,85,000 per couple',
      image: '/images/andaman/pkg-luxury.jpg',
      alt: 'Andaman five-star luxury escape Taj Exotica',
      whatsappMessage: 'Hi Outbound Travelers, tell me more about the Andaman Ultimate Luxury Escape 7N/8D. Please share options.',
      seasonal: false,
    },
  ] as Package[],
  itinerary: [
    {
      day: 1,
      title: 'Arrive in the Gateway – Historical Port Blair',
      description: 'Land in Port Blair where your private executive chauffeur meets you. Check-in to your sea-facing luxury resort. In the late afternoon, take a private guided walk through Cellular Jail, finishing with VIP seats at the sound & light historical show.',
      highlights: ['Airport private welcome', 'Luxury check-in', 'Cellular Jail private tour', 'Light & Sound show'],
      stay: 'Port Blair Luxury Resort (e.g. Taj / Sentinel)',
    },
    {
      day: 2,
      title: 'Ferry to Paradise – Swaraj Dweep (Havelock)',
      description: 'Board the premium Makruzz air-conditioned cruise ferry to Havelock Island. Watch the water shift from deep blue to bright cyan. Check-in to your beachfront villa. Spend the evening walking the soft sand of Radhanagar Beach (Asia\'s cleanest beach) under an orange sunset.',
      highlights: ['Premium Makruzz cruise', 'Havelock island welcome', 'Radhanagar beach walk', 'Private beachfront sunset relaxation'],
      stay: 'Havelock Beachfront Resort (e.g. Taj Exotica / Barefoot)',
    },
    {
      day: 3,
      title: 'Underwater Marvels – Scuba Discovery & Lagoon Snorkel',
      description: 'Plunge into warm waters for an introductory scuba dive or guided coral garden snorkeling. Explore massive brain corals and meet sea turtles, clownfish, and rays. Afternoon at leisure for premium resort spa therapies.',
      highlights: ['PADI instructor dive', 'Vibrant coral reef exploration', 'Bespoke underwater photos', 'Premium spa relaxation'],
      stay: 'Havelock Beachfront Resort',
    },
    {
      day: 4,
      title: 'Private Yacht Cruise & Candlelit Sandy Dinner',
      description: 'Charter a luxury catamaran yacht to hop between secret uninhabited sandbars. Swim in pristine isolated pools. At dusk, return to a private table set on Havelock beach under lanterns, enjoying a gourmet seafood grill with the ocean at your feet.',
      highlights: ['Private yacht charter', 'Sandbar swimming', 'Gourmet beachfront dining', 'Exclusive butler service'],
      stay: 'Havelock Beachfront Resort',
    },
    {
      day: 5,
      title: 'Relaxed Island Rhythm – Neil Island (Shaheed Dweep)',
      description: 'Take a mid-day speedboat to Neil Island, known for its slow pace, farming communities, and natural rock formations. Witness the majestic natural bridge and catch the sunset at Laxmanpur Beach before checking into a quiet boutique resort.',
      highlights: ['Speedboat to Neil Island', 'Natural Bridge hike', 'Laxmanpur beach sunset', 'Boutique eco-resort stay'],
      stay: 'Neil Island Boutique Eco-Resort',
    },
    {
      day: 6,
      title: 'Sunset Departure – Return to Port Blair',
      description: 'Enjoy a leisurely tropical breakfast in Neil before boarding the return cruise to Port Blair. Spend the afternoon browsing local woodcrafts and checking out Ross Island\'s colonial ruins. Dine at a premium rooftop harbor restaurant.',
      highlights: ['Morning beach leisure', 'Return cruise ferry', 'Ross Island heritage tour', 'Rooftop harbor dinner'],
      stay: 'Port Blair Luxury Hotel',
    },
    {
      day: 7,
      title: 'Farewell Islands – Departure Home',
      description: 'Your private chauffeur transfers you to Veer Savarkar International Airport in Port Blair for your direct flight home, carrying stunning memories of floating tropical luxury.',
      highlights: ['Gourmet local breakfast', 'Airport transfer assistance', 'Direct flight home'],
      stay: 'Departure flight home',
    },
  ] as ItineraryDay[],
  hotelTiers: [
    { tier: 'Comfort Stays', description: 'Highly-rated, clean boutique properties like Hotel Sentinel or Coral View Inn with local breakfasts and pool access.', price: 'Included in Base Cost' },
    { tier: 'Premium Resorts', description: 'Midscale luxury beach resorts like Oceanic Retreat or Sea Breeze Lodge offering spacious wooden cottages and private beach strips.', price: 'Upgrade Option (+₹18,500/person)' },
    { tier: 'Ultimate Luxury', description: 'Five-star flagship resorts like Taj Exotica Resort & Spa or Alila Havelock with private beachfront plunge villas, butler services, and private speedboats.', price: 'Luxury Upgrade (+₹85,000/person)' },
  ] as HotelTier[],
  months: [
    { month: 'Jan', rating: 'best', note: 'Unbelievably clear water, dry sunny days, perfect diving.' },
    { month: 'Feb', rating: 'best', note: 'Calm glassy seas, pleasant sea breeze, great sunset shots.' },
    { month: 'Mar', rating: 'best', note: 'Superb visibility under the water, minimal rain, warm.' },
    { month: 'Apr', rating: 'best', note: 'Glassy lagoons, excellent deal pricing before summer.' },
    { month: 'May', rating: 'good', note: 'Warm sunny days, mild evening clouds, low crowd density.' },
    { month: 'Jun', rating: 'okay', note: 'Monsoon showers start, lush green islands, dramatic sky.' },
    { month: 'Jul', rating: 'okay', note: 'Showers are common, great resort deals, rich tropical vibe.' },
    { month: 'Aug', rating: 'good', note: 'Rains ease off, great waterfalls active, fresh air.' },
    { month: 'Sep', rating: 'best', note: 'Beautiful post-monsoon weather, glassy waters start, dry.' },
    { month: 'Oct', rating: 'best', note: 'Very pleasant, all scuba programs fully active, booking essential.' },
    { month: 'Nov', rating: 'best', note: 'Peak season begins, vibrant light, ideal water temperature.' },
    { month: 'Dec', rating: 'best', note: 'Grand festive lights on beaches, fireworks, fully booked.' },
  ] as MonthRating[],
  seasons: [
    { id: 'glassy-calm', label: 'Glassy Calm Peak', months: 'Nov–Apr', description: 'Ultimate visibility for scuba, glassy blue lagoons, and perfect warm sunshine.', image: '/images/andaman/season-peak.jpg' },
    { id: 'green-monsoon', label: 'Lush Green Monsoon', months: 'Jun–Aug', description: 'Brief heavy showers, incredibly thick green rainforests, and empty beaches.', image: '/images/andaman/season-monsoon.jpg' },
    { id: 'tropical-trans', label: 'Tropical Autumn', months: 'Sep–Oct', description: 'Calm winds return, all maritime activities resume, wonderful weather.', image: '/images/andaman/season-autumn.jpg' },
  ] as Season[],
  process: [
    { step: 1, title: 'Personalized Consult', description: 'Tell us your preferred dates, group size, and dietary choices. Our island designer hosts a call.' },
    { step: 2, title: 'Tailored Island Blueprint', description: 'Receive an optimized day-wise island schedule including premium private ferries and transfers.' },
    { step: 3, title: 'Refining Stays & Dives', description: 'Choose your hotel tiers, add PADI dive packages or yacht charters, and customize your meals.' },
    { step: 4, title: 'Seamless Voyage', description: 'Arrive stress-free. Our on-ground hosts manage all baggage, ferries, and private vehicle transits.' },
  ] as ProcessStep[],
  inclusions: [
    '5 or 6 nights stay at choice beachfront hotels and private villas',
    'Daily elaborate gourmet breakfast buffet featuring Indian and Western specialties',
    'All inter-island speedboats and premium Makruzz cruise ferry tickets pre-booked',
    'All private transits in air-conditioned Toyota Crysta / Innova vehicles',
    'Private certified guide for Cellular Jail and Ross Island history walks',
    '1 beach candlelit multi-course dinner with private butler service',
    'Professional couple sunset photoshoot on Radhanagar Beach',
    'Introduction to Scuba Diving session with professional PADI instructor',
    '24/7 dedicated local WhatsApp ground concierge hotline',
    'All harbor entries, parking, and forest department permit charges',
  ],
  exclusions: [
    'International or domestic flight tickets to Port Blair',
    'Additional scuba diving certification packages (can be pre-added)',
    'Optional adventure tickets like sea-walks or helicopter rides',
    'Lunches and dinners not listed in inclusions (fine dining guides provided)',
    'Driver and local guide tips',
  ],
  gallery: [
    { image: '/images/andaman/gallery-01.jpg', alt: 'Radhanagar beach white sands Havelock' },
    { image: '/images/andaman/gallery-02.jpg', alt: 'Scuba diver swimming with sea turtle' },
    { image: '/images/andaman/gallery-03.jpg', alt: 'Beachfront candlelit dinner setting' },
    { image: '/images/andaman/gallery-04.jpg', alt: 'Makruzz cruise ferry sailing on cyan water' },
    { image: '/images/andaman/gallery-05.jpg', alt: 'Laxmanpur beach natural rock bridge Neil island' },
    { image: '/images/andaman/gallery-06.jpg', alt: 'Professional couple photoshoot on sunset beach' },
  ],
  testimonials: [
    {
      name: 'Pavan & Meera',
      city: 'Hyderabad',
      tripType: 'Lagoon Honeymoon',
      quote: 'Andaman felt like an untouched private Eden. The private sunset catamaran cruise and candlelit dinner on Havelock beach arranged by Outbound Travelers were absolute magic. Spotless service!',
      rating: 5,
      date: 'April 2026',
      photo: '/images/testimonials/pavan-meera.jpg',
    },
    {
      name: 'The Iyer Family',
      city: 'Chennai',
      tripType: 'Multi-Generation Family',
      quote: 'We traveled with two toddlers and senior citizens. The Outbound team handled our private Toyota Crysta transits and baggage at ferry terminals flawlessly. Outstanding child-safe beach resorts!',
      rating: 5,
      date: 'March 2026',
      photo: '/images/testimonials/iyer-family.jpg',
    },
    {
      name: 'Karthik',
      city: 'Bangalore',
      tripType: 'Solo Scuba Explorer',
      quote: 'The Scuba Explorer package is stellar. Got my PADI certification under world-class instructors. Plunging into deep night dives with glowing bioluminescence was a life-changing experience.',
      rating: 5,
      date: 'May 2026',
      photo: '/images/testimonials/karthik.jpg',
    },
  ] as Testimonial[],
  faqs: [
    {
      q: 'When is the absolute best time to visit Andaman?',
      a: 'The peak travel window is September to May. During these months, the seas are extremely calm, rainfall is minimal, and underwater visibility is at its absolute peak (up to 20–30 meters) which is perfect for scuba diving.',
    },
    {
      q: 'Do Indian passport holders need a visa or permit?',
      a: 'Indian passport holders do not require any visa or special permit to visit Port Blair, Havelock, or Neil. You only need standard government-issued photo IDs (Aadhaar/Driver\'s license). Foreign passport holders require an e-visa and a restricted area permit (RAP).',
    },
    {
      q: 'Are flight bookings included in the package?',
      a: 'Our base package rates exclude flight tickets, but our flight desk can secure consolidator booking rates (typically 5–10% cheaper than commercial portals) from Chennai, Bangalore, Kochi, and Hyderabad directly to Port Blair.',
    },
    {
      q: 'How safe is scuba diving for non-swimmers and beginners?',
      a: 'Extremely safe. Our intro scuba sessions are guided on a 1-on-1 ratio by fully certified PADI instructors. You do not need to know how to swim to experience basic recreational diving.',
    },
    {
      q: 'Can we customize the day-wise itinerary?',
      a: 'Yes, 100%. Every itinerary is custom-crafted. You can add extra days in Havelock, upgrade to water villas, pre-schedule deep dives, or structure longer afternoon gaps for a relaxed, slow honeymoon pacing.',
    },
  ] as FAQ[],
  relatedDestinations: [
    { name: 'Sikkim Tour', image: '/images/sikkim/hero.jpg', href: '/sikkim' },
    { name: 'Meghalaya Tour', image: '/images/meghalaya/hero.jpg', href: '/meghalaya' },
    { name: 'Malaysia Escape', image: '/images/malaysia/hero.jpg', href: '/malaysia' },
    { name: 'Langkawi Sanctuary', image: '/images/langkawi/hero.jpg', href: '/langkawi' },
  ] as RelatedDestination[],
  whatsapp: {
    number: '919876543210',
    heroMessage: 'Hi Outbound Travelers, I am interested in a premium Andaman tour package. Please share customized itineraries and quotes.',
    stickyMessage: 'Hi Outbound Travelers, I am planning an Andaman trip. Can you help me plan and estimate costs?',
    floaterMessage: 'Hi Outbound Travelers, I\'m interested in an Andaman package. Please share details on customized honeymoon/scuba trips.',
    finalCtaMessage: 'Hi Outbound Travelers, I\'m ready to plan my Andaman trip. Please send me your best itinerary and a custom quote.',
    postFormMessage: 'Hi Outbound Travelers, I just submitted my Andaman enquiry. Travel month: {month}, {travelers} travelers from {city}, trip type: {tripType}. Looking forward to the customized island blueprint.',
  } as WhatsAppConfig,
  leadForm: {
    title: 'Curate your Andaman Escape',
    subtitle: 'Step into tropical luxury. Let our island architects design your premium custom Andaman itinerary in under 2 hours.',
    submitButtonText: 'Get my Andaman quote',
    successMessage: 'Splendid! Your Andaman specialist is crafting your floating tropical blueprint and will WhatsApp you within 2 hours. Meanwhile, save our number: +91-98765-43210.',
    destinationId: 'andaman',
    destinationName: 'Andaman & Nicobar',
  } as LeadFormConfig,
  seoContent: {
    h2: 'Crafting Your Premium Andaman Getaway with Outbound Travelers',
    sections: [
      {
        h3: 'Why Swaraj Dweep (Havelock) is the ultimate romantic escape',
        body: 'Havelock Island is engineered to offer pure isolation. For honeymooners, the transition from busy mainland cities to the quiet beach bungalows of Havelock is remarkably serene. With pristine, powder-white sandy beaches, private butler dining under hanging lanterns, and premium private cruise connections (Makruzz), it provides a stunning, high-end tropical island sanctuary that easily rivals global counterparts like Mauritius or Fiji.',
      },
      {
        h3: 'Custom adjustments for multi-generation family groups',
        body: 'Unlike standard operators who pack exhausting schedules, we custom-pace our journeys. Families traveling with toddlers or elderly relatives receive dedicated luxury vehicles on each island, and we secure child-safe, vetted beach resorts with pools and flat beach walkways. We pre-book premium air-conditioned ferry seats and arrange on-ground baggage handling, so your family never has to carry heavy luggage or wait in warm terminals.',
      },
    ],
  },
}
