import type {
  TrustBadge, Package, ItineraryDay, HotelTier,
  MonthRating, Season, FAQ, Testimonial, RelatedDestination,
  Experience, WhatsAppConfig, ProcessStep, DestinationTheme, LeadFormConfig
} from '@/lib/shared/types'

export const baliData = {
  meta: {
    title: 'Bali Tour Packages — Customizable Honeymoon & Family Trips | Outbound Travelers',
    description: 'Plan your Bali trip with Outbound Travelers. Honeymoon, family & group packages with flights, hotels, transfers. Get a lightning-fast custom quote today.',
    canonical: 'https://www.outboundtravelers.com/bali',
    ogImage: 'https://picsum.photos/seed/bali-og/1200/630',
    h1: 'Bali Tour Packages — Crafted Trips to the Island of Gods',
  },
  theme: {
    accentColor: '#D97706',
    accentSoft: '#FEF3C7',
    motif: 'frangipani',
  } as DestinationTheme,
  hero: {
    headline: 'Bali, Designed Around You',
    subheadline: 'Honeymoon, family, and group trips to the Island of Gods — fully customizable, expert-planned, with end-to-end support from Bali specialists.',
    primaryCta: 'Get my Bali quote',
    secondaryCta: 'Or talk to a travel expert on WhatsApp',
    desktopImage: 'https://picsum.photos/seed/bali-hero-d/1920/1080',
    mobileImage: 'https://picsum.photos/seed/bali-hero-m/800/1200',
    imageAlt: 'Rice terraces in Ubud Bali at sunrise with morning mist',
  },
  trustBadges: [
    { icon: 'trips', label: '2,500+ trips delivered' },
    { icon: 'custom', label: '100% customizable' },
    { icon: 'verified', label: 'Verified villas' },
    { icon: 'support', label: '24/7 on-trip support' },
    { icon: 'quote', label: 'Lightning quotes' },
    { icon: 'member', label: 'TAFI/IATA member' },
  ] as TrustBadge[],
  quickSummary: {
    duration: '5–7 nights ideal',
    bestSeason: 'April–October (Dry Season)',
    startingFrom: 'From ₹[TBD] per person',
    tripTypes: 'Honeymoon · Family · Group · Luxury',
  },
  whyVisit: [
    {
      icon: 'specialist',
      title: 'Crafted, not templated',
      description: 'Every Bali itinerary we build is around your pace, your group, and your travel style — no fixed group departures, no compromise on quality.',
    },
    {
      icon: 'verified',
      title: 'Verified villas and resorts',
      description: 'Every villa, resort, and experience provider is vetted by our team. You get a real person on WhatsApp through your entire trip.',
    },
    {
      icon: 'southindia',
      title: 'South India to Bali, sorted',
      description: 'Flights from Chennai, Bangalore, Kochi, Hyderabad, with visa-on-arrival guidance and South Indian food arrangements on request.',
    },
  ],
  experiences: [
    { id: 'rice-terraces', title: 'Tegallalang Rice Terraces', description: 'Walk the ancient subak irrigation terraces at golden hour. The most photographed landscape in Bali — best before 9am when the light is soft and the crowds are thin.', image: 'https://picsum.photos/seed/rice-terraces/800/600', alt: 'Tegallalang rice terraces Ubud Bali at sunrise', seasonal: false },
    { id: 'temple-uluwatu', title: 'Uluwatu Temple at Sunset', description: 'Clifftop sea temple perched 70 metres above the Indian Ocean. Watch the Kecak fire dance as the sun drops behind the temple silhouette.', image: 'https://picsum.photos/seed/uluwatu/800/600', alt: 'Uluwatu temple cliff sunset Bali Kecak dance', seasonal: false },
    { id: 'ubud-culture', title: 'Ubud Arts & Culture Trail', description: 'Monkey Forest, Ubud Palace, traditional painter villages, silver workshops, and a cooking class in one full cultural day.', image: 'https://picsum.photos/seed/ubud/800/600', alt: 'Ubud cultural trail Bali monkey forest palace', seasonal: false },
    { id: 'seminyak-beach', title: 'Seminyak & Canggu Beaches', description: 'Bali\'s most sophisticated beach strip — boutique beach clubs, world-class surf breaks at sunset, and the best beachfront dining on the island.', image: 'https://picsum.photos/seed/seminyak/800/600', alt: 'Seminyak beach sunset Bali beach club', seasonal: false },
    { id: 'mount-batur', title: 'Mount Batur Sunrise Trek', description: 'Pre-dawn climb to Bali\'s active volcano summit for a sunrise above the clouds. Two hours up, breakfast at the crater rim, stunning caldera views.', image: 'https://picsum.photos/seed/batur/800/600', alt: 'Mount Batur sunrise trek Bali volcano caldera', seasonal: false },
    { id: 'nusa-penida', title: 'Nusa Penida Island Day Trip', description: 'Kelingking Beach cliff views, Angel\'s Billabong natural pool, Broken Beach arch, and crystal-clear snorkelling water — all in one island escape.', image: 'https://picsum.photos/seed/nusapenida/800/600', alt: 'Nusa Penida Kelingking Beach cliff view Bali', seasonal: false },
  ] as Experience[],
  packages: [
    {
      id: 'bali-classic',
      name: 'Bali Classic',
      duration: '5 Nights / 6 Days',
      idealFor: 'First-time visitors, Friend groups',
      highlights: ['Ubud 2N', 'Seminyak 2N', 'Nusa Penida day trip'],
      price: 'From ₹[TBD] per person',
      image: 'https://picsum.photos/seed/bali-pkg1/800/600',
      alt: 'Bali classic tour package Ubud Seminyak',
      whatsappMessage: 'Hi Outbound Travelers, I\'d like to know more about the Bali Classic 5N/6D package. Please share details and customization options.',
      seasonal: false,
    },
    {
      id: 'bali-honeymoon',
      name: 'Bali Honeymoon Special',
      duration: '6 Nights / 7 Days',
      idealFor: 'Newly-married couples, Anniversary trips',
      highlights: ['Private pool villa', 'Couples spa', 'Sunset dinner Jimbaran'],
      price: 'From ₹[TBD] per couple',
      image: 'https://picsum.photos/seed/bali-pkg2/800/600',
      alt: 'Bali honeymoon special private pool villa',
      whatsappMessage: 'Hi Outbound Travelers, I\'d like to know more about the Bali Honeymoon Special 6N/7D. Please share details and customization options.',
      seasonal: false,
    },
    {
      id: 'bali-family',
      name: 'Bali Family Deluxe',
      duration: '6 Nights / 7 Days',
      idealFor: 'Families with kids, Multi-gen travel',
      highlights: ['Ubud 2N', 'Seminyak 2N', 'Nusa Dua 2N', 'Water park'],
      price: 'From ₹[TBD] per person',
      image: 'https://picsum.photos/seed/bali-pkg3/800/600',
      alt: 'Bali family deluxe package kids friendly',
      whatsappMessage: 'Hi Outbound Travelers, I\'d like to know more about the Bali Family Deluxe 6N/7D package. Please share details and customization options.',
      seasonal: false,
    },
    {
      id: 'bali-luxury',
      name: 'Bali Luxury Escape',
      duration: '7 Nights / 8 Days',
      idealFor: 'Luxury travelers, Couples',
      highlights: ['5★ cliff resort', 'Private chef dinner', 'Helicopter sunrise'],
      price: 'From ₹[TBD] per person',
      image: 'https://picsum.photos/seed/bali-pkg4/800/600',
      alt: 'Bali luxury escape cliff resort private villa',
      whatsappMessage: 'Hi Outbound Travelers, I\'d like to know more about the Bali Luxury Escape 7N/8D. Please share details and customization options.',
      seasonal: false,
    },
    {
      id: 'bali-adventure',
      name: 'Bali Adventure & Surf',
      duration: '6 Nights / 7 Days',
      idealFor: 'Adventure seekers, Friend groups',
      highlights: ['Mount Batur trek', 'White water rafting', 'Surf lessons Canggu'],
      price: 'From ₹[TBD] per person',
      image: 'https://picsum.photos/seed/bali-pkg5/800/600',
      alt: 'Bali adventure surf package Mount Batur trek',
      whatsappMessage: 'Hi Outbound Travelers, I\'d like to know more about the Bali Adventure & Surf 6N/7D package. Please share details and customization options.',
      seasonal: false,
    },
  ] as Package[],
  itinerary: [
    { day: 1, title: 'Arrive Bali — Ubud Welcome', description: 'Airport pickup, transfer to Ubud. Check-in to rice terrace-view hotel. Evening walk through Ubud town, dinner at a local warung.', highlights: ['Airport pickup', 'Ubud check-in', 'Evening market walk'], stay: 'Ubud' },
    { day: 2, title: 'Ubud Culture & Nature Day', description: 'Tegallalang Rice Terraces at sunrise, Monkey Forest, Ubud Palace, Blanco Renaissance Museum, traditional painter village at Mas.', highlights: ['Tegallalang at sunrise', 'Monkey Forest', 'Ubud Palace'], stay: 'Ubud' },
    { day: 3, title: 'Nusa Penida Island Day Trip', description: 'Full-day boat trip to Nusa Penida. Kelingking Beach viewpoint, Angel\'s Billabong, Broken Beach, Crystal Bay snorkelling. Return by evening.', highlights: ['Kelingking viewpoint', 'Angel\'s Billabong', 'Crystal Bay snorkel'], stay: 'Ubud' },
    { day: 4, title: 'Ubud to Seminyak — Beach Transfer', description: 'Morning cooking class in Ubud. After lunch transfer to Seminyak. Sunset at La Plancha beach bar. First evening on Bali\'s west coast.', highlights: ['Cooking class', 'Seminyak check-in', 'La Plancha sunset'], stay: 'Seminyak' },
    { day: 5, title: 'Seminyak & Uluwatu', description: 'Morning beach time. Afternoon drive to Uluwatu Temple. Kecak fire dance at sunset. Dinner at Jimbaran seafood on the beach.', highlights: ['Uluwatu temple', 'Kecak fire dance', 'Jimbaran seafood dinner'], stay: 'Seminyak' },
    { day: 6, title: 'Canggu & Free Day', description: 'Morning surf lesson at Canggu beach. Brunch at a trendy café. Rest of the day free for spa, shopping, or beach clubs. Farewell dinner.', highlights: ['Surf lesson Canggu', 'Beach club afternoon', 'Farewell dinner'], stay: 'Seminyak' },
    { day: 7, title: 'Departure', description: 'Breakfast and airport transfer. Optional last morning at the beach or spa.', highlights: ['Late checkout optional', 'Hotel checkout', 'Airport transfer'], stay: 'Departure' },
  ] as ItineraryDay[],
  hotelTiers: [
    { tier: '3★ Comfort', description: 'Clean guesthouses and mid-range hotels in Ubud and Seminyak with pool access and daily breakfast.', price: 'From ₹[TBD] per night' },
    { tier: '4★ Premium', description: 'Boutique resorts and villas with private or semi-private pools, spa access, and full amenities.', price: 'From ₹[TBD] per night' },
    { tier: '5★ Luxury', description: 'Cliff-edge resorts, jungle infinity pools, butler service, and the finest dining in Bali.', price: 'From ₹[TBD] per night' },
    { tier: 'Private Pool Villa', description: 'Standalone villas with private plunge pools, open-air living, and personal staff — the definitive Bali honeymoon stay.', price: 'From ₹[TBD] per night' },
  ] as HotelTier[],
  months: [
    { month: 'Jan', rating: 'okay', note: 'Wet season, lush green but frequent rain.' },
    { month: 'Feb', rating: 'okay', note: 'Still wet season, fewer crowds.' },
    { month: 'Mar', rating: 'good', note: 'Rain reducing, good deals available.' },
    { month: 'Apr', rating: 'best', note: 'Dry season begins, ideal weather starts.' },
    { month: 'May', rating: 'best', note: 'Perfect weather, less crowded than peak.' },
    { month: 'Jun', rating: 'best', note: 'Dry, warm, great for all activities.' },
    { month: 'Jul', rating: 'best', note: 'Peak season, book early.' },
    { month: 'Aug', rating: 'best', note: 'Peak season, best beach weather.' },
    { month: 'Sep', rating: 'best', note: 'Still dry, crowds thinning after peak.' },
    { month: 'Oct', rating: 'good', note: 'Transitional, occasional showers.' },
    { month: 'Nov', rating: 'okay', note: 'Wet season approaching.' },
    { month: 'Dec', rating: 'good', note: 'Festive season, rain but festive atmosphere.' },
  ] as MonthRating[],
  seasons: [
    { id: 'dry', label: 'Dry Season', months: 'Apr–Oct', description: 'Best time to visit. Clear skies, low humidity, perfect for beaches and trekking.', image: 'https://picsum.photos/seed/bali-dry/800/600' },
    { id: 'shoulder', label: 'Shoulder Season', months: 'Mar & Nov', description: 'Good deals, fewer crowds. Occasional afternoon showers but mostly pleasant.', image: 'https://picsum.photos/seed/bali-shoulder/800/600' },
    { id: 'wet', label: 'Wet Season', months: 'Dec–Feb', description: 'Lush green Bali. Rain mostly in afternoons. Cultural festivals and lower prices.', image: 'https://picsum.photos/seed/bali-wet/800/600' },
    { id: 'peak', label: 'Peak Season', months: 'Jul–Aug', description: 'School holidays bring families worldwide. Book villas and flights 60+ days early.', image: 'https://picsum.photos/seed/bali-peak/800/600' },
  ] as Season[],
  process: [
    { step: 1, title: 'Share your dates', description: 'WhatsApp or form — send us your travel month, group size, departure city.' },
    { step: 2, title: 'Get a custom itinerary', description: 'A Bali specialist sends a day-wise plan plus transparent quote within 2 hours.' },
    { step: 3, title: 'Refine until it\'s right', description: 'Swap hotels, change pace, add experiences. We iterate till it\'s yours.' },
    { step: 4, title: 'Travel with full support', description: 'One team handles airport pickup to drop. Your consultant stays reachable through your trip.' },
  ] as ProcessStep[],
  inclusions: [
    'Accommodation per chosen tier',
    'Daily breakfast and meals per package',
    'Airport pickup and drop in Bali (Ngurah Rai)',
    'All sightseeing transfers in private AC vehicle',
    'English-speaking driver-guide',
    'Nusa Penida boat trip and snorkelling gear',
    'All applicable tolls and parking',
    'GST and service taxes',
  ],
  exclusions: [
    'Flights to Bali (can be booked on request)',
    'Visa on arrival fees (approx USD 35)',
    'Temple entrance fees and activity tickets',
    'Personal expenses, tips, minibar',
    'Travel insurance (recommended, can be added)',
    'Anything not explicitly in inclusions',
  ],
  gallery: [
    { image: 'https://picsum.photos/seed/bali-g1/800/600', alt: 'Tegallalang rice terraces Ubud Bali sunrise' },
    { image: 'https://picsum.photos/seed/bali-g2/800/600', alt: 'Uluwatu temple cliff sunset Bali' },
    { image: 'https://picsum.photos/seed/bali-g3/800/600', alt: 'Private pool villa Bali honeymoon' },
    { image: 'https://picsum.photos/seed/bali-g4/800/600', alt: 'Nusa Penida Kelingking Beach cliff Bali' },
    { image: 'https://picsum.photos/seed/bali-g5/800/600', alt: 'Seminyak beach sunset Bali beach club' },
    { image: 'https://picsum.photos/seed/bali-g6/800/600', alt: 'Mount Batur sunrise trek active volcano Bali' },
    { image: 'https://picsum.photos/seed/bali-g7/800/600', alt: 'Ubud monkey forest sacred temple Bali' },
    { image: 'https://picsum.photos/seed/bali-g8/800/600', alt: 'Jimbaran seafood dinner beach Bali' },
    { image: 'https://picsum.photos/seed/bali-g9/800/600', alt: 'Canggu surf lesson beach Bali' },
    { image: 'https://picsum.photos/seed/bali-g10/800/600', alt: 'Bali temple ceremony offerings flowers' },
    { image: 'https://picsum.photos/seed/bali-g11/800/600', alt: 'Infinity pool resort jungle view Bali' },
    { image: 'https://picsum.photos/seed/bali-g12/800/600', alt: 'Kecak fire dance Uluwatu Bali sunset' },
  ],
  testimonials: [
    { name: 'Deepa & Karthik', city: 'Chennai', tripType: 'Honeymoon', quote: 'Our Bali honeymoon was beyond what we imagined. The private pool villa in Ubud, the sunset dinner at Jimbaran, the Kecak dance at Uluwatu — Outbound Travelers got every detail right.', rating: 5, date: 'March 2026', photo: 'https://picsum.photos/seed/bali-t1/100/100' },
    { name: 'Suresh Family', city: 'Bangalore', tripType: 'Family', quote: 'Traveled with kids aged 8 and 12. Everything was perfectly paced — the water park, Nusa Penida, Ubud — kids loved every day. The guide was patient and brilliant with children.', rating: 5, date: 'May 2026', photo: 'https://picsum.photos/seed/bali-t2/100/100' },
  ] as Testimonial[],
  faqs: [
    { q: 'What is the best time to visit Bali?', a: 'April to October is Bali\'s dry season — the best time to visit for beaches, trekking, and outdoor activities. July and August are peak season so book early. March and November are shoulder months with good weather and lower prices.' },
    { q: 'How many days are enough for a Bali trip?', a: '6–7 nights is ideal for covering Ubud, Seminyak, and a Nusa Penida day trip. 5 nights is possible for a focused trip. 8+ nights lets you add Nusa Lembongan, Amed, or a slow Ubud retreat.' },
    { q: 'Do Indians need a visa for Bali?', a: 'Indian passport holders get visa on arrival at Ngurah Rai International Airport — currently USD 35 for 30 days, extendable once. We brief you on the process and current fee before travel.' },
    { q: 'What is the average cost of a Bali tour package from South India?', a: 'A 6N/7D 3-star package starts from ₹[TBD] per person land-only. Including flights from Chennai or Bangalore, budget ₹[TBD]+ per person. Honeymoon villa packages start higher. Use the cost estimator for a quick range.' },
    { q: 'Do Bali tour packages include flights?', a: 'Land packages don\'t include flights by default. We book flights on request at consolidator rates — usually 5–10% cheaper than direct booking.' },
    { q: 'Can I customize my Bali itinerary?', a: 'Yes — every itinerary is 100% customizable. Mix beach and culture, add adventure, choose your villa style, adjust pace. No fixed templates.' },
    { q: 'Is Bali safe for families with kids?', a: 'Bali is very family-friendly. Nusa Dua and Seminyak are particularly calm. We design kid-friendly itineraries with appropriate pacing, child-friendly hotels, and activities suitable for all ages.' },
    { q: 'What should I pack for Bali?', a: 'Light summer clothes, a light jacket for Ubud evenings and Mount Batur, reef-safe sunscreen, a sarong for temple visits (or rent one there), and walking sandals. Full packing list shared post-booking.' },
    { q: 'What is the difference between Ubud, Seminyak, and Nusa Dua?', a: 'Ubud is Bali\'s cultural and jungle heart — rice terraces, temples, art. Seminyak and Canggu are the beach and nightlife strips. Nusa Dua is calm, resort-style, great for families. Most trips combine two or three zones.' },
    { q: 'Can I get Indian or South Indian food in Bali?', a: 'Yes — Indian restaurants are plentiful in Seminyak and Ubud. For South Indian specifically, we can pre-arrange meals at select partner restaurants. Mention this when you enquire.' },
    { q: 'Is Nusa Penida worth a day trip from Bali?', a: 'Absolutely — Kelingking Beach, Angel\'s Billabong, and Broken Beach are unmissable. The boat ride is 45 minutes from Sanur. We include this in most Bali packages as a full-day excursion.' },
    { q: 'Do I need travel insurance for Bali?', a: 'We strongly recommend it. Bali activities like surfing, trekking, and water sports carry risk. A good travel insurance policy covers medical, trip cancellation, and activity cover. We can help arrange this.' },
  ] as FAQ[],
  relatedDestinations: [
    { name: 'Thailand', image: 'https://picsum.photos/seed/thailand/400/300', href: '/thailand' },
    { name: 'Maldives', image: 'https://picsum.photos/seed/maldives/400/300', href: '/maldives' },
    { name: 'Malaysia', image: 'https://picsum.photos/seed/malaysia/400/300', href: '/malaysia' },
    { name: 'Vietnam', image: 'https://picsum.photos/seed/vietnam/400/300', href: '/vietnam' },
  ] as RelatedDestination[],
  whatsapp: {
    number: '919876543210',
    heroMessage: 'Hi Outbound Travelers, I\'m interested in a Bali tour package. Please share itinerary options and a quote.',
    stickyMessage: 'Hi Outbound Travelers, I\'m planning a Bali trip. Can someone help me plan and quote?',
    floaterMessage: 'Hi Outbound Travelers, I\'m interested in a Bali tour package. Please share itinerary options and a quote.',
    finalCtaMessage: 'Hi Outbound Travelers, I\'m ready to plan my Bali trip. Please send me your best itinerary and quote.',
    postFormMessage: 'Hi Outbound Travelers, I just submitted my Bali enquiry. Travel month: {month}, {travelers} travelers from {city}, trip type: {tripType}. Looking forward to the itinerary and quote.',
  } as WhatsAppConfig,
  leadForm: {
    title: 'Get your Bali quote',
    subtitle: 'Tell us a bit about your trip — we\'ll come back within 2 hours.',
    submitButtonText: 'Get my Bali quote',
    successMessage: 'Got it! Your Bali consultant will WhatsApp you within 2 hours. Meanwhile, save our number: +91-98765-43210.',
    destinationId: 'bali',
    destinationName: 'Bali',
  } as LeadFormConfig,
  seoContent: {
    h2: 'Planning Your Bali Trip with Outbound Travelers',
    sections: [
      {
        h3: 'Which Bali circuit is right for you?',
        body: 'The classic Bali tour package combines Ubud for culture and Seminyak for beaches — two contrasting zones in five or six nights. Add Nusa Penida as a day trip and you have the complete Bali experience. Families often prefer replacing Seminyak with Nusa Dua — calmer waters, resort-style beaches, and more child-friendly infrastructure. Adventure travelers can swap rest days for Mount Batur, white water rafting on the Ayung River, or surf lessons in Canggu.',
      },
      {
        h3: 'Bali from South India — flights, visa, what to plan around',
        body: 'Direct flights to Bali run from major Indian metros. From Chennai, Bangalore, and Hyderabad, one connecting flight via Singapore, Kuala Lumpur, or Colombo is standard — total travel time around six to eight hours. Visa on arrival is available at Ngurah Rai International Airport for Indian passport holders at approximately USD 35. We handle all pre-departure briefings including visa process, currency, and SIM card guidance.',
      },
      {
        h3: 'Customizing your Bali package',
        body: 'Honeymoon travelers typically upgrade to a private pool villa in Ubud or Seminyak and add couples spa sessions, a candlelit dinner on a clifftop, and a sunset cruise. Families add the Waterbom Park in Kuta, the Bali Safari, or a silver jewellery making class for kids in Ubud. Adventure groups build around Mount Batur sunrise, ATV rides, and surfing. Every Bali tour package we build starts from your idea of a perfect trip.',
      },
      {
        h3: 'Why book Bali with Outbound Travelers',
        body: 'Our Bali specialists have planned hundreds of trips to the island. Every villa and resort we recommend is personally vetted. You get a dedicated consultant reachable on WhatsApp from enquiry to return. Quotes come back within two hours. And because we specialise in South Indian travelers, we understand food preferences, family travel styles, and the cultural context that most generic operators miss.',
      },
    ],
  },
}
