import type {
  TrustBadge, Package, ItineraryDay, HotelTier,
  MonthRating, Season, FAQ, Testimonial, RelatedDestination,
  Experience, WhatsAppConfig, ProcessStep, DestinationTheme, LeadFormConfig
} from '@/lib/shared/types'

export const amritsarData = {
  meta: {
    title: 'Amritsar Tour Packages — Golden Temple, Wagah Border, Heritage | Outbound Travelers',
    description: 'Customisable Amritsar tour packages from ₹7,999. Golden Temple, Wagah Border ceremony, Jallianwala Bagh. 2N short trips or add to Kashmir/Shimla. Built for South Indian travellers.',
    canonical: 'https://www.outboundtravelers.com/destinations/amritsar-tour-packages',
    ogImage: 'https://picsum.photos/seed/amritsar-og/1200/630',
    h1: 'Amritsar Tour Packages — Golden Temple, Wagah & Heritage',
  },
  theme: {
    accentColor: '#A16207',
    accentSoft: '#FEF3C7',
    motif: 'khanda-arch',
  } as DestinationTheme,
  hero: {
    variant: 'HeroEditorial',
    eyebrow: 'Domestic · Heritage · Short Trip / Add-on',
    headline: 'Where the Gold Sits Quietly on the Water',
    subheadline: 'Golden Temple at dawn, Wagah Border at dusk, langar in between. A short trip that stays with you — on its own or paired with Kashmir, Shimla or Manali.',
    primaryCta: { label: 'Plan My Amritsar Trip on WhatsApp', action: 'whatsapp' },
    secondaryCta: { label: 'See Packages', action: 'scroll', target: '#amritsar-packages' },
    trustChips: ['Heritage-tested', 'Family-friendly', '24/7 ground team', 'Easy add-on to North India trips'],
    desktopImage: 'https://picsum.photos/seed/amritsar-hero-d/1920/1080',
    mobileImage: 'https://picsum.photos/seed/amritsar-hero-m/800/1200',
    imageAlt: 'Golden Temple Harmandir Sahib Amritsar golden hour reflection sarovar',
  },
  quickSummary: [
    { label: 'Best Time', value: 'Oct–Mar' },
    { label: 'Days', value: '2N/3D standalone; +2N add-on' },
    { label: 'Starts From', value: 'From ₹7,999 per person' },
    { label: 'Combo', value: 'Kashmir / Shimla / Manali' },
  ],
  whyVisit: {
    title: 'Why Amritsar',
    body: 'Some places are about ticking sights. Amritsar isn\'t. The Golden Temple isn\'t a monument — it\'s an active gurudwara, and the silence in the marble courtyard at 4am is the experience. The Wagah Border ceremony is something else entirely — loud, choreographed, emotional. We build trips where you experience both, eat a meal at the langar that feeds 1,00,000+ people a day, and leave a little quieter than you came.',
  },
  comboModule: {
    enabled: true,
    title: 'Add Amritsar to a longer Northern trip',
    combos: [
      { label: 'Kashmir + Amritsar', duration: '9N/10D', note: 'Fly Srinagar, exit via Amritsar', href: '/kashmir' },
      { label: 'Amritsar + Shimla/Manali', duration: '8N/9D', note: 'Land Amritsar, drive up', href: '/shimla' },
      { label: 'Amritsar + Dharamshala/Dalhousie', duration: '5N/6D', note: 'Heritage + hill station', href: '#amritsar-packages' },
    ],
  },
  topExperiences: [
    { id: 'golden-temple', title: 'Golden Temple (Harmandir Sahib)', subtitle: 'Early morning + night visits', image: 'https://picsum.photos/seed/amritsar-exp1/800/600', alt: 'Golden Temple Harmandir Sahib Amritsar at dawn reflection' },
    { id: 'langar', title: 'Langar at Golden Temple', subtitle: 'World\'s largest community kitchen', image: 'https://picsum.photos/seed/amritsar-exp2/800/600', alt: 'Langar community kitchen Golden Temple Amritsar' },
    { id: 'wagah', title: 'Wagah-Attari Border Ceremony', subtitle: 'Evening flag-lowering ceremony', image: 'https://picsum.photos/seed/amritsar-exp3/800/600', alt: 'Wagah Border ceremony Attari India Pakistan flag lowering' },
    { id: 'jallianwala', title: 'Jallianwala Bagh', subtitle: 'Historic memorial', image: 'https://picsum.photos/seed/amritsar-exp4/800/600', alt: 'Jallianwala Bagh memorial Amritsar historic garden' },
    { id: 'partition-museum', title: 'Partition Museum', subtitle: 'Town Hall — most moving museum in India', image: 'https://picsum.photos/seed/amritsar-exp5/800/600', alt: 'Partition Museum Town Hall Amritsar Punjab' },
    { id: 'food-walk', title: 'Local Food Walk', subtitle: 'Kulcha Land, Beera Chicken House, Ahuja Lassi', image: 'https://picsum.photos/seed/amritsar-exp6/800/600', alt: 'Amritsar food walk kulcha lassi local Punjabi food' },
    { id: 'ranjit-museum', title: 'Maharaja Ranjit Singh Museum', subtitle: 'Summer Palace', image: 'https://picsum.photos/seed/amritsar-exp7/800/600', alt: 'Maharaja Ranjit Singh Museum Summer Palace Amritsar' },
    { id: 'durgiana', title: 'Durgiana Temple', subtitle: 'Silver-domed temple', image: 'https://picsum.photos/seed/amritsar-exp8/800/600', alt: 'Durgiana Temple silver dome Amritsar' },
  ],
  packages: [
    {
      id: 'amritsar-short-trip',
      name: 'Amritsar Short Trip',
      duration: '2N/3D',
      featured: true,
      idealFor: 'First-time visitors, Couples, Add-on travelers',
      tier: 'Comfort / Premium',
      highlights: ['Golden Temple darshan twice', 'Wagah Border ceremony', 'Jallianwala Bagh', 'Partition Museum', 'Food walk'],
      price: 'From ₹7,999 per person',
      image: 'https://picsum.photos/seed/amritsar-pkg1/800/600',
      alt: 'Amritsar short trip Golden Temple Wagah 2 nights package',
      whatsappMessage: 'Hi Outbound Travelers, I\'d like to know more about the Amritsar Short Trip 2N/3D package. Please share details and a quote.',
    },
    {
      id: 'amritsar-dharamshala',
      name: 'Amritsar + Wagah + Dharamshala',
      duration: '5N/6D',
      featured: false,
      idealFor: 'Couples, Small groups',
      tier: 'Comfort',
      highlights: ['Amritsar 2N', 'Dharamshala 2N', 'Dalhousie 1N'],
      price: 'From ₹18,999 per person',
      image: 'https://picsum.photos/seed/amritsar-pkg2/800/600',
      alt: 'Amritsar Dharamshala Dalhousie 5 nights combo package',
      whatsappMessage: 'Hi Outbound Travelers, I\'d like to know more about the Amritsar + Dharamshala 5N/6D package. Please share details and a quote.',
    },
    {
      id: 'amritsar-family-heritage',
      name: 'Amritsar Family Heritage',
      duration: '3N/4D',
      featured: false,
      idealFor: 'Families with children, Multi-gen',
      tier: 'Premium',
      highlights: ['Sri Ram Tirath', 'Maharaja Ranjit Singh Museum', 'Food walk', 'Wagah'],
      price: 'From ₹11,999 per person',
      image: 'https://picsum.photos/seed/amritsar-pkg3/800/600',
      alt: 'Amritsar family heritage tour 3 nights package',
      whatsappMessage: 'Hi Outbound Travelers, I\'d like to know more about the Amritsar Family Heritage 3N/4D package. Please share details and a quote.',
    },
    {
      id: 'amritsar-pilgrimage',
      name: 'Amritsar Pilgrimage Special',
      duration: '3N/4D',
      featured: false,
      idealFor: 'Pilgrimage travelers, Senior citizens',
      tier: 'Comfort',
      highlights: ['Goindwal Sahib', 'Tarn Taran Sahib', 'Anandpur Sahib day trip'],
      price: 'From ₹10,999 per person',
      image: 'https://picsum.photos/seed/amritsar-pkg4/800/600',
      alt: 'Amritsar pilgrimage special Goindwal Tarn Taran Anandpur Sahib',
      whatsappMessage: 'Hi Outbound Travelers, I\'d like to know more about the Amritsar Pilgrimage Special 3N/4D package. Please share details and a quote.',
    },
  ],
  itinerary: [
    {
      day: 1,
      title: 'Arrive Amritsar',
      description: 'Hotel check-in. Late afternoon visit to Jallianwala Bagh and Partition Museum. Evening Golden Temple darshan + langar experience.',
      highlights: ['Hotel check-in', 'Jallianwala Bagh', 'Partition Museum', 'Evening Golden Temple darshan', 'Langar'],
      stay: 'Amritsar',
    },
    {
      day: 2,
      title: 'Golden Temple + Wagah + Food Walk',
      description: 'Early morning Golden Temple visit (4–6am recommended). Afternoon Maharaja Ranjit Singh Museum. Late afternoon Wagah Border ceremony (reach by 4pm). Night food walk — Kulcha Land, Beera Chicken House, Ahuja Lassi.',
      highlights: ['Early morning Golden Temple', 'Maharaja Ranjit Singh Museum', 'Wagah Border ceremony', 'Night food walk'],
      stay: 'Amritsar',
    },
    {
      day: 3,
      title: 'Depart Amritsar',
      description: 'Morning shopping at Hall Bazaar. Transfer to Amritsar airport or station for departure.',
      highlights: ['Hall Bazaar shopping', 'Hotel checkout', 'Airport / station transfer'],
      stay: 'Departure',
    },
  ],
  hotelTiers: [
    { tier: 'Comfort (3★)', description: 'Standard properties near the Golden Temple — walking distance to the sarovar, clean and well-located.', amritsarExample: 'Standard near Golden Temple', price: 'From ₹2,000 per night' },
    { tier: 'Premium (4★)', description: 'Full-service hotels with multi-cuisine restaurants and comfortable amenities.', amritsarExample: 'Hyatt / Holiday Inn', price: 'From ₹3,500 per night' },
    { tier: 'Luxury (5★)', description: 'Taj Swarna — the benchmark luxury property in Amritsar, close to the Golden Temple.', amritsarExample: 'Taj Swarna', price: 'From ₹6,000 per night' },
  ],
  months: [
    { month: 'Jan', status: 'peak' as const, note: 'Cool and pleasant. Peak season. Book early.' },
    { month: 'Feb', status: 'peak' as const, note: 'Pleasant weather. Ideal for sightseeing.' },
    { month: 'Mar', status: 'peak' as const, note: 'Warm days, cool nights. Still good.' },
    { month: 'Apr', status: 'shoulder' as const, note: 'Getting warm (28-35°C). Shoulder pricing.' },
    { month: 'May', status: 'shoulder' as const, note: 'Hot (35-40°C). Early morning visits recommended.' },
    { month: 'Jun', status: 'shoulder' as const, note: 'Very hot (38-42°C). Lower crowds and pricing.' },
    { month: 'Jul', status: 'off-peak' as const, note: 'Monsoon begins. Off-peak pricing.' },
    { month: 'Aug', status: 'off-peak' as const, note: 'Monsoon. Occasional heavy rain.' },
    { month: 'Sep', status: 'off-peak' as const, note: 'Monsoon tapering. Transitional month.' },
    { month: 'Oct', status: 'peak' as const, note: 'Post-monsoon clarity. Peak season starts.' },
    { month: 'Nov', status: 'peak' as const, note: 'Best weather. Gurpurab festival possible.' },
    { month: 'Dec', status: 'peak' as const, note: 'Cool and crisp. Christmas + New Year travel.' },
  ] as MonthRating[],
  seasons: [
    { id: 'peak', label: 'Oct–Mar Peak', months: 'October to March', description: 'Pleasant 10–22°C. Best time for Golden Temple and Wagah. Book 30+ days ahead in Nov–Feb.', image: 'https://picsum.photos/seed/amritsar-season-peak/800/600' },
    { id: 'shoulder', label: 'Apr–Jun Shoulder', months: 'April to June', description: 'Hot 28–42°C but fewer crowds and lower prices. Early morning visits make it bearable.', image: 'https://picsum.photos/seed/amritsar-season-shoulder/800/600' },
    { id: 'offpeak', label: 'Jul–Sep Monsoon', months: 'July to September', description: 'Monsoon rains, off-peak pricing. Golden Temple in rain has its own beauty.', image: 'https://picsum.photos/seed/amritsar-season-monsoon/800/600' },
  ] as Season[],
  process: [
    { step: 1, title: 'Tell us your group', description: 'Share travel dates, group size, and whether this is standalone or a combo add-on to Kashmir or Shimla.' },
    { step: 2, title: 'We design your itinerary', description: 'An Amritsar specialist builds your day plan — timing Golden Temple at dawn and Wagah at dusk correctly.' },
    { step: 3, title: 'You confirm and pay deposit', description: 'Review, customise, confirm. Secure with a small deposit. Balance on travel.' },
    { step: 4, title: 'Ground team on call', description: 'Amritsar ground team reachable throughout. Wagah transport, temple guidance, food walk — all covered.' },
  ] as ProcessStep[],
  inclusions: [
    'Accommodation per chosen tier',
    'Daily breakfast',
    'Wagah Border transport (both ways)',
    'All sightseeing transfers in private vehicle',
    'Airport or railway station pickup and drop',
    'Food walk guidance (when listed in package)',
    'All applicable tolls and parking',
    'GST on services',
  ],
  exclusions: [
    'Flights or trains to Amritsar (can be booked on request)',
    'Lunch and dinner (except where listed)',
    'Museum entry fees (Partition Museum, Ranjit Singh Museum)',
    'Personal expenses and tips',
    'Travel insurance (recommended)',
    'Anything not explicitly listed in inclusions',
  ],
  gallery: [
    { image: 'https://picsum.photos/seed/amritsar-g1/800/600', alt: 'Golden Temple Harmandir Sahib at dawn reflection sarovar' },
    { image: 'https://picsum.photos/seed/amritsar-g2/800/600', alt: 'Wagah Border flag lowering ceremony crowd' },
    { image: 'https://picsum.photos/seed/amritsar-g3/800/600', alt: 'Langar Golden Temple community meal thousands' },
    { image: 'https://picsum.photos/seed/amritsar-g4/800/600', alt: 'Jallianwala Bagh memorial garden Amritsar' },
    { image: 'https://picsum.photos/seed/amritsar-g5/800/600', alt: 'Partition Museum Town Hall Amritsar interior' },
    { image: 'https://picsum.photos/seed/amritsar-g6/800/600', alt: 'Amritsar kulcha street food local restaurant' },
    { image: 'https://picsum.photos/seed/amritsar-g7/800/600', alt: 'Maharaja Ranjit Singh Museum Summer Palace Amritsar' },
    { image: 'https://picsum.photos/seed/amritsar-g8/800/600', alt: 'Durgiana Temple silver dome Amritsar' },
    { image: 'https://picsum.photos/seed/amritsar-g9/800/600', alt: 'Golden Temple night illumination reflection water' },
    { image: 'https://picsum.photos/seed/amritsar-g10/800/600', alt: 'Hall Bazaar shopping Amritsar phulkari' },
    { image: 'https://picsum.photos/seed/amritsar-g11/800/600', alt: 'Amritsar food walk lassi Ahuja local guide' },
    { image: 'https://picsum.photos/seed/amritsar-g12/800/600', alt: 'Golden Temple marble courtyard pilgrims morning' },
  ],
  testimonials: [
    { name: 'Surinder family', city: 'Bangalore', tripType: 'Family', quote: 'Took my parents. 4am Golden Temple visit was overwhelming. The langar experience moved them to tears.', rating: 5, date: 'May 2026', photo: 'https://picsum.photos/seed/amritsar-t1/100/100' },
    { name: 'Anand & Priya', city: 'Chennai', tripType: 'Combo', quote: 'Added 2 nights to our Kashmir trip. Wagah ceremony was unforgettable. Food walk was perfectly curated.', rating: 5, date: 'January 2026', photo: 'https://picsum.photos/seed/amritsar-t2/100/100' },
    { name: 'Group of 6', city: 'Coimbatore', tripType: 'Group', quote: 'First time in Punjab. Felt like a different country. Highly recommend the heritage package.', rating: 5, date: 'March 2026', photo: 'https://picsum.photos/seed/amritsar-t3/100/100' },
  ] as Testimonial[],
  faqs: [
    { q: 'How many days are enough for Amritsar?', a: '2 nights is enough for the highlights; 3 nights for a richer experience with day trips.' },
    { q: 'What is the best time to visit Amritsar?', a: 'Oct–Mar for pleasant weather. Summer (Apr–Jun) is harsh at 35–42°C. Monsoon (Jul–Sep) is off-peak.' },
    { q: 'What are the Golden Temple darshan timings?', a: 'The Golden Temple is open 24/7. We recommend visiting at 4–6am for the spiritual experience or 9–11pm for the night illumination.' },
    { q: 'How does the Wagah Border ceremony work?', a: 'We arrange transport and seating. Reach the border by 4pm. The flag-lowering ceremony happens at sunset — around 5:30pm in winter, later in summer.' },
    { q: 'What is the dress code at the Golden Temple?', a: 'Head cover is required — cloth is provided free at the entrance. Shoes must be removed and feet washed at the entry pool.' },
    { q: 'Is Amritsar good for vegetarians?', a: 'Exceptionally so. Amritsar has world-class vegetarian food. The langar at the Golden Temple is pure vegetarian. Kulcha Land is a must.' },
    { q: 'Can we add Dharamshala to an Amritsar trip?', a: 'Yes — Dharamshala is 4–5 hours by road. We offer a dedicated Amritsar + Dharamshala + Dalhousie 5N/6D combo package.' },
    { q: 'Is the food very spicy for South Indian travelers?', a: 'Punjabi food is rich and buttery but not always spicy. Many dishes are South Indian-friendly. Our food walk guide knows your preferences.' },
    { q: 'How do I reach Amritsar from South India?', a: 'Amritsar has its own international airport (ATQ). Direct flights from Delhi and Mumbai; one-stop connections from Bangalore, Chennai, and Kochi. We can book flights on request.' },
    { q: 'Is Amritsar suitable for families with kids?', a: 'Very family-friendly. The Golden Temple welcomes all ages and is deeply moving for children. Jallianwala Bagh is important history for older kids.' },
    { q: 'Can we do a pilgrimage extension from Amritsar?', a: 'Yes — Goindwal Sahib, Tarn Taran Sahib, and Anandpur Sahib are all doable as day trips or overnight extensions. Our Pilgrimage Special package covers these.' },
    { q: 'Are Amritsar tour packages customisable?', a: 'Yes — all our itineraries are built around your group, dates, and preferences. Combo routes, hotel upgrades, flight bookings — all adjustable.' },
  ] as FAQ[],
  relatedDestinations: [
    { name: 'Kashmir', Slug: 'kashmir-tour-packages', image: 'https://picsum.photos/seed/kashmir-rel/400/300', href: '/kashmir' },
    { name: 'Shimla', Slug: 'shimla-tour-packages', image: 'https://picsum.photos/seed/shimla-rel/400/300', href: '/shimla' },
    { name: 'Manali', Slug: 'manali-tour-packages', image: 'https://picsum.photos/seed/manali-rel/400/300', href: '/manali' },
  ] as unknown as RelatedDestination[],
  whatsapp: {
    number: '919876543210',
    heroMessage: 'Hi Outbound Travelers, I\'m interested in an Amritsar tour package. Please share itinerary options and a quote.',
    stickyMessage: 'Hi Outbound Travelers, I\'m planning an Amritsar trip. Can someone help me plan and quote?',
    floaterMessage: 'Hi Outbound Travelers, I\'m interested in an Amritsar tour package. Please share itinerary options and a quote.',
    finalCtaMessage: 'Hi Outbound Travelers, I\'m ready to plan my Amritsar trip. Please send me your best itinerary and quote.',
    postFormMessage: 'Hi Outbound Travelers, I just submitted my Amritsar enquiry. Travel month: {month}, {travelers} travelers from {city}, trip type: {tripType}. Looking forward to the itinerary and quote.',
  } as WhatsAppConfig,
  leadForm: {
    title: 'Get your Amritsar quote',
    subtitle: 'Tell us if this is standalone or an add-on to Kashmir, Shimla, or Manali — we\'ll build around it.',
    submitButtonText: 'Get my Amritsar quote',
    successMessage: 'Got it! Your Amritsar specialist will WhatsApp you within 2 hours.',
    destinationId: 'amritsar',
    destinationName: 'Amritsar',
  } as LeadFormConfig,
  trustChips: ['Heritage-tested', 'Family-friendly', '24/7 ground team', 'Easy add-on to North India trips'],
  seoContent: {
    h2: 'Planning Your Amritsar Trip with Outbound Travelers',
    sections: [
      {
        h3: 'How many days do you need in Amritsar?',
        body: 'Two nights covers the Golden Temple at dawn and dusk, the Wagah Border ceremony, Jallianwala Bagh, and the Partition Museum with time for a food walk. Three nights adds room for Maharaja Ranjit Singh Museum, the Durgiana Temple, and a slower pace at the Golden Temple sarovar. Most South Indian travelers do Amritsar as a two-night standalone or add two nights to a Kashmir or Shimla booking.'
      },
      {
        h3: 'Amritsar from South India — flights and connections',
        body: 'Amritsar\'s Sri Guru Ram Dass Jee International Airport has one-stop connections from Chennai, Bangalore, Kochi, and Hyderabad — typically via Delhi or Mumbai. Flight time from South India is four to five hours with the connection. We book flights on request and plan your arrival so the first evening is your Jallianwala Bagh and Golden Temple introduction.'
      },
      {
        h3: 'Adding Amritsar to a Kashmir or Shimla trip',
        body: 'Amritsar sits at the Punjab end of the northern belt — making it a natural entry or exit point for Kashmir and Himachal Pradesh trips. Our Kashmir plus Amritsar nine-night combo flies you into Srinagar and out via Amritsar. The Amritsar plus Shimla-Manali eight-night combo starts in Amritsar and drives up through Chandigarh. The Dharamshala-Dalhousie five-night combo pairs heritage and hill station in a compact circuit.'
      },
      {
        h3: 'Why book your Amritsar trip with Outbound Travelers',
        body: 'Wagah Border timing is the most common planning mistake — reach by 4pm or you lose the good seats. Golden Temple is most powerful at 4am — most generic operators skip it. Our Amritsar specialists, who are South Indian themselves, know exactly what moves travelers from Tamil Nadu, Karnataka, and Kerala and build the experience accordingly. We handle flights, transfers, hotel, Wagah transport, and the food walk in one plan.'
      },
    ]
  }
}
