import type {
  TrustBadge, Package, ItineraryDay, HotelTier,
  MonthRating, Season, FAQ, Testimonial, RelatedDestination,
  Experience, WhatsAppConfig, ProcessStep, DestinationTheme, LeadFormConfig
} from '@/lib/shared/types'

export const lakshadweepData = {
  meta: {
    title: 'Lakshadweep Tour Packages — Exclusive Island Trips | Outbound Travelers',
    description: 'Plan your Lakshadweep trip with Outbound Travelers. Honeymoon, luxury & snorkelling packages with permits, island stays, and transfers. Lightning-fast quotes.',
    canonical: 'https://www.outboundtravelers.com/lakshadweep',
    ogImage: 'https://picsum.photos/seed/lakshadweep-og/1200/630',
    h1: 'Lakshadweep Tour Packages — India\'s Last Pristine Island Escape',
  },
  theme: {
    accentColor: '#06B6D4',
    accentSoft: '#CFFAFE',
    motif: 'coral-wave',
  } as DestinationTheme,
  hero: {
    variant: 'HeroCinematic',
    headline: 'Lakshadweep — Where India Meets the Indian Ocean',
    subheadline: 'Crystal lagoons, coral reefs, and zero crowds — India\'s most exclusive island destination, fully permitted and planned for South Indian travelers.',
    primaryCta: 'Get my Lakshadweep quote',
    secondaryCta: 'Or talk to a travel expert on WhatsApp',
    desktopImage: 'https://picsum.photos/seed/lakshadweep-hero-d/1920/1080',
    mobileImage: 'https://picsum.photos/seed/lakshadweep-hero-m/800/1200',
    imageAlt: 'Lakshadweep lagoon crystal blue water coral reef aerial view',
  },
  trustBadges: [
    { icon: 'trips', label: '2,500+ trips delivered' },
    { icon: 'custom', label: '100% customizable' },
    { icon: 'verified', label: 'Permit handled' },
    { icon: 'support', label: '24/7 on-trip support' },
    { icon: 'quote', label: 'Lightning quotes' },
    { icon: 'member', label: 'TAFI/IATA member' },
  ] as TrustBadge[],
  quickSummary: {
    duration: '4–6 nights ideal',
    bestSeason: 'Oct–May (Calm Lagoons)',
    startingFrom: 'From ₹[TBD] per person',
    tripTypes: 'Honeymoon · Luxury · Snorkelling · Exclusive',
  },
  whyVisit: [
    {
      icon: 'specialist',
      title: 'Permits and NOC — completely handled',
      description: 'Entry permits and No Objection Certificates for Lakshadweep require advance paperwork. We handle every document so you just board the flight.',
    },
    {
      icon: 'verified',
      title: 'Verified island resorts and cottages',
      description: 'Accommodation in Lakshadweep is government-regulated and limited. We work with verified approved operators and secure bookings months in advance.',
    },
    {
      icon: 'southindia',
      title: 'South India\'s closest ocean escape',
      description: 'Just 90 minutes from Kochi by flight to Agatti. The nearest pristine coral atoll to South Indian travelers — closer than Maldives, more exclusive than Andaman.',
    },
  ],
  experiences: [
    {
      id: 'lagoon-snorkel',
      title: 'Lagoon Snorkelling & Glass-Bottom Boats',
      description: 'Slip into a lagoon so clear you can see the coral 10 metres below from the surface. Lakshadweep\'s coral ecosystem is among the healthiest in India — parrotfish, rays, turtles in the same snorkel session.',
      image: 'https://picsum.photos/seed/lakshadweep-snorkel/800/600',
      alt: 'Lakshadweep lagoon snorkelling coral reef clear water',
      seasonal: false,
    },
    {
      id: 'scuba',
      title: 'Scuba Diving — Certified & Discovery',
      description: 'Bangaram and Kadmat offer some of the best scuba diving in India. Dive sites with walls, channels, and reef flats rich with marine life. Certified PADI courses and discovery dives both available.',
      image: 'https://picsum.photos/seed/lakshadweep-scuba/800/600',
      alt: 'Scuba diving Lakshadweep Bangaram coral reef marine life',
      seasonal: false,
    },
    {
      id: 'bangaram-island',
      title: 'Bangaram Island — The Uninhabited Atoll',
      description: 'A teardrop-shaped uninhabited island with a single resort. White sand beach, turquoise lagoon on all sides, no roads, no crowds — the most exclusive spot in Lakshadweep.',
      image: 'https://picsum.photos/seed/bangaram/800/600',
      alt: 'Bangaram Island uninhabited atoll Lakshadweep resort',
      seasonal: false,
    },
    {
      id: 'kayaking',
      title: 'Kayaking & Canoe in the Lagoon',
      description: 'Paddle through the shallow lagoon in a transparent kayak — the coral gardens visible below as you drift. Dawn kayaking when the lagoon is a mirror is the best hour of any Lakshadweep trip.',
      image: 'https://picsum.photos/seed/lakshadweep-kayak/800/600',
      alt: 'Kayaking Lakshadweep lagoon transparent kayak coral',
      seasonal: false,
    },
    {
      id: 'local-culture',
      title: 'Island Culture & Local Life',
      description: 'Lakshadweep\'s inhabited islands — Kavaratti, Minicoy, Agatti — have a distinct Malayali-Arab culture. Mosques, traditional fishing, coconut cultivation, and warm island hospitality unlike any Indian mainland experience.',
      image: 'https://picsum.photos/seed/lakshadweep-culture/800/600',
      alt: 'Lakshadweep island culture local life Kavaratti mosque',
      seasonal: false,
    },
    {
      id: 'turtle-nesting',
      title: 'Sea Turtle Nesting — Nov to Feb',
      description: 'Hawksbill and green turtles nest on Lakshadweep beaches between November and February. Supervised twilight walks with conservation guides — one of India\'s most extraordinary wildlife encounters.',
      image: 'https://picsum.photos/seed/turtle-nesting/800/600',
      alt: 'Sea turtle nesting Lakshadweep beach November conservation',
      seasonal: true,
      seasonMonths: [11, 12, 1, 2],
    },
  ] as Experience[],
  packages: [
    {
      id: 'lakshadweep-classic',
      name: 'Lakshadweep Classic',
      duration: '4 Nights / 5 Days',
      idealFor: 'First-time visitors, Couples',
      highlights: ['Agatti or Kadmat island', 'Lagoon snorkelling', 'Glass-bottom boat', 'Permit included'],
      price: 'From ₹[TBD] per person',
      image: 'https://picsum.photos/seed/lakshadweep-pkg1/800/600',
      alt: 'Lakshadweep classic tour package Agatti lagoon',
      whatsappMessage: 'Hi Outbound Travelers, I\'d like to know more about the Lakshadweep Classic 4N/5D package. Please share details and customization options.',
      seasonal: false,
    },
    {
      id: 'lakshadweep-honeymoon',
      name: 'Lakshadweep Honeymoon Escape',
      duration: '5 Nights / 6 Days',
      idealFor: 'Newly-married couples, Anniversary trips',
      highlights: ['Bangaram island stay', 'Private beach dinner', 'Couples snorkel', 'Water villa upgrade'],
      price: 'From ₹[TBD] per couple',
      image: 'https://picsum.photos/seed/lakshadweep-pkg2/800/600',
      alt: 'Lakshadweep honeymoon escape Bangaram private beach',
      whatsappMessage: 'Hi Outbound Travelers, I\'d like to know more about the Lakshadweep Honeymoon Escape 5N/6D. Please share details and customization options.',
      seasonal: false,
    },
    {
      id: 'lakshadweep-dive',
      name: 'Lakshadweep Dive Expedition',
      duration: '5 Nights / 6 Days',
      idealFor: 'Scuba divers, Snorkelling enthusiasts',
      highlights: ['Bangaram dive sites', 'Kadmat wall dive', '4 guided dives', 'PADI certified optional'],
      price: 'From ₹[TBD] per person',
      image: 'https://picsum.photos/seed/lakshadweep-pkg3/800/600',
      alt: 'Lakshadweep dive expedition Bangaram scuba',
      whatsappMessage: 'Hi Outbound Travelers, I\'d like to know more about the Lakshadweep Dive Expedition 5N/6D. Please share details and customization options.',
      seasonal: false,
    },
    {
      id: 'lakshadweep-luxury',
      name: 'Lakshadweep Luxury Island',
      duration: '6 Nights / 7 Days',
      idealFor: 'Luxury travelers, Exclusive escape seekers',
      highlights: ['Bangaram premium cottages', 'Multi-island circuit', 'Private snorkel guide', 'Sunset dinner on beach'],
      price: 'From ₹[TBD] per person',
      image: 'https://picsum.photos/seed/lakshadweep-pkg4/800/600',
      alt: 'Lakshadweep luxury island Bangaram premium cottage',
      whatsappMessage: 'Hi Outbound Travelers, I\'d like to know more about the Lakshadweep Luxury Island 6N/7D. Please share details and customization options.',
      seasonal: false,
    },
    {
      id: 'lakshadweep-turtle',
      name: 'Lakshadweep Turtle Season',
      duration: '5 Nights / 6 Days',
      idealFor: 'Wildlife seekers, Nature lovers',
      highlights: ['Turtle nesting walk', 'Conservation guide', 'Snorkelling', 'Island culture visit'],
      price: 'From ₹[TBD] per person',
      image: 'https://picsum.photos/seed/lakshadweep-pkg5/800/600',
      alt: 'Lakshadweep turtle nesting season package November',
      whatsappMessage: 'Hi Outbound Travelers, I\'d like to know more about the Lakshadweep Turtle Season 5N/6D. Please share details and customization options.',
      seasonal: true,
      seasonMonths: [11, 12, 1, 2],
    },
  ] as Package[],
  itinerary: [
    {
      day: 1,
      title: 'Fly Kochi to Agatti — Island Arrival',
      description: 'Morning flight from Kochi to Agatti (90 min). First sight of the lagoon from the air is unforgettable. Speedboat transfer to your island. Afternoon at leisure in the lagoon.',
      highlights: ['Kochi–Agatti flight', 'Speedboat transfer', 'First lagoon dip'],
      stay: 'Agatti / Bangaram',
    },
    {
      day: 2,
      title: 'Lagoon Day — Snorkelling & Glass Bottom',
      description: 'Full day lagoon exploration. Morning snorkel with guide — coral gardens, fish schools, rays. Afternoon glass-bottom boat tour. Sunset on the beach.',
      highlights: ['Guided snorkelling', 'Glass-bottom boat', 'Reef fish and coral'],
      stay: 'Agatti / Bangaram',
    },
    {
      day: 3,
      title: 'Scuba Diving or Kayaking Day',
      description: 'Discovery dive for non-certified or guided dive for certified divers. Non-divers: transparent kayak through the lagoon, canoe tour, or beach walk. Afternoon free.',
      highlights: ['Scuba dive / kayak', 'Transparent kayak lagoon', 'Coral garden paddle'],
      stay: 'Agatti / Bangaram',
    },
    {
      day: 4,
      title: 'Island Hopping — Culture & Uninhabited Beaches',
      description: 'Day trip to a nearby island — Kavaratti for the mosque and local culture, or an uninhabited sand spit for a private picnic lunch. Return by speedboat.',
      highlights: ['Island hopping speedboat', 'Kavaratti culture visit', 'Uninhabited island picnic'],
      stay: 'Agatti / Bangaram',
    },
    {
      day: 5,
      title: 'Final Lagoon Morning & Departure',
      description: 'Last sunrise on the beach. Final snorkel or lagoon walk. Speedboat to Agatti. Afternoon flight back to Kochi.',
      highlights: ['Last sunrise snorkel', 'Speedboat to Agatti', 'Kochi flight return'],
      stay: 'Departure',
    },
  ] as ItineraryDay[],
  hotelTiers: [
    {
      tier: 'SPORTS Island Cottages',
      description: 'Government-run Society for Promotion of Nature Tourism and Sports (SPORTS) cottages on Agatti, Kadmat, and Minicoy. Simple, clean, lagoon-facing. The most accessible option.',
      price: 'From ₹[TBD] per night',
    },
    {
      tier: 'Bangaram Island Resort',
      description: 'The only private luxury resort in Lakshadweep on an uninhabited island. Thatched cottages, beach access, dive centre, restaurant. The definitive Lakshadweep experience.',
      price: 'From ₹[TBD] per night',
    },
    {
      tier: 'Agatti Island Beach Resort',
      description: 'Well-maintained beachfront property on Agatti island with comfortable rooms, lagoon access, and good meal arrangements.',
      price: 'From ₹[TBD] per night',
    },
    {
      tier: 'Thinnakara Island Camp',
      description: 'Eco-camp on the uninhabited Thinnakara island — tented accommodation, campfire dinners, complete isolation, and the most pristine snorkelling in Lakshadweep.',
      price: 'From ₹[TBD] per night',
    },
  ] as HotelTier[],
  months: [
    { month: 'Jan', rating: 'best', note: 'Perfect conditions, calm lagoon, turtle nesting ends.' },
    { month: 'Feb', rating: 'best', note: 'Best visibility for diving and snorkelling.' },
    { month: 'Mar', rating: 'best', note: 'Ideal weather, clear skies, peak season.' },
    { month: 'Apr', rating: 'best', note: 'Good conditions, slightly warmer.' },
    { month: 'May', rating: 'good', note: 'Pre-monsoon, still accessible but book early.' },
    { month: 'Jun', rating: 'avoid', note: 'Islands closed — monsoon, no flights or boats.' },
    { month: 'Jul', rating: 'avoid', note: 'Completely inaccessible, no tourism.' },
    { month: 'Aug', rating: 'avoid', note: 'Monsoon season, islands closed to tourism.' },
    { month: 'Sep', rating: 'avoid', note: 'Still closed, seas rough.' },
    { month: 'Oct', rating: 'good', note: 'Islands reopen, early season, fewer crowds.' },
    { month: 'Nov', rating: 'best', note: 'Season peaks, turtle nesting begins.' },
    { month: 'Dec', rating: 'best', note: 'Peak season, Christmas on an island paradise.' },
  ] as MonthRating[],
  seasons: [
    {
      id: 'peak',
      label: 'Peak Island Season',
      months: 'Nov–Apr',
      description: 'Calm lagoons, perfect visibility, all activities running. Book 60–90 days in advance — accommodation is extremely limited.',
      image: 'https://picsum.photos/seed/lakshadweep-peak/800/600',
    },
    {
      id: 'turtle',
      label: 'Turtle Nesting Season',
      months: 'Nov–Feb',
      description: 'Hawksbill and green turtles nest on beaches. Supervised twilight walks with conservation guides. Book the turtle package specifically.',
      image: 'https://picsum.photos/seed/lakshadweep-turtle/800/600',
    },
    {
      id: 'shoulder',
      label: 'Shoulder Season',
      months: 'May & Oct',
      description: 'Islands accessible with slightly lower prices. May has pre-monsoon heat. October is fresh post-monsoon. Fewer tourists than peak.',
      image: 'https://picsum.photos/seed/lakshadweep-shoulder/800/600',
    },
    {
      id: 'closed',
      label: 'Monsoon — Islands Closed',
      months: 'Jun–Sep',
      description: 'Lakshadweep is completely inaccessible June through September. No flights, no boats. Do not plan travel in this window.',
      image: 'https://picsum.photos/seed/lakshadweep-monsoon/800/600',
    },
  ] as Season[],
  process: [
    {
      step: 1,
      title: 'Share your dates and group',
      description: 'Tell us your travel window and group size. We confirm island and accommodation availability first — Lakshadweep has very limited capacity.',
    },
    {
      step: 2,
      title: 'Permits and NOC initiated',
      description: 'We begin the Entry Permit and NOC process immediately — this takes 2–4 weeks and must be started well before travel.',
    },
    {
      step: 3,
      title: 'Itinerary and accommodation confirmed',
      description: 'Island choice, cottage type, dive bookings, and all inter-island transfers locked. Full itinerary sent for your approval.',
    },
    {
      step: 4,
      title: 'Travel with complete island support',
      description: 'Your consultant stays reachable through your island stay. Emergency contact with the island resort operator always active.',
    },
  ] as ProcessStep[],
  inclusions: [
    'Entry Permit and NOC processing (government fee extra at actuals)',
    'Kochi to Agatti return flight (or ship from Kochi — per package)',
    'Island accommodation per chosen tier',
    'All meals on island (full board — limited dining options on islands)',
    'Speedboat transfers between islands where applicable',
    'Snorkelling gear and guided snorkel session',
    'Glass-bottom boat tour',
    'All applicable taxes and resort fees',
  ],
  exclusions: [
    'Entry Permit and NOC government fees (paid at actuals, approx ₹3,000–5,000 pp)',
    'Scuba diving charges (priced per dive at actuals)',
    'Kayak, canoe, and other water sport equipment rental',
    'Personal expenses and tips',
    'Travel insurance (strongly recommended — medical evacuation from islands is expensive)',
    'Anything not explicitly in inclusions',
  ],
  gallery: [
    { image: 'https://picsum.photos/seed/lakshadweep-g1/800/600', alt: 'Lakshadweep lagoon aerial view crystal blue water' },
    { image: 'https://picsum.photos/seed/lakshadweep-g2/800/600', alt: 'Bangaram Island white sand beach turquoise lagoon' },
    { image: 'https://picsum.photos/seed/lakshadweep-g3/800/600', alt: 'Snorkelling coral reef Lakshadweep clear water' },
    { image: 'https://picsum.photos/seed/lakshadweep-g4/800/600', alt: 'Scuba diving Lakshadweep Bangaram marine life' },
    { image: 'https://picsum.photos/seed/lakshadweep-g5/800/600', alt: 'Transparent kayak Lakshadweep lagoon coral below' },
    { image: 'https://picsum.photos/seed/lakshadweep-g6/800/600', alt: 'Sea turtle Lakshadweep beach nesting November' },
    { image: 'https://picsum.photos/seed/lakshadweep-g7/800/600', alt: 'Lakshadweep sunset beach silhouette couple' },
    { image: 'https://picsum.photos/seed/lakshadweep-g8/800/600', alt: 'Kavaratti island mosque Lakshadweep local culture' },
    { image: 'https://picsum.photos/seed/lakshadweep-g9/800/600', alt: 'Glass bottom boat tour Lakshadweep reef' },
    { image: 'https://picsum.photos/seed/lakshadweep-g10/800/600', alt: 'Agatti island view from plane window lagoon' },
    { image: 'https://picsum.photos/seed/lakshadweep-g11/800/600', alt: 'Thinnakara island eco camp tent Lakshadweep' },
    { image: 'https://picsum.photos/seed/lakshadweep-g12/800/600', alt: 'Lakshadweep honeymoon couple private beach dinner' },
  ],
  testimonials: [
    {
      name: 'Ananya & Rohit',
      city: 'Kochi',
      tripType: 'Honeymoon',
      quote: 'Lakshadweep for our honeymoon was the best decision. Bangaram was completely private — just us, the ocean, and the reef. Outbound Travelers handled every permit without a single call from us.',
      rating: 5,
      date: 'February 2026',
      photo: 'https://picsum.photos/seed/lakshadweep-t1/100/100',
    },
    {
      name: 'Prashanth & Group',
      city: 'Bangalore',
      tripType: 'Adventure',
      quote: 'Four dives in three days at Bangaram. The wall dive at Kadmat was the best dive I\'ve done in India. Permits were ready, accommodation was sorted — just showed up and dived.',
      rating: 5,
      date: 'March 2026',
      photo: 'https://picsum.photos/seed/lakshadweep-t2/100/100',
    },
  ] as Testimonial[],
  faqs: [
    {
      q: 'Do Indians need a permit to visit Lakshadweep?',
      a: 'Yes — Indian nationals need an Entry Permit to visit Lakshadweep. Foreign nationals require additional clearances. The permit process takes 2–4 weeks. We handle all documentation — you just provide your ID and details.',
    },
    {
      q: 'What is the best time to visit Lakshadweep?',
      a: 'October to May is the accessible window. November to April is ideal — calm seas, clear visibility, perfect snorkelling and diving. June to September is monsoon season and the islands are completely closed to tourism.',
    },
    {
      q: 'How do I get to Lakshadweep from South India?',
      a: 'The easiest way is a 90-minute flight from Kochi to Agatti island. Alternatively there is a ship from Kochi that takes 14–18 hours and reaches multiple islands. We recommend the flight for most travelers — faster and more reliable for short trips.',
    },
    {
      q: 'How many days are enough for Lakshadweep?',
      a: '4–5 nights is ideal. The islands are small — you can cover snorkelling, diving, kayaking, and island culture in this time. 6 nights allows a multi-island circuit. Do not try to rush Lakshadweep in under 3 nights.',
    },
    {
      q: 'Is Lakshadweep expensive?',
      a: 'Yes — accommodation is limited and demand is high, making it premium priced compared to mainland destinations. A 4N/5D package starts from ₹[TBD] per person including flights. Bangaram Island Resort is the most expensive. SPORTS cottages are the most affordable.',
    },
    {
      q: 'Can I do scuba diving in Lakshadweep?',
      a: 'Yes — Lakshadweep has some of the best scuba diving in India. Bangaram and Kadmat are the primary dive locations. PADI-certified dives and discovery dives for beginners are both available. We include dive packages on request.',
    },
    {
      q: 'What is Bangaram Island?',
      a: 'Bangaram is an uninhabited teardrop-shaped island with a single luxury resort — Bangaram Island Resort. No local population, no roads, just beach and lagoon. It is the most exclusive accommodation option in Lakshadweep.',
    },
    {
      q: 'Is Lakshadweep good for families with kids?',
      a: 'Yes for families with older children (10+) who can snorkel. The lagoons are calm and safe. Activities like glass-bottom boat tours and beach walks are accessible for all ages. Very young children may find the limited facilities and boat transfers tiring.',
    },
    {
      q: 'What are the conservation rules in Lakshadweep?',
      a: 'Lakshadweep has strict conservation rules — no single-use plastic, no coral touching, no shell collection, no loud music on beaches, no fishing without permit. We brief all travelers before departure. Respecting these rules is non-negotiable.',
    },
    {
      q: 'Is Lakshadweep better than Andaman or Maldives?',
      a: 'Lakshadweep is less developed and more pristine than Andaman, with arguably better coral. It is more exclusive but has fewer luxury options than Maldives. For Indian travelers wanting unspoiled nature closer to home, Lakshadweep is unique.',
    },
    {
      q: 'Can I see sea turtles in Lakshadweep?',
      a: 'Yes — Hawksbill and green turtles nest on Lakshadweep beaches from November to February. Conservation-guided twilight turtle walks are available during this window. This is one of India\'s most extraordinary wildlife experiences.',
    },
    {
      q: 'How far in advance should I book Lakshadweep?',
      a: 'At least 60–90 days in advance. Accommodation is extremely limited — Bangaram has fewer than 30 cottages. Peak season (Dec–Mar) sells out months ahead. Permits also need 2–4 weeks processing time.',
    },
  ] as FAQ[],
  relatedDestinations: [
    { name: 'Maldives', image: 'https://picsum.photos/seed/maldives-rel/400/300', href: '/maldives' },
    { name: 'Andaman', image: 'https://picsum.photos/seed/andaman-rel/400/300', href: '/andaman' },
    { name: 'Kerala', image: 'https://picsum.photos/seed/kerala-rel/400/300', href: '/destinations/kerala-tour-packages' },
    { name: 'Bali', image: 'https://picsum.photos/seed/bali-rel/400/300', href: '/bali' },
  ] as RelatedDestination[],
  whatsapp: {
    number: '918072120021', // Actual valid testing number as referenced
    heroMessage: 'Hi Outbound Travelers, I\'m interested in a Lakshadweep tour package. Please share island options, permit process, and a quote.',
    stickyMessage: 'Hi Outbound Travelers, I\'m planning a Lakshadweep trip. Can someone help me with permits and planning?',
    floaterMessage: 'Hi Outbound Travelers, I\'m interested in Lakshadweep. Please share package options and the permit process.',
    finalCtaMessage: 'Hi Outbound Travelers, I\'m ready to plan my Lakshadweep trip. Please share availability, permits, and your best quote.',
    postFormMessage: 'Hi Outbound Travelers, I just submitted my Lakshadweep enquiry. Travel month: {month}, {travelers} travelers from {city}, trip type: {tripType}. Please confirm availability and start the permit process.',
  } as WhatsAppConfig,
  leadForm: {
    title: 'Get your Lakshadweep quote',
    subtitle: 'Accommodation is limited — tell us your dates so we can check availability first.',
    submitButtonText: 'Get my Lakshadweep quote',
    successMessage: 'Got it! Your Lakshadweep specialist will WhatsApp you within 2 hours to confirm availability and start the permit process.',
    destinationId: 'lakshadweep',
    destinationName: 'Lakshadweep',
  } as LeadFormConfig,
  permitInfo: {
    title: '📋 Entry Permit & NOC — We Handle Everything',
    subtitle: 'Visiting Lakshadweep requires government permits. Start the process 60+ days before travel.',
    points: [
      'Indian nationals require an Entry Permit from the Lakshadweep Administration',
      'A No Objection Certificate (NOC) is required from the island administration',
      'Permit processing takes 2–4 weeks — start immediately after booking',
      'We collect your documents and submit the permit application on your behalf',
      'Government permit fees are approximately ₹3,000–5,000 per person (paid at actuals)',
      'Without a valid permit you cannot board the flight to Agatti',
    ],
    urgencyNote: 'Book at least 60–90 days before travel to allow permit processing time and secure limited island accommodation.',
  },
  conservationRules: [
    'No single-use plastic on any island',
    'Do not touch or stand on coral reefs',
    'No collection of shells, coral, or marine life',
    'No loud music on beaches especially near turtle nesting areas',
    'Dispose of all waste only at designated points',
    'Respect local customs — Lakshadweep is a Muslim-majority union territory',
  ],
  honeymoonyLuxury: {
    title: 'Lakshadweep for the Two of You',
    image: 'https://picsum.photos/seed/lakshadweep-honeymoon-feat/800/600',
    body: 'A private beach on an uninhabited island. A candlelit dinner where the only sound is the ocean. Snorkelling in a lagoon that no cruise ship has ever entered. Lakshadweep offers a privacy and exclusivity that no developed resort destination can match — because the islands themselves are the experience.',
    highlights: [
      'Bangaram Island — India\'s most private island resort',
      'Private beach dinners with lagoon view',
      'Couples snorkel with personal guide',
      'Sunrise kayaking on a glass-flat lagoon',
    ],
    cta: 'See honeymoon packages',
  },
  seoContent: {
    h2: 'Planning Your Lakshadweep Trip with Outbound Travelers',
    sections: [
      {
        h3: 'Which Lakshadweep island is right for you?',
        body: 'Agatti is the entry point — the airport island, with good SPORTS cottages and a beautiful lagoon. Kadmat is the diver\'s island — longer, with excellent wall dives and snorkelling. Bangaram is the exclusive option — uninhabited, one resort, complete privacy. Minicoy is the southernmost and most culturally distinct island. Most packages use Agatti as base with day trips or combine Agatti and Bangaram for a two-island experience.',
      },
      {
        h3: 'Lakshadweep from South India — flights, permits, what to plan around',
        body: 'Kochi is the gateway to Lakshadweep. The Agatti flight is 90 minutes and runs daily with limited seats — book well in advance. The Kochi-based ship service reaches more islands but takes 14–18 hours and runs on a limited schedule. Because of the permit requirement and the accommodation scarcity, Lakshadweep needs to be booked 60–90 days ahead, not on impulse.',
      },
      {
        h3: 'Customizing your Lakshadweep package',
        body: 'Honeymooners choose Bangaram for total privacy with beach dinners and couples snorkel. Divers build around Bangaram and Kadmat dive sites with 4–6 guided dives. Wildlife seekers time their visit for November to February and add the turtle nesting walk. Families with older children combine snorkelling, glass-bottom boats, and a Kavaratti culture visit for a well-rounded island experience.',
      },
      {
        h3: 'Why book Lakshadweep with Outbound Travelers',
        body: 'The permit process alone puts most travelers off Lakshadweep — which is exactly why so few people go, and why those who do find it pristine. We handle every document, every submission, every follow-up with the administration. Our island contacts secure accommodation months in advance. And because we are a South India-based operator, Kochi logistics — the gateway to Lakshadweep — are something we manage daily.',
      },
    ],
  },
}
