import type {
  TrustBadge, Package, ItineraryDay, HotelTier,
  MonthRating, Season, FAQ, Testimonial, RelatedDestination,
  Experience, WhatsAppConfig, ProcessStep, DestinationTheme, LeadFormConfig
} from '@/lib/shared/types'

export const kashmirData = {
  meta: {
    title: 'Kashmir Tour Packages — Customizable Trips | Outbound Travelers',
    description: 'Plan your Kashmir trip with Outbound Travelers. Honeymoon, family & group packages with flights, hotels, transfers. Get a lightning-fast custom quote today.',
    canonical: 'https://www.outboundtravelers.com/kashmir',
    ogImage: '/kashmir/og-kashmir.jpg',
    h1: 'Kashmir Tour Packages — Customized Trips to the Valley of Paradise',
  },
  theme: {
    accentColor: '#1F6E3F',
    accentSoft: '#E3F0E8',
    motif: 'chinar-leaf',
  } as DestinationTheme,
  hero: {
    headline: 'Kashmir, Crafted Just for You',
    subheadline: 'Honeymoon, family, and group trips planned end-to-end by Kashmir specialists — fully customizable, lightning-fast quotes, premium on-trip support.',
    primaryCta: 'Get my Kashmir quote',
    secondaryCta: 'Or talk to a travel expert on WhatsApp',
    desktopImage: '/kashmir/hero-desktop.jpg',
    mobileImage: '/kashmir/hero-mobile.jpg',
    imageAlt: 'Shikara on Dal Lake at golden hour with mountains in the background, Srinagar, Kashmir',
  },
  trustBadges: [
    { icon: 'trips', label: '2,500+ trips delivered' },
    { icon: 'custom', label: '100% customizable' },
    { icon: 'verified', label: 'Verified houseboats' },
    { icon: 'support', label: '24/7 on-trip support' },
    { icon: 'quote', label: 'Lightning quotes' },
    { icon: 'member', label: 'TAFI/IATA member' },
  ] as TrustBadge[],
  quickSummary: {
    duration: '5–7 nights ideal',
    bestSeason: 'March–October (Tulips · Summer · Autumn)',
    startingFrom: 'From ₹[TBD] per person',
    tripTypes: 'Honeymoon · Family · Group · Luxury',
  },
  whyVisit: [
    {
      icon: 'specialist',
      title: 'Crafted, not templated',
      description: 'Our consultants build your Kashmir itinerary around your pace, your group, and your travel style — no fixed group departures, no compromise.',
    },
    {
      icon: 'verified',
      title: 'Verified inventory, real support',
      description: 'Every houseboat and hotel is vetted by our team, and you\'ll have a real person reachable on WhatsApp through your trip.',
    },
    {
      icon: 'southindia',
      title: 'South India to Srinagar, sorted',
      description: 'Flights from Chennai, Bangalore, Coimbatore, Madurai, Trivandrum, plus South Indian food arrangements on request.',
    },
  ],
  experiences: [
    { id: 'dal-lake', title: 'Dal Lake Shikara at Sunrise', description: 'Glide across glassy water as Srinagar wakes up. The morning mist, the wooden houseboats, the distant Zabarwan mountains — this is Kashmir at its most peaceful.', image: '/kashmir/exp-dal.jpg', alt: 'Shikara ride on Dal Lake at sunrise Srinagar Kashmir', seasonal: false },
    { id: 'gulmarg', title: 'Gulmarg Gondola Phase 2', description: 'Asia\'s highest cable car rises to Apharwat Peak at 4,200m. Snow-capped views, skiing in winter, wildflower meadows in summer.', image: '/kashmir/exp-gulmarg.jpg', alt: 'Gulmarg gondola cable car over snow Kashmir', seasonal: false },
    { id: 'pahalgam', title: 'Pahalgam\'s Aru & Betaab Valley', description: 'Pine forests, a rushing river, open meadows, and mountain walls in every direction — all reachable in one unhurried day.', image: '/kashmir/exp-pahalgam.jpg', alt: 'Aru Valley pine forest Pahalgam Kashmir', seasonal: false },
    { id: 'sonmarg', title: 'Sonmarg Thajiwas Glacier', description: 'Pony or trek up to a glacier that stays snow-covered even in summer. The valley drive to get there is half the experience.', image: '/kashmir/exp-sonmarg.jpg', alt: 'Sonmarg Thajiwas glacier summer Kashmir', seasonal: false },
    { id: 'mughal', title: 'Mughal Gardens & Old Srinagar', description: 'Shalimar Bagh, Nishat Bagh, Chashme Shahi — three terraced gardens built by Mughal emperors. Old city walk through Jamia Masjid and the craft bazaars.', image: '/kashmir/exp-mughal.jpg', alt: 'Shalimar Bagh Mughal garden Srinagar Kashmir spring', seasonal: false },
    { id: 'tulip', title: 'Tulip Garden, Spring Only', description: '1.5 million tulips across Asia\'s largest tulip garden, blooming on the slopes of Zabarwan hill overlooking Dal Lake. Mid-March to April only.', image: '/kashmir/exp-tulip.jpg', alt: 'Tulip Garden Srinagar April bloom Kashmir', seasonal: true, seasonMonths: [3, 4] },
  ] as Experience[],
  packages: [
    {
      id: 'classic',
      name: 'Kashmir Classic',
      duration: '5 Nights / 6 Days',
      idealFor: 'First-time visitors, Families',
      highlights: ['Srinagar 2N', 'Gulmarg day', 'Pahalgam 2N'],
      price: 'From ₹[TBD] per person',
      image: '/kashmir/pkg-classic.jpg',
      alt: 'Kashmir Classic tour package Srinagar Gulmarg Pahalgam',
      whatsappMessage: 'Hi Outbound Travelers, I\'d like to know more about the Kashmir Classic 5N/6D package. Please share details and customization options.',
      seasonal: false,
    },
    {
      id: 'honeymoon',
      name: 'Kashmir Honeymoon Special',
      duration: '6 Nights / 7 Days',
      idealFor: 'Newly-married couples, Anniversary trips',
      highlights: ['Heritage houseboat', 'Private shikara', 'Candlelit dinner'],
      price: 'From ₹[TBD] per couple',
      image: '/kashmir/pkg-honeymoon.jpg',
      alt: 'Kashmir honeymoon special package houseboat Dal Lake',
      whatsappMessage: 'Hi Outbound Travelers, I\'d like to know more about the Kashmir Honeymoon Special 6N/7D. Please share details and customization options.',
      seasonal: false,
    },
    {
      id: 'family',
      name: 'Kashmir Family Deluxe',
      duration: '6 Nights / 7 Days',
      idealFor: 'Families with kids, Senior citizens',
      highlights: ['Srinagar 2N', 'Gulmarg 1N', 'Pahalgam 2N', 'Sonmarg day'],
      price: 'From ₹[TBD] per person',
      image: '/kashmir/pkg-family.jpg',
      alt: 'Kashmir family deluxe package with kids senior friendly',
      whatsappMessage: 'Hi Outbound Travelers, I\'d like to know more about the Kashmir Family Deluxe 6N/7D package. Please share details and customization options.',
      seasonal: false,
    },
    {
      id: 'premium',
      name: 'Kashmir Premium with Houseboat',
      duration: '7 Nights / 8 Days',
      idealFor: 'Luxury travelers, Depth seekers',
      highlights: ['1N premium houseboat', '4★ hotels', 'All four valleys'],
      price: 'From ₹[TBD] per person',
      image: '/kashmir/pkg-premium.jpg',
      alt: 'Kashmir premium tour package with heritage houseboat',
      whatsappMessage: 'Hi Outbound Travelers, I\'d like to know more about Kashmir Premium with Houseboat 7N/8D. Please share details and customization options.',
      seasonal: false,
    },
    {
      id: 'snow',
      name: 'Kashmir Snow Escape',
      duration: '5 Nights / 6 Days',
      idealFor: 'Snow lovers, Couples, Friend groups',
      highlights: ['Gulmarg 2N', 'Gondola Phase 2', 'Skiing add-on optional'],
      price: 'From ₹[TBD] per person',
      image: '/kashmir/pkg-snow.jpg',
      alt: 'Kashmir snow escape winter package December Gulmarg skiing',
      whatsappMessage: 'Hi Outbound Travelers, I\'d like to know more about the Kashmir Snow Escape 5N/6D package. Please share details and customization options.',
      seasonal: true,
      seasonMonths: [10, 11, 12, 1, 2, 3],
    },
  ] as Package[],
  itinerary: [
    { day: 1, title: 'Arrive Srinagar, Settle into the Valley', description: 'Airport pickup, check-in to Dal Lake-facing hotel or houseboat. Evening shikara cruise as the lake turns golden.', highlights: ['Airport pickup', 'Welcome shikara', 'Hotel check-in'], stay: 'Srinagar' },
    { day: 2, title: 'Srinagar Sightseeing — Gardens & Old City', description: 'Mughal gardens (Shalimar Bagh, Nishat Bagh, Chashme Shahi). Old city walk, Jamia Masjid, Pari Mahal viewpoint.', highlights: ['Mughal gardens trio', 'Old city walk', 'Pari Mahal sunset'], stay: 'Srinagar' },
    { day: 3, title: 'Drive to Gulmarg — Gondola Day', description: '2-hour scenic drive. Afternoon Gondola Phase 1 (and Phase 2 weather permitting). Optional snow play or pony ride in season.', highlights: ['Gondola Phase 1', 'Optional Phase 2', 'Snow play in season'], stay: 'Gulmarg' },
    { day: 4, title: 'Gulmarg to Pahalgam — The Scenic Drive', description: 'Long scenic drive via Awantipora ruins and saffron fields. Evening leisure on the Lidder river.', highlights: ['Saffron fields', 'Awantipora ruins', 'Lidder riverwalk'], stay: 'Pahalgam' },
    { day: 5, title: 'Pahalgam Local — Aru, Betaab, Chandanwari', description: 'Local taxi day to Aru Valley, Betaab Valley, and Chandanwari point-to-point as included.', highlights: ['Aru Valley', 'Betaab Valley', 'Chandanwari'], stay: 'Pahalgam' },
    { day: 6, title: 'Pahalgam to Sonmarg Day Trip and Return', description: 'Day trip to Sonmarg with optional Thajiwas glacier. Drive back to Srinagar by evening.', highlights: ['Sonmarg valley drive', 'Optional glacier pony', 'Return to Srinagar'], stay: 'Srinagar' },
    { day: 7, title: 'Departure', description: 'Breakfast and airport transfer. Last shikara optional.', highlights: ['Last shikara optional', 'Hotel checkout', 'Airport drop'], stay: 'Departure' },
  ] as ItineraryDay[],
  hotelTiers: [
    { tier: '3★ Comfort', description: 'Clean, well-located properties with friendly service and family rooms.', price: 'From ₹[TBD] per night' },
    { tier: '4★ Premium', description: 'Modern hotels with full amenities, central locations, reliable breakfast spreads.', price: 'From ₹[TBD] per night' },
    { tier: '5★ Luxury', description: 'Top hotels in Srinagar with valley views and full-service spas.', price: 'From ₹[TBD] per night' },
    { tier: 'Heritage Houseboat', description: 'Vetted deluxe houseboats on Dal/Nigeen Lake with private decks and home-cooked Kashmiri meals.', price: 'From ₹[TBD] per night' },
  ] as HotelTier[],
  months: [
    { month: 'Jan', rating: 'good', note: 'Deep winter, ideal for snow lovers, sub-zero.' },
    { month: 'Feb', rating: 'good', note: 'Snow continues, fewer crowds.' },
    { month: 'Mar', rating: 'best', note: 'Early tulips bloom mid-month, pleasant days.' },
    { month: 'Apr', rating: 'best', note: 'Tulip Festival peak, lush early spring.' },
    { month: 'May', rating: 'best', note: 'Perfect green valleys, 15–25°C.' },
    { month: 'Jun', rating: 'best', note: 'Peak season for families, school holidays.' },
    { month: 'Jul', rating: 'good', note: 'Some rain, valleys lush.' },
    { month: 'Aug', rating: 'good', note: 'Rain spells, monsoon-edge.' },
    { month: 'Sep', rating: 'best', note: 'Crisp clear days, autumn arrives.' },
    { month: 'Oct', rating: 'best', note: 'Golden chinars, the most photogenic month.' },
    { month: 'Nov', rating: 'okay', note: 'Cold setting in, fewer crowds, lower prices.' },
    { month: 'Dec', rating: 'good', note: 'Snow begins, Gulmarg ski season opens late month.' },
  ] as MonthRating[],
  seasons: [
    { id: 'spring', label: 'Tulip Spring', months: 'Late Mar–Apr', description: '1.5M tulips bloom. Cool days, light woollens. Book 45+ days in advance.', image: '/kashmir/season-spring.jpg' },
    { id: 'summer', label: 'Lush Summer', months: 'May–Aug', description: 'Green valleys, ideal for families and seniors. Pleasant 18–28°C.', image: '/kashmir/season-summer.jpg' },
    { id: 'autumn', label: 'Golden Autumn', months: 'Sep–Oct', description: 'Chinar leaves turn copper. The most photogenic Kashmir.', image: '/kashmir/season-autumn.jpg' },
    { id: 'winter', label: 'Snow Winter', months: 'Dec–Feb', description: 'Gulmarg becomes a ski resort. Pack for -5 to 5°C.', image: '/kashmir/season-winter.jpg' },
  ] as Season[],
  process: [
    { step: 1, title: 'Share your dates', description: 'WhatsApp or form — send us your travel month, group size, departure city.' },
    { step: 2, title: 'Get a custom itinerary', description: 'A Kashmir specialist sends a day-wise plan plus transparent quote within 2 hours.' },
    { step: 3, title: 'Refine until it\'s right', description: 'Swap hotels, change pace, add experiences. We iterate till it\'s yours.' },
    { step: 4, title: 'Travel with full support', description: 'One team handles airport pickup to drop. Your consultant stays reachable through your trip.' },
  ] as ProcessStep[],
  inclusions: [
    'Accommodation per chosen tier',
    'Daily breakfast and meals per package',
    'Airport pickup and drop in Srinagar',
    'All sightseeing transfers in private vehicle',
    'Driver who knows the routes',
    'One welcome shikara ride',
    'All applicable tolls and parking',
    'GST on services',
  ],
  exclusions: [
    'Flights/trains to Srinagar (can be booked on request)',
    'Gondola tickets, pony rides, skiing equipment',
    'Personal expenses, tips, room service',
    'Travel insurance (recommended, can be added)',
    'Anything not explicitly in inclusions',
  ],
  gallery: [
    { image: '/kashmir/gallery-01.jpg', alt: 'Shikara silhouette Dal Lake sunset Kashmir' },
    { image: '/kashmir/gallery-02.jpg', alt: 'Gulmarg gondola snow valley Kashmir' },
    { image: '/kashmir/gallery-03.jpg', alt: 'Pahalgam Lidder Valley scenic river view' },
    { image: '/kashmir/gallery-04.jpg', alt: 'Mughal garden Shalimar Bagh in spring Srinagar' },
    { image: '/kashmir/gallery-05.jpg', alt: 'Heritage houseboat interior on Dal Lake Kashmir' },
    { image: '/kashmir/gallery-06.jpg', alt: 'Sonmarg Thajiwas glacier trek in summer' },
    { image: '/kashmir/gallery-07.jpg', alt: 'Aru Valley meadow pine forest Pahalgam Kashmir' },
    { image: '/kashmir/gallery-08.jpg', alt: 'Tulip Garden Srinagar in full bloom April' },
    { image: '/kashmir/gallery-09.jpg', alt: 'Kashmir family enjoying shikara ride with kids' },
    { image: '/kashmir/gallery-10.jpg', alt: 'Honeymoon couple at Mughal garden Kashmir' },
    { image: '/kashmir/gallery-11.jpg', alt: 'Golden chinar leaves autumn Srinagar Kashmir' },
    { image: '/kashmir/gallery-12.jpg', alt: 'Gulmarg snow meadow winter Kashmir' },
  ],
  testimonials: [
    { name: 'Priya & Arun', city: 'Chennai', tripType: 'Honeymoon', quote: 'Outbound Travelers planned every minute of our honeymoon. The houseboat surprise on Day 4, the candlelit dinner on Dal Lake — we still talk about it. They even arranged idli on Day 3 morning.', rating: 5, date: 'April 2026', photo: '/testimonials/priya-arun.jpg' },
    { name: 'Rajesh Family', city: 'Bangalore', tripType: 'Family', quote: 'We traveled with my parents (70+) and two kids. Pace was perfect, transport was comfortable, hotels were clean. The team was a WhatsApp message away the whole trip.', rating: 5, date: 'June 2026', photo: '/testimonials/rajesh-family.jpg' },
  ] as Testimonial[],
  faqs: [
    { q: 'What is the best time to visit Kashmir?', a: 'It depends on what you want. Late March–April for tulips. May–August for lush family-friendly weather. September–October for autumn chinars. December–February for snow and Gulmarg skiing. Our consultants match your dates to the experience you want.' },
    { q: 'How many days are enough for a Kashmir tour?', a: '5–7 nights is the sweet spot. 5N/6D covers Srinagar, Gulmarg, Pahalgam. 6N/7D adds Sonmarg or a houseboat night. 7N/8D allows offbeat valleys like Doodhpathri.' },
    { q: 'Is Kashmir safe to visit right now?', a: 'Tourist Kashmir — Srinagar, Gulmarg, Pahalgam, Sonmarg, Doodhpathri — is currently well-trafficked with stable tourism. We monitor conditions and only operate where we\'d send our own families.' },
    { q: 'What is the average cost of a Kashmir tour package from South India?', a: 'A 6N/7D 3-star package starts from ₹[TBD] per person land-only, varying by month. Honeymoon and family deluxe packages start higher. Use the cost estimator above for a quick range.' },
    { q: 'Do Kashmir tour packages include flights?', a: 'Land packages don\'t include flights by default. We book flights on request and bill at actuals — usually 5–10% cheaper than direct booking due to consolidator rates.' },
    { q: 'Can I customize my Kashmir itinerary?', a: 'Yes — every Outbound Travelers itinerary is 100% customizable. Pace, cities, stay types, experiences, food preferences — all configurable.' },
    { q: 'Is Kashmir suitable for families with kids and senior citizens?', a: 'Absolutely. We design family-paced itineraries with shorter drives, kid-friendly hotels, and senior-friendly transport. Wheelchair accessibility can be arranged where available.' },
    { q: 'What should I pack for a Kashmir trip?', a: 'Light woollens for spring/autumn, heavy woollens and snow boots for winter, comfortable walking shoes year-round, sunscreen, and any prescription medication. Detailed packing list shared post-booking.' },
    { q: 'How do houseboats work — are they comfortable?', a: 'Our houseboats are vetted deluxe or premium tier on Dal and Nigeen lakes, with private bedrooms, attached bathrooms, sit-out decks, and home-cooked meals. They\'re typically a one-night experience, not the whole trip.' },
    { q: 'What is the difference between Gulmarg, Pahalgam, and Sonmarg?', a: 'Gulmarg is a high-altitude meadow with the gondola and skiing. Pahalgam is a river-valley town with Aru, Betaab, and Lidder forest walks. Sonmarg is a glacier-edge valley, often done as a day trip from Srinagar.' },
    { q: 'Will I get South Indian food in Kashmir?', a: 'Yes — most properties we work with arrange South Indian breakfasts on request. We pre-arrange idli, dosa, sambar rice, curd rice for families that want it. Mention this when you enquire.' },
    { q: 'Do I need an ID or permit to visit Kashmir?', a: 'Domestic travelers need only a government photo ID. Some restricted areas may have light checks — we handle all of that as part of your trip planning.' },
  ] as FAQ[],
  relatedDestinations: [
    { name: 'Ladakh', image: '/shared/ladakh-thumb.jpg', href: '/ladakh' },
    { name: 'Manali', image: '/shared/manali-thumb.jpg', href: '/manali' },
    { name: 'Shimla', image: '/shared/shimla-thumb.jpg', href: '/shimla' },
    { name: 'Sikkim', image: '/shared/sikkim-thumb.jpg', href: '/sikkim' },
  ] as RelatedDestination[],
  whatsapp: {
    number: '919876543210',
    heroMessage: 'Hi Outbound Travelers, I\'m interested in a Kashmir tour package. Please share itinerary options and a quote.',
    stickyMessage: 'Hi Outbound Travelers, I\'m planning a Kashmir trip. Can someone help me plan and quote?',
    floaterMessage: 'Hi Outbound Travelers, I\'m interested in a Kashmir tour package. Please share itinerary options and a quote.',
    finalCtaMessage: 'Hi Outbound Travelers, I\'m ready to plan my Kashmir trip. Please send me your best itinerary and quote.',
    postFormMessage: 'Hi Outbound Travelers, I just submitted my Kashmir enquiry. Travel month: {month}, {travelers} travelers from {city}, trip type: {tripType}. Looking forward to the itinerary and quote.',
  } as WhatsAppConfig,
  leadForm: {
    title: 'Get your Kashmir quote',
    subtitle: 'Tell us a bit about your trip — we\'ll come back within 2 hours.',
    submitButtonText: 'Get my Kashmir quote',
    successMessage: 'Got it! Your Kashmir consultant will WhatsApp you within 2 hours. Meanwhile, save our number: +91-98765-43210.',
    destinationId: 'kashmir',
    destinationName: 'Kashmir',
  } as LeadFormConfig,
  seoContent: {
    h2: 'Planning Your Kashmir Trip with Outbound Travelers',
    sections: [
      {
        h3: 'Which Kashmir circuit is right for you?',
        body: 'The classic Kashmir tour package covers Srinagar, Gulmarg, and Pahalgam — three distinct landscapes in five or six nights. First-time travelers and families find this circuit ideal. Extend to seven nights and Sonmarg joins the route, adding the Thajiwas glacier day. Offbeat travelers can swap one city for Doodhpathri or Yusmarg, meadow valleys that see a fraction of the tourist footfall of Gulmarg.',
      },
      {
        h3: 'Kashmir from South India — flights, transit, what to plan around',
        body: 'Direct flights to Srinagar run from Delhi and Mumbai. From Chennai, Bangalore, Kochi, and Hyderabad, one connecting flight via Delhi is standard — total travel time four to five hours. Morning departures from South Indian cities typically land in Srinagar by early afternoon, leaving the first evening free for a shikara ride. We handle flight booking on request and consistently find consolidator rates five to ten percent below direct booking.',
      },
      {
        h3: 'Customizing your Kashmir package',
        body: 'Honeymoon travelers typically add a houseboat night, private shikara, candlelit dinner, and a half-day photographer — all bookable as add-ons to any base package. Families with seniors request shorter daily drives, ground-floor rooms, and South Indian breakfast arrangements. Adventure travelers add Gondola Phase 2, skiing in Gulmarg in winter, or a guided trek in summer. Every Kashmir tour package we build starts from your requirements, not from a fixed template.',
      },
      {
        h3: 'Why book Kashmir with Outbound Travelers',
        body: 'Our Kashmir specialists have planned over 2,500 trips to the valley. Every houseboat and hotel on our list is personally vetted. You get a dedicated consultant reachable on WhatsApp from the day you enquire to the day you return. Quotes come back within two hours. And because we specialize in South Indian travelers, we understand the food preferences, family structures, and travel pace that most North India-based operators miss.',
      },
    ],
  },
}
